(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_MoreThan_160x600_atlas_", frames: [[0,0,259,107]]}
];


// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_MoreThan_160x600_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.RULE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,2,1).p("A3LAAMAuXAAA");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.RULE, new cjs.Rectangle(-149.3,-1,298.70000000000005,2), null);


(lib.LINER = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,2,1).p("A3LAAMAuXAAA");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.LINER, new cjs.Rectangle(-149.3,-1,298.70000000000005,2), null);


(lib.LINEL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,2,1).p("A3LAAMAuXAAA");
	this.shape.setTransform(0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.LINEL, new cjs.Rectangle(-149.2,-1,298.7,2), null);


(lib.HousingncOUTLINEai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MoreThan-worker.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,1,1).p("AGtD0QAChVAAkEQgKgUgfhGQgghLgHgOQg+AhgcAPQgxAZgkAHQgdgmgvhEQgzhIgHgMQgdAIhOAVQhVAXgYAFQgWgDg/gOQhggVhHgOQgDCPAAD0QgBCIAAD9");
	this.shape.setTransform(100.425,190.375);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(56.3,150.3,88.3,80.19999999999999);


(lib.HousingncALLai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MoreThan-worker.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,1,1).p("AGvhlQgKgUgfhGQgghLgHgOQg+AhgcAPQgxAZgkAHQgdgmgvhEQgzhIgHgMQgdAIhOAVQhVAXgYAFQgWgDg/gOQhggVhHgOQgDCPAAD0QgBCIAAD9QAEAAAGgBQAWgEApgJQAzgLANgFQAAiSgFnpQAEABAEABQAXAGArANQAwAPAaAGQABA1ACDjQABCsADBsQABAAAEAAQAZgEB5gSQBbgOA7gNQgChKAAiKQAAiSgChCQADACADABQAKAEAOAFQALADAUAHQAFCEAAEOIANgCQB8gVAigEQAFAAAQgDQARgEAAgBQAChVAAkEgAkKjEIgCBTIBLALIAAhRgAjCj3IDehiQAJAOAzBFQAtA9ASAYQA+AZADgDQAwgdBNgyQAUAzAiBQIAkACAgui0IAECgICCAUIgCiXgAEghhIAAB6IBIAMIgChzgAFDBnIAAB6IAigEIAAh0gAg5BHIADDVICMgOIgCjCgAkPBlIACDjIBPgKIgBjZg");
	this.shape.setTransform(100.425,190.375);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(56.3,150.3,88.3,80.19999999999999);


(lib.HEAD4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AASBSIAAgQIATAAQAEAAAAgHIAAhUQAAgmghAAQgVAAgOATQgNAUAAAhIAAAyQAAAHAEAAIAUAAIAAAQIhKAAIAAgQIAUAAQAFAAAAgHIAAhxQAAgHgFAAIgUAAIAAgQIANAAQAYAAAMgDIAAAqQAQgrApAAQAyAAAAA3IAABVQAAAHAEAAIAVAAIAAAQg");
	this.shape.setTransform(63.925,4.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag5A9QgWgXgBgmQABgkAWgXQAXgYAiAAQAkAAAWAYQAWAXAAAkQAAAmgWAXQgWAXgkAAQgjAAgWgXgAgogwQgPAQAAAgIAAABQAAAgAPARQAOASAaAAQAaAAAPgSQAPgRAAggIAAgBQAAgfgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_1.setTransform(45.35,4.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgkBvIAAgPIAUAAQAEAAABgHIAAhsQAAgNgIAAIgRAAIAAgPIAOAAQAWAAANgDIAACLQgBAHAFAAIAUAAIAAAPgAgMhRQgFgEAAgIQAAgHAFgFQAFgFAHAAQAHAAAFAFQAFAFAAAHQAAAHgFAFQgFAGgHAAQgHAAgFgGg");
	this.shape_2.setTransform(32.1,1.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJBbQgKgKAAgWIAAhoIgZAAIAAgNIASgCQALgBAAgLIADgcIARAAIAAAnIAlAAIAAAQIgmAAIAABoQAAAOAGAGQAFAGAMAAQAJAAAJgEIAAAQQgLAEgMAAQgWAAgJgKg");
	this.shape_3.setTransform(22.675,2.95);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhBBIQgOgMAAgSQAAgbAbgOQAZgMA5gHIAAgJQAAgUgKgKQgKgKgVAAQgdAAgLAOQAKAEAAALQAAAHgEAEQgFAFgHAAQgSAAAAgTQAAgTAUgMQATgLAcAAQAgAAAPAOQAQAOAAAcIAABVQAAAGAEAAIAVAAIAAAQIgsAAQgEgOgBgUQgHARgRAKQgQALgUAAQgXAAgNgMgAgiAJQgVAKAAAUQAAANAJAHQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgNQgtAEgTAJg");
	this.shape_4.setTransform(9.575,4.75);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag2A9QgWgXAAgmQAAglAXgWQAXgYAkAAQAgAAATAQQAUAPAAAZQAAAKgGAGQgGAHgIAAQgIAAgFgFQgEgEAAgGQAAgQAQgCQgIgegpAAQgaAAgQASQgQASAAAeIAAABQAAAgAPARQAQATAaAAQArAAALgqIAQAGQgOA0g5AAQglgBgWgWg");
	this.shape_5.setTransform(-7.725,4.75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhBAdIAAhXQAAgHgEAAIgVAAIAAgQIAyAAIAABtQAAAlAhAAQAVgBANgSQANgSAAgdIAAg5QAAgHgEAAIgVAAIAAgQIAyAAIAACIQAAAHAEAAIAWAAIAAAQIgOAAQgXAAgOACIAAgmQgQAogmAAQgzAAAAg1g");
	this.shape_6.setTransform(-25.725,4.95);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhHBaQgUgWAAgnQAAglAVgWQAUgYAhAAQArAAAQAnIAAhHQAAgHgEAAIgVAAIAAgQIAOAAQAXAAANgCIAADGQAAAGAFAAIAUAAIAAAQIgvAAIgCgkQgRAogrAAQghgBgVgWgAgygTQgPAQAAAeIAAAEQAAAfAPARQAOARAZAAQAYAAAOgRQAPgSAAgeIAAgEQAAgcgPgSQgPgRgXAAQgZAAgOARg");
	this.shape_7.setTransform(-44.675,1.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhTBuIAAgQIAVAAQAFAAAAgHIAAitQAAgHgFAAIgVAAIAAgQICgAAIAAAwIgSAAIgCgZQgBgHgLAAIhNAAIAABUIAxAAQAHABAAgHIABgQIAPAAIAAA9IgPAAIgBgRQAAgHgHAAIgxAAIAABYIBVAAQALAAABgHIACgZIARAAIAAAwg");
	this.shape_8.setTransform(-64.475,1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD4, new cjs.Rectangle(-80.5,-14,161,37), null);


(lib.HEAD3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhHBaQgUgXAAgmQAAglAVgWQAUgYAhAAQArABAQAnIAAhHQAAgJgEABIgVAAIAAgQIAOAAQAXAAANgCIAADGQAAAGAFABIAUAAIAAAPIgvAAIgCgkQgRAngrABQghgBgVgWgAgygUQgPASAAAdIAAAEQAAAeAPASQAOAQAZABQAYgBAOgQQAPgSAAgeIAAgEQAAgcgPgSQgPgRgXAAQgZAAgOAQg");
	this.shape.setTransform(27.025,30.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag5A8QgWgWAAgmQAAgkAWgXQAWgXAkgBQAjAAAWAYQAWAXAAAkQAAAmgWAWQgWAYgkAAQgjAAgWgYgAgogxQgPASAAAfIAAACQAAAeAPASQAPARAZABQAagBAPgRQAPgSAAgeIAAgCQAAgfgPgSQgPgRgZAAQgaAAgPARg");
	this.shape_1.setTransform(8.1,33.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag5A8QgWgWgBgmQABgkAWgXQAXgXAigBQAkAAAWAYQAXAXgBAkQABAmgXAWQgWAYgkAAQgjAAgWgYgAgogxQgPASAAAfIAAACQAAAeAPASQAOARAaABQAagBAPgRQAPgSAAgeIAAgCQAAgfgPgSQgPgRgaAAQgZAAgPARg");
	this.shape_2.setTransform(-9.65,33.75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhQBuIAAgQIAWAAQAEAAAAgHIAAitQAAgHgEAAIgWAAIAAgPIChAAIAAAvIgRAAIgDgZQAAgHgMAAIhOAAIAABaIAwAAQAHAAAAgGIAAgRIAQAAIAAA9IgQAAIAAgQQAAgHgHAAIgwAAIAABLQAAAHAFAAIAWAAIAAAQg");
	this.shape_3.setTransform(-27.9,30.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AATBvIAAgQIATAAQAEAAAAgHIAAhVQAAglghAAQgWAAgNATQgOATAAAiIAAAyQAAAHAFAAIAUAAIAAAQIhLAAIAAgQIAVAAQAEAAAAgHIAAisQAAgIgEAAIgWAAIAAgPIAPAAQAXAAANgDIAABkQARgqAnAAQAzAAgBA2IAABWQABAHAEAAIAVAAIAAAQg");
	this.shape_4.setTransform(31.6,1.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag8BFIAAgpIAUAAIAAAgQAPAJAYAAQAmAAAAgdQAAgPgMgHQgIgFgVgEQgagGgNgGQgRgLAAgVQAAgWAQgNQARgNAbAAQAhAAAXAPIAAAoIgUAAIAAgeQgNgJgWAAQgmAAAAAcQAAAOANAHQAIADAWAFQAaAFAMAIQARALAAAVQgBAXgQAMQgQAOgdAAQghAAgagPg");
	this.shape_5.setTransform(15,4.75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag3A8QgVgXAAglQAAgjAWgYQAWgYAjAAQAiABAUAVQAUAWAAAkIAAAHIiAAAQAAAcAPASQAQARAaABQAqgBAMgpIAQAGQgGAXgSAOQgSAPgdAAQglAAgXgYgAA0gKQAAgbgNgPQgNgPgXAAQgXAAgPAPQgOAQgCAaIBnAAIAAAAg");
	this.shape_6.setTransform(-0.65,4.75);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag/BSIAAgQIAVAAQAEAAABgHIAAhxQgBgHgEAAIgVAAIAAgQIAOAAQAWAAAOgDIAAAmQALgnAgAAQAQAAAJAKQAJAIAAAOQAAAXgUAAQgGAAgEgEQgEgEgBgGQAAgMANgCQgDgKgOAAQgTAAgJATQgKASAAAeIAAA4QAAAHAEAAIAWAAIAAAQg");
	this.shape_7.setTransform(-16.05,4.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhQBuIAAgQIAWAAQAEAAAAgHIAAitQAAgHgEAAIgWAAIAAgQIChAAIAAAwIgRAAIgDgZQAAgHgMAAIhOAAIAABaIAwAAQAHAAAAgHIAAgQIAQAAIAAA9IgQAAIAAgQQAAgHgHAAIgwAAIAABLQAAAHAFAAIAWAAIAAAQg");
	this.shape_8.setTransform(-32.4,1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-80.5,-14,161,66), null);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhXBXQAAgaAngJQgegFAAgYQAAgVAbgIQgYgPAAgeQgBgZAUgRQATgQAfAAQAeAAATATQAGgfAWAAQAIAAAFAFQAFAEgBAHQAAAGgDAEQgEAFgGAAQgMAAgCgMQgHAHgEANQAKANAAASQAAAagTAQQgTAOgfgBQgQAAgPgEQgTADAAAOQAAAPAaAAIA+gBQAzAAAAAoQAAAZgYAOQgYAMgpAAQhPAAABgjgAhDBVQAAAYA7ABQBEgBAAggQAAgMgJgFQgIgFgUAAIg1AAQglAIAAAWgAgnhTQgMALAAAVIAAABQAAATAMAMQALALAUAAQATAAAMgLQAMgLAAgUIAAgBQAAgVgMgLQgLgMgTAAQgUAAgMAMg");
	this.shape.setTransform(51.2,7.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AASBSIAAgQIATAAQAEAAAAgHIAAhUQAAgmghAAQgVAAgOATQgNAUAAAhIAAAyQAAAHAEAAIAUAAIAAAQIhKAAIAAgQIAUAAQAFAAAAgHIAAhxQAAgHgFAAIgUAAIAAgQIANAAQAYAAAMgDIAAAqQAQgrApAAQAyAAAAA3IAABVQAAAHAEAAIAVAAIAAAQg");
	this.shape_1.setTransform(32.675,4.575);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AglBvIAAgPIAVAAQAEAAABgHIAAhsQAAgNgIAAIgSAAIAAgPIAPAAQAWAAANgDIAACLQgBAHAFAAIAUAAIAAAPgAgMhRQgFgEAAgIQAAgHAFgFQAFgFAHAAQAHAAAFAFQAFAFAAAHQAAAHgFAFQgFAGgHAAQgHAAgFgGg");
	this.shape_2.setTransform(18.6,1.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag7BFIAAgpIATAAIAAAgQAPAJAXAAQAoAAAAgdQAAgPgNgHQgJgFgUgEQgbgGgLgGQgSgLABgVQAAgWAPgNQASgNAaAAQAgAAAYAPIAAAoIgUAAIAAgeQgNgJgVAAQgmAAgBAcQABAOANAHQAHADAWAFQAaAFAMAIQAQALAAAVQABAXgRAMQgQAOgdAAQghAAgZgPg");
	this.shape_3.setTransform(7.1,4.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhBAdIAAhXQAAgHgEAAIgVAAIAAgQIAyAAIAABtQAAAlAhAAQAVgBANgSQANgSAAgdIAAg5QAAgHgEAAIgVAAIAAgQIAyAAIAACIQAAAHAEAAIAWAAIAAAQIgOAAQgXAAgOACIAAgmQgQAogmAAQgzAAAAg1g");
	this.shape_4.setTransform(-9.575,4.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag5A9QgWgXgBgmQABgkAWgXQAXgYAiAAQAkAAAWAYQAXAXgBAkQABAmgXAXQgXAXgjAAQgjAAgWgXgAgogwQgPAQAAAgIAAABQAAAgAPARQAPASAZAAQAaAAAPgSQAPgRAAggIAAgBQAAgfgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_5.setTransform(-27.75,4.75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAfBuIAAgQIAVAAQAGAAAAgIIAAhQIhzAAIAABQQAAAIAGAAIAVAAIAAAQIhOAAIAAgQIAWAAQAFAAgBgIIAAisQABgHgFAAIgWAAIAAgQIBOAAIAAAQIgVAAQgGAAAAAHIAABNIBzAAIAAhNQAAgHgGAAIgVAAIAAgQIBOAAIAAAQIgWAAQgFAAAAAHIAACsQAAAIAFAAIAWAAIAAAQg");
	this.shape_6.setTransform(-48.15,1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-80.5,-14,161,37), null);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag3A8QgVgXAAglQAAgkAWgXQAWgXAjgBQAiAAAUAXQAUAVAAAkIAAAHIiAAAQAAAcAPASQAQARAaABQAqgBALgpIARAGQgGAXgSAOQgSAPgdAAQglgBgXgXgAA0gKQAAgbgNgPQgNgPgXAAQgXAAgPAQQgOAOgCAbIBnAAIAAAAg");
	this.shape.setTransform(26.45,33.75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag/BSIAAgQIAVAAQAEAAAAgHIAAhxQAAgHgEAAIgVAAIAAgQIAOAAQAWAAAOgDIAAAmQALgnAgAAQAQAAAJAKQAJAIAAAOQAAAXgUAAQgGAAgFgEQgDgEAAgGQAAgMAMgCQgDgKgOAAQgTAAgJATQgKASAAAeIAAA4QAAAHAEAAIAWAAIAAAQg");
	this.shape_1.setTransform(11.05,33.575);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhBBIQgOgMAAgTQAAgaAbgOQAZgMA5gHIAAgJQAAgUgKgLQgKgJgVAAQgdAAgLAPQAKADAAALQAAAHgEAEQgFAFgHAAQgSgBAAgSQAAgTAUgMQATgKAcgBQAgAAAPAOQAQAOAAAcIAABVQAAAGAEABIAVAAIAAAPIgsAAQgEgOgBgUQgHARgRALQgQAJgUABQgXAAgNgMgAgiAJQgVAKAAAUQAAANAJAHQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgNQgtAEgTAJg");
	this.shape_2.setTransform(-4.225,33.75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhEBTQgdgeAAg0QAAg0AdgfQAdgeArAAQAaAAATAMQASAMAIAUIAEgoIAQAAIAABPIgVAAQgMhCg4AAQghAAgVAZQgWAZAAArIAAAFQAAAsAVAZQAVAYAiAAQAeAAASgOQAVgRAEggIATADQgEAjgYAVQgZAVgnAAQgtAAgdgeg");
	this.shape_3.setTransform(-24.25,30.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AATBvIAAgQIATAAQAEAAAAgHIAAhVQAAglghAAQgWAAgNATQgOATAAAiIAAAyQAAAHAFAAIAUAAIAAAQIhLAAIAAgQIAVAAQAEAAAAgHIAAisQAAgIgEAAIgVAAIAAgPIAOAAQAXAAANgDIAABkQARgqAnAAQAzAAgBA2IAABWQABAHAEAAIAVAAIAAAQg");
	this.shape_4.setTransform(38,1.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJBbQgKgKAAgWIAAhoIgZAAIAAgNIASgCQALgBAAgLIADgcIARAAIAAAnIAlAAIAAAQIgmAAIAABoQAAAOAGAGQAFAGAMAAQAJAAAJgEIAAAQQgLAEgMAAQgWAAgJgKg");
	this.shape_5.setTransform(23.475,2.95);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgkBvIAAgQIAUAAQAFAAAAgHIAAisQAAgIgFAAIgUAAIAAgPIAOAAQAWAAANgDIAADGQAAAHAEAAIAUAAIAAAQg");
	this.shape_6.setTransform(14.275,1.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhBBIQgOgMAAgSQAAgbAbgOQAZgMA5gHIAAgJQAAgUgKgKQgKgKgVAAQgdAAgLAOQAKAEAAALQAAAHgEAEQgFAFgHAAQgSAAAAgTQAAgTAUgMQATgLAcAAQAgAAAPAOQAQAOAAAcIAABVQAAAGAEAAIAVAAIAAAQIgsAAQgEgOgBgUQgHARgRAKQgQALgUAAQgXAAgNgMgAgiAJQgVAKAAAUQAAANAJAHQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgNQgtAEgTAJg");
	this.shape_7.setTransform(1.675,4.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag3A8QgVgXAAglQAAgjAWgYQAWgYAjAAQAiABAUAVQAUAWAAAkIAAAHIiAAAQAAAcAPASQAQARAaABQAqgBAMgpIAQAGQgGAXgSAOQgSAPgdAAQglAAgXgYgAA0gKQAAgbgNgPQgNgPgXAAQgXAAgPAPQgOAQgCAaIBnAAIAAAAg");
	this.shape_8.setTransform(-15.95,4.75);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAfBuIAAgQIAVAAQAGAAAAgIIAAhQIhzAAIAABQQAAAIAGAAIAVAAIAAAQIhOAAIAAgQIAWAAQAFAAgBgIIAAisQABgHgFAAIgWAAIAAgQIBOAAIAAAQIgVAAQgGAAAAAHIAABNIBzAAIAAhNQAAgHgGAAIgVAAIAAgQIBOAAIAAAQIgWAAQgFAAAAAHIAACsQAAAIAFAAIAWAAIAAAQg");
	this.shape_9.setTransform(-36,1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-80.5,-14,161,66), null);


(lib.HEADend = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAPQgGgGAAgJQAAgJAGgFQAGgHAJAAQAJAAAGAHQAHAFAAAJQAAAJgHAGQgGAHgJAAQgJAAgGgHg");
	this.shape.setTransform(47.475,98.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhRBaQgggjAAg3QAAg3AhgiQAhgkA0AAQAxAAAeAgQAeAgAAA1IAAALIjJAAQAAAtAZAdQAaAeAqAAQBHAAARhEIATAGQgIAlgbAVQgcAXgtAAQg1AAghgkgABYgOQAAgqgWgZQgXgagnAAQgmAAgZAaQgZAZgDAqICvAAIAAAAg");
	this.shape_1.setTransform(31.05,88.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhaB7IAAgSIAjAAQAGAAAAgKIAAi3QAAgLgGAAIgjAAIAAgSIAMAAQAfAAAWgEIAAA6QASg7AxAAQAYAAANANQAMAMAAASQAAAdgXAAQgHAAgGgFQgFgFAAgHQAAgQARgCQgDgSgZAAQgfAAgQAfQgPAeAAAxIAABYQAAAKAGAAIAkAAIAAASg");
	this.shape_2.setTransform(8.775,88.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhfBsQgVgSAAgcQAAgnAogVQAngUBYgIIAAgOQAAgjgQgQQgQgQgjAAQg0AAgSAeQAQADAAAQQAAASgUAAQgVAAAAgYQAAgaAdgRQAcgSAoAAQBbAAAABUIAACFQAAAKAGAAIAiAAIAAASIg8AAQgDgUgCgjQgKAcgaARQgYAQghAAQgiAAgUgSgAg5ALQgiAQAAAgQAAAVAPANQAQAOAZAAQAmAAAYgbQAYgbAAgqIAAgVQhMAHggAOg");
	this.shape_3.setTransform(-13.075,88.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhQBbQghgiAAg5QAAg2AjgkQAigjA1AAQAuAAAdAXQAdAYAAAmQAAALgGAIQgGAHgKAAQgUAAAAgSQAAgUAUAAQgMg3hGAAQgqAAgbAdQgbAdAAAwIAAACQAAAwAZAcQAaAeArAAQBIAAAQhFIATAGQgJAmgbAVQgcAXgrAAQg2AAghgjg");
	this.shape_4.setTransform(-38.475,88.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAfCoIAAgTIAgAAQAGAAAAgJIAAiKQAAg8g2AAQgkAAgXAhQgYAhAAA4IAABMQAAAJAGAAIAjAAIAAATIhrAAIAAgTIAjAAQAGAAAAgJIAAkSQAAgLgGAAIgkAAIAAgSIAOAAQAfAAAWgEIAACdQAbhEA9AAQBLAAAABOIAACMQAAAJAGAAIAjAAIAAATg");
	this.shape_5.setTransform(52.425,28.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgKCJQgOgOgBggIAAinIgnAAIAAgPIAdgDQANAAAAgMIAEgsIASAAIAAA4IA8AAIAAASIg8AAIAACnQAAApAkAAQAKAAATgFIAAATQgRAFgPAAQgfAAgMgOg");
	this.shape_6.setTransform(31.45,30.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag1CoIAAgTIAjAAQAGAAAAgJIAAkSQAAgLgGAAIgjAAIAAgSIANAAQAgAAAVgEIAAEzQAAAJAGAAIAjAAIAAATg");
	this.shape_7.setTransform(18.45,28.325);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhfBsQgVgSAAgcQAAgoAogUQAngUBYgIIAAgOQAAgjgQgQQgQgQgjAAQg0AAgSAeQAQADAAAQQAAASgUAAQgVABAAgZQAAgaAdgRQAcgSAoAAQBbAAAABUIAACFQAAAKAGAAIAiAAIAAASIg8AAQgDgUgCgjQgKAcgaARQgYAQghAAQgiAAgUgSgAg5AMQgiAPAAAgQAAAWAPAMQAQAOAZAAQAmAAAYgbQAYgaAAgrIAAgVQhMAHggAPg");
	this.shape_8.setTransform(0.325,33.05);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhRBaQgggjAAg3QAAg3AhgiQAhgkA0AAQAyAAAdAgQAeAgAAA1IAAALIjJAAQAAAtAZAdQAaAeAqAAQBIAAAQhEIATAGQgIAkgaAWQgdAXgsAAQg1AAgigkgABZgOQgBgrgWgYQgXgagmAAQgnAAgaAaQgXAagEApICwAAIAAAAg");
	this.shape_9.setTransform(-25.6,33.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAfCoIAAgTIAgAAQAGAAAAgJIAAiKQAAg8g2AAQgkAAgXAhQgYAhAAA4IAABMQAAAJAGAAIAjAAIAAATIhrAAIAAgTIAjAAQAGAAAAgJIAAkSQAAgLgGAAIgkAAIAAgSIAOAAQAfAAAWgEIAACdQAbhEA9AAQBLAAAABOIAACMQAAAJAGAAIAjAAIAAATg");
	this.shape_10.setTransform(-52.125,28.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAfB7IAAgSIAgAAQAGAAAAgKIAAiHQAAg+g2AAQglAAgXAhQgXAhAAA4IAABLQAAAKAGAAIAjAAIAAASIhsAAIAAgSIAjAAQAGAAAAgKIAAi3QAAgLgGAAIgjAAIAAgSIAOAAQAeAAAXgEIAABEQAZhFA+AAQBMAAAABQIAACJQAAAKAGAAIAjAAIAAASg");
	this.shape_11.setTransform(33.975,-22.675);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhfBsQgVgSAAgcQAAgoAogUQAngUBYgIIAAgOQAAgjgQgQQgQgQgjAAQg0AAgSAeQAQADAAAQQAAASgUAAQgVABAAgZQAAgaAdgRQAcgSAoAAQBbAAAABUIAACGQAAAJAGAAIAiAAIAAASIg8AAQgDgVgCgiQgKAcgaARQgYAQghAAQgiAAgUgSgAg5AMQgiAQAAAfQAAAWAPAMQAQAOAZAAQAmAAAYgbQAYgbAAgqIAAgVQhMAHggAPg");
	this.shape_12.setTransform(7.675,-22.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAfCoIAAgTIAgAAQAGAAAAgJIAAiKQAAg8g2AAQgkAAgXAhQgYAhAAA4IAABMQAAAJAGAAIAjAAIAAATIhrAAIAAgTIAjAAQAGAAAAgJIAAkSQAAgLgGAAIgkAAIAAgSIAOAAQAfAAAWgEIAACdQAbhEA9AAQBLAAAABOIAACMQAAAJAGAAIAjAAIAAATg");
	this.shape_13.setTransform(-19.775,-27.125);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgLCJQgOgOABggIAAinIgoAAIAAgQIAegCQAMAAAAgMIAEgsIATAAIAAA4IA7AAIAAASIg8AAIAACnQAAApAlAAQAJAAATgFIAAATQgQAFgRAAQgeAAgNgOg");
	this.shape_14.setTransform(-40.75,-25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhRBaQgggjAAg3QAAg2AhgkQAhgjA0AAQAxAAAeAgQAeAgAAA1IAAALIjJAAQAAAtAZAdQAaAeAqAAQBHAAARhEIATAFQgIAmgbAVQgcAXgtAAQg0AAgigkgABZgNQgBgrgWgaQgXgZgnAAQgmAAgaAaQgXAagEAqICwAAIAAAAg");
	this.shape_15.setTransform(43.85,-77.85);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhaB7IAAgSIAjAAQAGAAAAgKIAAi3QAAgLgGAAIgjAAIAAgSIAMAAQAfAAAWgEIAAA6QASg7AxAAQAYAAANANQAMAMAAASQAAAdgXAAQgHAAgGgFQgFgFAAgHQAAgQARgCQgDgSgZAAQgfAAgQAfQgPAeAAAxIAABYQAAAKAGAAIAkAAIAAASg");
	this.shape_16.setTransform(21.575,-78.125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhVBbQghgjAAg4QAAg3AigjQAhgjA0AAQA1AAAgAjQAhAiAAA4QAAA4ghAjQghAjg1AAQg0AAghgjgAhDhNQgZAdAAAvIAAACQAAAxAZAcQAZAdAqAAQArAAAZgdQAagdAAgwIAAgCQAAgwgZgcQgZgdgrAAQgqAAgaAdg");
	this.shape_17.setTransform(-1.325,-77.85);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgOCmIh6k0IAAEXQAAAKAGAAIAkAAIAAATIhoAAIAAgTIAkAAQAGAAAAgKIAAkTQAAgJgGAAIgkAAIAAgTIBQAAIB1EmIB5kmIBPAAIAAATIgjAAQgHAAAAAJIAAETQAAAKAHAAIAjAAIAAATIhuAAIAAgTIAlAAQAGAAAAgKIAAkaIiAE3g");
	this.shape_18.setTransform(-35.1,-82.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEADend, new cjs.Rectangle(-81,-116.9,162,233.8), null);


(lib.GradHatncOUTLINEai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MoreThan-worker.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("Ahsl1ImVDPICmBKIgCBAQgDBHAAAkQAAAtCDA5QCHA8BzgEQB9gEBQgkQBWgmAAg+QAAhUgDhEQA5AmAGBrQAEA6gIBcQAAAuANAjQAHASAGAJIARh3IANB7QAKgdAJgiQAShDgIgVQgIgVgLgKIgKgGQAGg2gGg7QgLh0g3gYICUhig");
	this.shape.setTransform(410.4351,187.9416);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(357.3,149.6,106.30000000000001,76.5);


(lib.GradHatncALLai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MoreThan-worker.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AE9g3IABAsQACA3AAA1QAAA+hWAmQhQAkh9AEQhzAEiHg8QiDg5AAgtQAAgkADhHIAChAIimhKIGVjPIJuC6IiUBiQA2AXAMBxQAGA8gGA5IAKAGQALAKAIAVQAIAVgSBDQgJAigKAdIgNh7IgRB3QgGgJgHgSQgNgjAAguQAKhqgHhAQgLhagzgjgAAXjQQADgQAAgCQAAgOgQAFQgOAFgRAPQgRAQgCAOQgDAQAVAEQAOACAYAHQAAgDABgEQAEgdACgQICQAwQCYA0AoAQQAEABADACIgxAgIgBABIjrCaImsi+AD3hRQg4gPhAgOQhTgTgSAAQgNAAADgbQBHAUCgA3QAfALAiALQgPgIgRgFQgQgEgRgFgAE4g7QACABADABIAAACQgBgBAAAAQgCgBgCgCg");
	this.shape.setTransform(410.4344,187.9416);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(357.3,149.6,106.30000000000001,76.5);


(lib.FreshFood2ncOUTLINEai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MoreThan-worker.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("ABfFdQg4ATgIAHQgNANARAmQANAeBHgQQBDgOAoggQAvgmALgHQAagQAngIQgOAqA3AXQA3AXAxgkQAbAXAlgPQAjgOANggQBAgNgGg8QgGg3glgWQAqgcgTgsQgPgkgogZQAVgqgwgpQgxgrgjAhQgKgvgvAIQgaAEgIgBQgQgDgGgUQgHgcgoAHQgmAGgbAbIgDjGIhmhtIgBg2IkjADIAAA2IhoCAIABGZQgIheheAXQAJghgRgRQgJgKgfgLQgdgIgIgKQgOgRANggQhAAiAEAyQAEAvApAKQghAJgRAjQgQAiAJAkIgQAGQgngYglANQggALgTAjQgSAhAHAiQAIAmAkATQAsAWAwABQAtAAAjgTQALALAOAHQBHAkBDgPQBDgPANg3ICpACQAVAaAmACQAWAAAvgOgABlFbQgDABgDAB");
	this.shape.setTransform(525.9798,80.5131);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(458.4,33.3,135,92.9);


(lib.FreshFood2ncALLai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MoreThan-worker.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("ABHBKQAJgigQgSQgKgKgegLQgcgJgJgJQgOgQANghQg/AiAEAzQAEAvApAK");
	this.shape.setTransform(483.8151,81.1034);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("ACEAFQAAiHiKA6QgogVgiAOQgeANgNAiQgOAgAKAiQAMAlAkAT");
	this.shape_1.setTransform(488.075,96.9185);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AAEhSQgmgYglANQggALgTAiQgSAiAHAhQAIAmAkASQBNAoBJgaQBJgZAChBQAFiJiJA4g");
	this.shape_2.setTransform(473.1628,108.973);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AgVhSQgegTgeANQgcAMgPAgQgPAgAIAfQAJAjAkATQBOAnBFgVQBHgVAChBQACg7glgcQgsgghMAgg");
	this.shape_3.setTransform(492.5159,111.4082);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AhvgBIDfAD");
	this.shape_4.setTransform(511.675,113.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AACBnIgDjM");
	this.shape_5.setTransform(551.1,62.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AB0hAQgSAMg+ANQg7ANgzACQgtADAEAqQACARAKANQALAOAOAA");
	this.shape_6.setTransform(533.0548,100.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AgMjMQgMgDgOAEQgbAHgHAfQghghgkAiQgkAiAaAhQgXgBgRANQgQAMgEARQgJAsBAACQgUA1AAACQADARA4ACQAAAMgIAlQgBAeAgAAQgGAXANARQANAQAXAFQA4ALAZgzQAOATAlAIQAlAIAhgKQBZgagnhr");
	this.shape_7.setTransform(568.0601,93.6529);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AlABgQAVgHBdgXQBUgXANgTQAHgJgGgRQgKgXgFgMQgVgvAfgVQgVgPATgbQATgcApgDQgYgWAKgZQAJgXAdgRQAcgQAZAAQAdAAAGAWQAGAUAQADQAHABAagEQAvgIALAvQAjghAwArQAwAqgUAqQAoAZAPAkQATAsgrAbQAmAWAFA3QAGA8g/ANQgOAggjAOQglAPgagXQgxAkg4gXQg2gXAOgqQgoAIgZAQQgKAHgwAmQgoAghDAOQhHAQgNgeQgLgZABgMQACgMAPgIQAUgLBlgjQBagmAdgVQAOgKgEgDQgyAdg7AcQh1A5gngCQgugDgUggQgSgfAagSQAVgOABgFg");
	this.shape_8.setTransform(556.8456,96.8419);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("Aj5GMIgBpWIBniAIAAg2IEkgDIAAA2IABABIACgHACSlMIBiBoIiSAbIAFgMIgHASIAAGiACSlMIgrB3");
	this.shape_9.setTransform(526.2172,74.7471);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(458.4,33.3,135,92.9);


(lib.DrChildncOUTLINEai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MoreThan-worker.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AG7F9QAlh1AAgfQgBgqgCgVQgDgkgIgaQgNgpgTgKQgQgDgBgDQgEgSAFgsQABgEAUgKQAXgMALgoQAeh0gkguQgLgOgSgHQgPgEgBgBQgagohoAgQhkAggSAlQgDAHATANQgJARABAYQAAADAGAgQAEAUgEAPQAAABgJAPQgGAJAFAGQACADAIACQAIACACABQADAEADAPQAEAIAEAOQAEAMANAGQAFADAdADQAVACAGAMQACAEACANQACAKAFAFQgJAHgBABQgMAMgJAXQgFAMgEAPQgJgGgeACQglADgDAAQgVgCgNAFQgTAIgRAZQAEgXAAgOQACgagRgCQgJgCgEAAQgFgBgFACQggAHALgJQAUgRAAgBQABgGgNgOQgPgOgDgEQgHgJgWgTQgSgQgHgQQgLgZgJgIQgGgFghgOIgMgHQACgQgBgHQAAgIgFgHQgEgGgEgCIgDgYQgCgTAJgSQAPggABgFQAFgSgEgTQgFgUgMgFQgJgDgcAMIgDgHQAfgtgngQQABgHgCgHQgIgkgjgdQghgagjgEQgXgDgoAGQgrAGgSAKQhMArgGBtQgCAnAIAlQAGAhAIAJQAgAhAbgaQACAJAFALQgMALgeAeQgYAYgGADQgmAXgJBiQgCAVAGANQAEAIAMAMQAEAsAIAgQAMAtASAaQAVAdAMAqQAEAOAYAlQAUAggBAN");
	this.shape.setTransform(231.2568,74.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(181.6,29.9,99.29999999999998,89.5);


(lib.DrChildncALLai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MoreThan-worker.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AC+kEQAFAEAGAEQAkAYAEAFQANAPAKAaQAJAVACABQAIADAPgUQAOgTANADQAVAGAHAoQAHAlARAAQAGAAATABQARABAFgEQARgOABgCQAGgHAFgOQAVg9gOg5QgMgxgZgLQgggOgaAAQgngBg7AZQgeANgFACQgUALgKAMQgHAJgFAKgAG8EyQAOguAHgaQAPg3AAgWQgBgqgCgVQgDgkgIgaQgNgogTgKQgQgDgBgDQgEgSAFgtQABgEAUgKQAXgMALgoQAeh0gkguQgLgOgSgHQgPgEgBgBQgagohoAgQhkAggSAlQgCAHASANQgJATABAWQAAADAGAgQAEAUgEAPQAAABgJAPQgGAJAFAHQACACAIACQAIACACABQADAEADAPQAEAJAEAOQAEAMANAGQAFADAdADQAVACAGAMQACAEACANQADAKAEAEQgGAEgEAEQgMAMgJAXQgFAMgEAPQgJgGgeACQglADgDAAQgVgCgNAFQgTAIgRAZQAEgXAAgOQACgagRgCQgJgCgEAAQgFgBgFACQggAHALgJQAUgRAAgBQABgGgNgOQgPgNgDgEQgHgJgWgTQgSgQgHgQQgLgagJgIQgGgFghgOQgGgEgGgDQgBAHgCAJQgDANgGAZQgIAkAPAlQAJAWAaAtQA4BzAeAWQgRACgrg6Qgtg7AEgTQACgMgHgKQgOgPgNgRQgEgGgLgvQgKgpgNgDQgDAAgEAAQAAAFgBAGQgFA3gMAHQgOAJhIhWQgTgXgKgVQgKgCgMgCQgtgKgMgSQgHgKgHgOQgCgHgDgHQgBgDgBgDQgMAMgNAAQgPABgTgUQgIgJgGghQgIglACgnQAGhtBMgrQASgKArgGQAogGAXADQAjAEAhAbQAjAcAIAkQACAIgBAGQgBAKgJAFQgKAGgdABQgSAAglAUQgiATgQASQgHAIAXgFQAigGALACQAUAFAGAAQAPABABgJQACgJAOgOQAOgOAIgBQAKgBACAKQAGAHAEAJQABADABADQAEgBAFgCQAWgJAGADQAMAFAFAUQAEATgFASQgBAFgPAgQgJASACATQACAPABAJQABABACABQAJAGABAPQABAKgCANQgSgLgKgGQgYgNgEAPQAAACgGA7QgTgBgIgCQgKgCgCgHQgCgBgBgCQgBgIgCgDQgNgOgIgDQgJgFgPACQgSACgZgEQgKgTgDgQQgBgEgBgEQgGgkgIgSQgEgJgQgLQgUgOgEgEQgIgJAIgMQAKgPgBgKQgCgZAfgMQAJgEArgHQANgDATgUQASgTARAAQAkAAATAIQAaALgFAYQgDAOgJANQgFAHgHAHQAEgDAKgFQALAjgJA5QgHAygOATQgTAaglgJQgqgJgTgGQgQgEgNgHQgKgGgIgIQgIgJgDgEQgGgGgIgCQgIgCgbAYQgIAHgLALQgzAxgCABQgmAXgJBjQgDAeAUAUQABACACABQACAmAKAmQAMAtASAaQAVAdAMAqQAEAOAYAlQAUAggBANAEtABQABAAAAAAQAJAJAXgNQAugYgkAKQgbAHgQALgAhzDXQAhgBA0AAQA7gCApgPQAKgEAWgUQAWgTALgDQAHgBAPABQAQABAHgBQAWgEAPADQAUAFgCAQQAAAJg3ADQANAAAeAGQAJABACABQAFACACAFQACAIgEAGQgEAHgHgDQgHgEgQgBQgTgCgGAFQACABAPACQAOADACADQAJAJgPAGIgGABQABAAAKgBQACATgeAQQgSALgNABQgKAAgZgGQgNgCgVAAQgOgBgcALQhgAmg8AAQgYgBgHgBQgLAAgFAGQgJAPgCAEQgEAHgDgUQgEgfBEhZQACgDADgEQAIgKgSACQgaADgHgIQgDgDADgPQACgNgHgCQgFgBgMAPQgMAPgEgFQgJgJAFgMQAIgSgBgIQgDgVgNgZQgOgbgPgKQgQgLgLgUQgMgYgHgNQgRgjgIgSQgQgfgRgRQgNgNgaAAQgZABgSANQgqAegFBRQgBAYACAZQAXAYAFAYQAJAsAZAhQAMAPAwAxQASARAlAnQAiAhAdALQARAHAIgIQADgEAJgXQAEgKAHgbQAHgYAFgNQAFgNAHgDQAFgDAPAAQAIgBAKAAgADcFTQgDgKAAgLQABgJADgVQAEgVANgZQANgZAEgVQACgIgFgeQgEgZAIgNQAIgMAIgMQAEgEAEASQADAPACAeQACAbAFARQAEAPASAjQAMAWgHAGQgpAeg6AgQgkAUgqAVQgoAUgOAMQgcAWgEAdQADgEAKgGQABgBAAAAQAHgFACgFAG8EyQgKgNgCgSQgCgkgIgzQgJg1gHgUQgDgJgIARQgIARgGAdQgQBOAVAlQgPABhNAqQhBAkgIgSQgBgDAAgDAl1jXQgHgYAIgKQAKgLAHAFQAHAGgGAJQgJAQgKAJgAhai3QABAVgIgJIAAgEQABgKAGACgAizhnQgCgGADgIQAHAAABAEQACAEgGAEQgDADgCgBgAiJlGQgBABgCABABGHEQgRAXAKASQAGgEAHgPQAIgRAFgFQgRAdAFAfQAAACABgCQAFgDAIgMQAEgHAIgNQgIAXgBAKQgBACADABQACABABgCQAIgMAXgUQAGgHAPgHQAQgGAGgGQAFgEAJgTQAJgSAHgEQAOgJBAgLQBAgMALgHQAGgEAqgRQAdgMAFgOQADgJADgIAC0C3QgDAAgDAA");
	this.shape.setTransform(231.2623,82.1667);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(181.6,29.9,99.29999999999998,104.6);


(lib.covwhiteeps = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// co-v-white.eps
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(-0.0175,0.0157,0.2696,0.2696);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(3.7442,-14.7583,0.2695,0.2695);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(63.7618,21.4304,0.2696,0.2696);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(48.7404,21.5584,0.2696,0.2696);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(34.5952,24.6786,0.2696,0.2696);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(21.1171,21.5584,0.2696,0.2696);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(10.3346,21.4304,0.2696,0.2696);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-5.7919,20.0893,0.2696,0.2696);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-23.2393,21.5584,0.2696,0.2696);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-33.8331,21.4304,0.2696,0.2696);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-46.5564,21.5584,0.2696,0.2696);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-61.9416,20.2376,0.2696,0.2696);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69.5,-33.8,139,67.69999999999999);


(lib.BUTTONbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnmC7Qg1AAgmgmQglglAAg1IAAh1QAAg1AlglQAmgmA1AAIPNAAQA1AAAmAmQAlAlAAA1IAAB1QAAA1glAlQgmAmg1AAg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-18.6,123,37.3);


(lib.HousingOUTLINE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.HousingncOUTLINEai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-55.5,7.3,1,1,0,0,0,100.4,190.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.HousingOUTLINE, new cjs.Rectangle(-99.6,-32.7,88.3,80.2), null);


(lib.HousingALL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.HousingncALLai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-55.35,-0.05,1,1,0,0,0,100.4,190.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.HousingALL, new cjs.Rectangle(-99.4,-40.1,88.2,80.30000000000001), null);


(lib.GradHatOUTLINE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.GradHatncOUTLINEai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-59.4,1.15,1,1,0,0,0,410.4,188);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.GradHatOUTLINE, new cjs.Rectangle(-112.5,-37.3,106.3,76.6), null);


(lib.GradHatALL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.GradHatncALLai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-59,1.15,1,1,0,0,0,410.4,188);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.GradHatALL, new cjs.Rectangle(-112.1,-37.3,106.3,76.6), null);


(lib.FreshFoodOUTLINE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.FreshFood2ncOUTLINEai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(56.95,3.9,1,1,0,0,0,525.9,79.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.FreshFoodOUTLINE, new cjs.Rectangle(-10.5,-42.5,135,92.9), null);


(lib.FreshFoodALL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4
	this.instance = new lib.FreshFood2ncALLai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(56.95,-0.9,1,1,0,0,0,525.9,79.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.FreshFoodALL, new cjs.Rectangle(-10.5,-47.3,135,92.9), null);


(lib.DrChildOUTLINE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.DrChildncOUTLINEai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(59.6,0,1,1,0,0,0,231.1,74.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.DrChildOUTLINE, new cjs.Rectangle(10.1,-44.7,99.30000000000001,89.5), null);


(lib.DrChildALL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.DrChildncALLai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(59.6,7.05,1,1,0,0,0,231.1,82.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.DrChildALL, new cjs.Rectangle(10.1,-45.3,99.30000000000001,104.69999999999999), null);


(lib.BUTTON = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("AgaA1IAAgQIAHAAIADgBIAAgFIAAgVIgagpQgDgFgEAAIgEAAIAAgQIA2AAIAAAQIgEAAQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAACABADIAMAUIAMgWQADgFgGAAIgGAAIAAgQIAsAAIAAAQIgFAAQgEAAgEAFIgZAoIAAAWQAAAFAEABIAHAAIAAAQg");
	this.shape.setTransform(31.525,7.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_1.setTransform(21.625,7.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAAKAIQALAHAAARQAAASgKAGQgKAIgXAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgEgEQgDgEgIAAIgHAAg");
	this.shape_2.setTransform(12.35,7.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAALAIQAKAHAAARQAAASgKAGQgLAIgWAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgDgEQgEgEgIAAIgHAAg");
	this.shape_3.setTransform(2.6,7.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_4.setTransform(-7.975,7.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaABQgZgBgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAJQAFAGAKABQALgBAFgGQAFgJAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_5.setTransform(-22.575,7.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF8300").s().p("AgbA1IAAgQIAHAAQAEgBAAgFIAAhDIgCAAIgKABQgCABgBAFIgCAIIgPAAIAAgfIBhAAIAAAfIgPAAIgBgIQgBgEgEgCIgKgBIgCAAIAABDQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAAAAAAAQABAAAAAAQABABAAAAIAHAAIAAAQg");
	this.shape_6.setTransform(-33.15,7.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF8300").s().p("AASA1IgSg2IgSA2IgaAAIgZhTQgCgGgEAAIgFAAIAAgQIAzAAIAAAQIgEAAIgEABIABAEIANArIANgrQACgFgFAAIgFAAIAAgQIAwAAIAAAQIgFAAQgEAAACAFIAOAsIANgsQABgFgEAAIgGAAIAAgQIAoAAIAAAQIgFAAIgEABIgCAFIgaBTg");
	this.shape_7.setTransform(38.15,-6.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaAAQgZAAgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAIQAFAIAKAAQALAAAFgIQAFgIAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_8.setTransform(24.525,-6.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF8300").s().p("AAHA1IAAgQIAFAAQAEgBAAgFIAAgYIgfAAIAAAYQAAAFAEABIAFAAIAAAQIg0AAIAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgGAAIAAgQIA0AAIAAAQIgFAAQgEAAAAAFIAAAYIAfAAIAAgYQAAgFgEAAIgFAAIAAgQIA0AAIAAAQIgGAAQgEAAAAAFIAAA+QAAAFAEABIAGAAIAAAQg");
	this.shape_9.setTransform(13.075,-6.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF8300").s().p("AAXA1IgxhEIAAAuQAAAFAEABIAHAAIAAAQIgpAAIAAgQIAHAAQAEgBAAgFIAAg+QAAgFgEAAIgHAAIAAgQIArAAIAnA3IAAgiQAAgFgDAAIgHAAIAAgQIApAAIAAAQIgHAAQgEAAAAAFIAABUg");
	this.shape_10.setTransform(-1.625,-6.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF8300").s().p("AAcA1QgRAAgCgcQgCgJgCgDQgDgFgGABIgFAAIAAAWQAAAFADABIAGAAIAAAQIg0AAIAAgQIAFAAQAFgBAAgFIAAg+QAAgFgFAAIgFAAIAAgQIA8AAQAnAAAAAdQgBAVgWADQALAEAFAGQAEAHABALQAAAIAGAAIACAAIAAAQgAgJgEIAGAAQAIAAAFgEQADgDAAgKQAAgHgDgEQgEgEgHAAIgIAAg");
	this.shape_11.setTransform(-12.4,-6.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_12.setTransform(-23.375,-6.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF8300").s().p("AguA1IAAgQIAGAAQAEgBAAgFIAAg+QAAgFgEAAIgGAAIAAgQIBcAAIAAAeIgQAAIgDgIQgCgEgCgBIgJgBIgRAAIAAAcIAIAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAIABgGIAAgDIAPAAIAAAlIgPAAIAAgEQAAgIgFABIgIAAIAAAdIASAAQAHAAACgBQACgBADgFIACgHIAQAAIAAAeg");
	this.shape_13.setTransform(-33.925,-6.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_14.setTransform(-43.125,-6.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.instance = new lib.BUTTONbkgd();
	this.instance.parent = this;
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_3
	this.instance_1 = new lib.Buttonshad();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-69,-27,0.5544,0.5544);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-69,-27,143.6,59.3), null);


// stage content:
(lib.CO_MoreThan_160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_221 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(221).call(this.frame_221).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(222));

	// RULE
	this.instance = new lib.RULE();
	this.instance.parent = this;
	this.instance.setTransform(80.1,453.1,1.0111,1,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(222));

	// LOGO
	this.instance_1 = new lib.covwhiteeps("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(346.9,672.5,1,1,0,0,0,266.9,125.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(222));

	// BUTTON
	this.instance_2 = new lib.BUTTON();
	this.instance_2.parent = this;
	this.instance_2.setTransform(81.2,454);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(222));

	// HEAD-end
	this.instance_3 = new lib.HEADend();
	this.instance_3.parent = this;
	this.instance_3.setTransform(80,212,1,1,0,0,0,0,-15);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(211).to({_off:false},0).to({alpha:1},10).wait(1));

	// LINE-R
	this.instance_4 = new lib.LINER();
	this.instance_4.parent = this;
	this.instance_4.setTransform(129,206.5,0.0067,1);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(14).to({_off:false},0).to({regX:7.8,scaleX:0.11,scaleY:1.0239,skewX:12.4058,x:144.6},3).wait(16).to({regX:8.2,scaleX:0.1096,x:-9.55},12,cjs.Ease.quintIn).wait(1).to({regX:8.5,scaleX:0.2586,x:3.95},11).wait(28).to({regX:8.8,scaleX:0.1371,x:-111.8},14,cjs.Ease.quintIn).wait(19).to({regX:10.7,scaleX:0.0141,x:145.15,y:208},0).to({regX:12.1,scaleX:0.0622,x:151.75},6).wait(12).to({regX:11.7,scaleX:0.0515,x:-4.4},12,cjs.Ease.quintIn).to({_off:true},1).wait(2).to({_off:false,x:-0.4,y:163},0).to({regX:12.3,scaleX:0.1376,x:13.55},3).wait(37).to({x:-125.3},14,cjs.Ease.quintIn).to({_off:true},12).wait(5));

	// LINE-L
	this.instance_5 = new lib.LINEL();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-17.5,211,0.1102,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({scaleX:0.2068,x:17},6).wait(27).to({x:-138},12,cjs.Ease.quintIn).to({_off:true},7).wait(14).to({_off:false,regX:3.6,scaleX:0.0277,x:131.5,y:208},0).to({regX:3,scaleX:0.1191,x:145.35},3).wait(16).to({regX:3.6,scaleX:0.0706,x:6.6},14,cjs.Ease.quintIn).to({regX:3.1,scaleX:0.096,x:1.75},6).wait(31).to({regX:2.9,scaleX:0.0527,x:7.95},0).to({regX:2.6,scaleX:0.0565,x:-146.85},12,cjs.Ease.quintIn).to({_off:true},1).wait(73));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AlhbWMAAAgnDILDAAMAAAAnDg");
	var mask_graphics_1 = new cjs.Graphics().p("AmRbWMAAAgnDIMjAAMAAAAnDg");
	var mask_graphics_2 = new cjs.Graphics().p("AnAbWMAAAgnDIOBAAMAAAAnDg");
	var mask_graphics_3 = new cjs.Graphics().p("AnwbWMAAAgnDIPhAAMAAAAnDg");
	var mask_graphics_4 = new cjs.Graphics().p("AogbWMAAAgnDIRBAAMAAAAnDg");
	var mask_graphics_5 = new cjs.Graphics().p("ApQbWMAAAgnDIShAAMAAAAnDg");
	var mask_graphics_6 = new cjs.Graphics().p("Ap/bWMAAAgnDIT/AAMAAAAnDg");
	var mask_graphics_7 = new cjs.Graphics().p("AqvbWMAAAgnDIVfAAMAAAAnDg");
	var mask_graphics_8 = new cjs.Graphics().p("ArfbWMAAAgnDIW/AAMAAAAnDg");
	var mask_graphics_9 = new cjs.Graphics().p("AsPbWMAAAgnDIYfAAMAAAAnDg");
	var mask_graphics_10 = new cjs.Graphics().p("As+bWMAAAgnDIZ9AAMAAAAnDg");
	var mask_graphics_11 = new cjs.Graphics().p("AtubWMAAAgnDIbdAAMAAAAnDg");
	var mask_graphics_12 = new cjs.Graphics().p("AuebWMAAAgnDIc9AAMAAAAnDg");
	var mask_graphics_13 = new cjs.Graphics().p("AvObWMAAAgnDIedAAMAAAAnDg");
	var mask_graphics_14 = new cjs.Graphics().p("Av9bWMAAAgnDIf7AAMAAAAnDg");
	var mask_graphics_15 = new cjs.Graphics().p("AwtbWMAAAgnDMAhbAAAMAAAAnDg");
	var mask_graphics_16 = new cjs.Graphics().p("AxdbWMAAAgnDMAi7AAAMAAAAnDg");
	var mask_graphics_17 = new cjs.Graphics().p("AyNbWMAAAgnDMAkbAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-34.6441,y:175}).wait(1).to({graphics:mask_graphics_1,x:-29.858,y:174.9999}).wait(1).to({graphics:mask_graphics_2,x:-25.0719,y:174.9999}).wait(1).to({graphics:mask_graphics_3,x:-20.2858,y:174.9998}).wait(1).to({graphics:mask_graphics_4,x:-15.4997,y:174.9998}).wait(1).to({graphics:mask_graphics_5,x:-10.7137,y:174.9997}).wait(1).to({graphics:mask_graphics_6,x:-5.9276,y:174.9997}).wait(1).to({graphics:mask_graphics_7,x:-1.1415,y:174.9996}).wait(1).to({graphics:mask_graphics_8,x:3.6446,y:174.9996}).wait(1).to({graphics:mask_graphics_9,x:8.4307,y:174.9995}).wait(1).to({graphics:mask_graphics_10,x:13.2168,y:174.9994}).wait(1).to({graphics:mask_graphics_11,x:18.0029,y:174.9994}).wait(1).to({graphics:mask_graphics_12,x:22.789,y:174.9993}).wait(1).to({graphics:mask_graphics_13,x:27.5751,y:174.9993}).wait(1).to({graphics:mask_graphics_14,x:32.3612,y:174.9992}).wait(1).to({graphics:mask_graphics_15,x:37.1472,y:174.9992}).wait(1).to({graphics:mask_graphics_16,x:41.9333,y:174.9991}).wait(1).to({graphics:mask_graphics_17,x:46.7194,y:174.974}).wait(15).to({graphics:null,x:0,y:0}).wait(190));

	// DrChild-OUTLINE
	this.instance_6 = new lib.DrChildOUTLINE();
	this.instance_6.parent = this;
	this.instance_6.setTransform(23.45,168.4,1,1,0,0,0,0,0.4);

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(17).to({alpha:0},15).to({_off:true},15).wait(175));

	// DrChild-ALL
	this.instance_7 = new lib.DrChildALL();
	this.instance_7.parent = this;
	this.instance_7.setTransform(23.45,175,1,1,0,0,0,0,7);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(17).to({_off:false},0).to({alpha:1},15).wait(1).to({x:-132},12,cjs.Ease.quintIn).to({_off:true},1).wait(176));

	// HEAD1
	this.instance_8 = new lib.HEAD1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(80.5,256);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(17).to({_off:false},0).to({alpha:1},8).wait(14).to({x:-78},12,cjs.Ease.quintIn).to({_off:true},1).wait(170));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_52 = new cjs.Graphics().p("AlhTiMAAAgnDILDAAMAAAAnDg");
	var mask_1_graphics_53 = new cjs.Graphics().p("AmRTiMAAAgnDIMjAAMAAAAnDg");
	var mask_1_graphics_54 = new cjs.Graphics().p("AnATiMAAAgnDIOBAAMAAAAnDg");
	var mask_1_graphics_55 = new cjs.Graphics().p("AnwTiMAAAgnDIPhAAMAAAAnDg");
	var mask_1_graphics_56 = new cjs.Graphics().p("AogTiMAAAgnDIRBAAMAAAAnDg");
	var mask_1_graphics_57 = new cjs.Graphics().p("ApQTiMAAAgnDIShAAMAAAAnDg");
	var mask_1_graphics_58 = new cjs.Graphics().p("Ap/TiMAAAgnDIT/AAMAAAAnDg");
	var mask_1_graphics_59 = new cjs.Graphics().p("AqvTiMAAAgnDIVfAAMAAAAnDg");
	var mask_1_graphics_60 = new cjs.Graphics().p("ArfTiMAAAgnDIW/AAMAAAAnDg");
	var mask_1_graphics_61 = new cjs.Graphics().p("AsPTiMAAAgnDIYfAAMAAAAnDg");
	var mask_1_graphics_62 = new cjs.Graphics().p("As+TiMAAAgnDIZ9AAMAAAAnDg");
	var mask_1_graphics_63 = new cjs.Graphics().p("AtuTiMAAAgnDIbdAAMAAAAnDg");
	var mask_1_graphics_64 = new cjs.Graphics().p("AueTiMAAAgnDIc9AAMAAAAnDg");
	var mask_1_graphics_65 = new cjs.Graphics().p("AvOTiMAAAgnDIedAAMAAAAnDg");
	var mask_1_graphics_66 = new cjs.Graphics().p("Av9TiMAAAgnDIf7AAMAAAAnDg");
	var mask_1_graphics_67 = new cjs.Graphics().p("AwtTiMAAAgnDMAhbAAAMAAAAnDg");
	var mask_1_graphics_68 = new cjs.Graphics().p("AxdTiMAAAgnDMAi7AAAMAAAAnDg");
	var mask_1_graphics_69 = new cjs.Graphics().p("AyNTiMAAAgnDMAkbAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(52).to({graphics:mask_1_graphics_52,x:-34.6441,y:125}).wait(1).to({graphics:mask_1_graphics_53,x:-29.858,y:124.9999}).wait(1).to({graphics:mask_1_graphics_54,x:-25.0719,y:124.9999}).wait(1).to({graphics:mask_1_graphics_55,x:-20.2858,y:124.9998}).wait(1).to({graphics:mask_1_graphics_56,x:-15.4997,y:124.9998}).wait(1).to({graphics:mask_1_graphics_57,x:-10.7137,y:124.9997}).wait(1).to({graphics:mask_1_graphics_58,x:-5.9276,y:124.9997}).wait(1).to({graphics:mask_1_graphics_59,x:-1.1415,y:124.9996}).wait(1).to({graphics:mask_1_graphics_60,x:3.6446,y:124.9996}).wait(1).to({graphics:mask_1_graphics_61,x:8.4307,y:124.9995}).wait(1).to({graphics:mask_1_graphics_62,x:13.2168,y:124.9994}).wait(1).to({graphics:mask_1_graphics_63,x:18.0029,y:124.9994}).wait(1).to({graphics:mask_1_graphics_64,x:22.789,y:124.9993}).wait(1).to({graphics:mask_1_graphics_65,x:27.5751,y:124.9993}).wait(1).to({graphics:mask_1_graphics_66,x:32.3612,y:124.9992}).wait(1).to({graphics:mask_1_graphics_67,x:37.1472,y:124.9992}).wait(1).to({graphics:mask_1_graphics_68,x:41.9333,y:124.9991}).wait(1).to({graphics:mask_1_graphics_69,x:46.7194,y:124.95}).wait(15).to({graphics:null,x:0,y:0}).wait(138));

	// Housing-OUTLINE
	this.instance_9 = new lib.HousingOUTLINE();
	this.instance_9.parent = this;
	this.instance_9.setTransform(140,175.7);
	this.instance_9._off = true;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(52).to({_off:false},0).wait(17).to({alpha:0},15).to({_off:true},1).wait(137));

	// Housing-ALL
	this.instance_10 = new lib.HousingALL();
	this.instance_10.parent = this;
	this.instance_10.setTransform(140,183.05);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(69).to({_off:false},0).to({alpha:1},15).wait(1).to({x:8},14,cjs.Ease.quintIn).to({_off:true},1).wait(122));

	// HEAD2
	this.instance_11 = new lib.HEAD2();
	this.instance_11.parent = this;
	this.instance_11.setTransform(80.5,266);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(69).to({_off:false},0).to({alpha:1},8).wait(15).to({x:-80},14,cjs.Ease.quintIn).to({_off:true},1).wait(115));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_103 = new cjs.Graphics().p("AlhbWMAAAgnDILDAAMAAAAnDg");
	var mask_2_graphics_104 = new cjs.Graphics().p("AmRbWMAAAgnDIMjAAMAAAAnDg");
	var mask_2_graphics_105 = new cjs.Graphics().p("AnAbWMAAAgnDIOBAAMAAAAnDg");
	var mask_2_graphics_106 = new cjs.Graphics().p("AnwbWMAAAgnDIPhAAMAAAAnDg");
	var mask_2_graphics_107 = new cjs.Graphics().p("AogbWMAAAgnDIRBAAMAAAAnDg");
	var mask_2_graphics_108 = new cjs.Graphics().p("ApQbWMAAAgnDIShAAMAAAAnDg");
	var mask_2_graphics_109 = new cjs.Graphics().p("Ap/bWMAAAgnDIT/AAMAAAAnDg");
	var mask_2_graphics_110 = new cjs.Graphics().p("AqvbWMAAAgnDIVfAAMAAAAnDg");
	var mask_2_graphics_111 = new cjs.Graphics().p("ArfbWMAAAgnDIW/AAMAAAAnDg");
	var mask_2_graphics_112 = new cjs.Graphics().p("AsPbWMAAAgnDIYfAAMAAAAnDg");
	var mask_2_graphics_113 = new cjs.Graphics().p("As+bWMAAAgnDIZ9AAMAAAAnDg");
	var mask_2_graphics_114 = new cjs.Graphics().p("AtubWMAAAgnDIbdAAMAAAAnDg");
	var mask_2_graphics_115 = new cjs.Graphics().p("AuebWMAAAgnDIc9AAMAAAAnDg");
	var mask_2_graphics_116 = new cjs.Graphics().p("AvObWMAAAgnDIedAAMAAAAnDg");
	var mask_2_graphics_117 = new cjs.Graphics().p("Av9bWMAAAgnDIf7AAMAAAAnDg");
	var mask_2_graphics_118 = new cjs.Graphics().p("AwtbWMAAAgnDMAhbAAAMAAAAnDg");
	var mask_2_graphics_119 = new cjs.Graphics().p("AxdbWMAAAgnDMAi7AAAMAAAAnDg");
	var mask_2_graphics_120 = new cjs.Graphics().p("AyNbWMAAAgnDMAkbAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(103).to({graphics:mask_2_graphics_103,x:-34.6441,y:175}).wait(1).to({graphics:mask_2_graphics_104,x:-29.858,y:174.9999}).wait(1).to({graphics:mask_2_graphics_105,x:-25.0719,y:174.9999}).wait(1).to({graphics:mask_2_graphics_106,x:-20.2858,y:174.9998}).wait(1).to({graphics:mask_2_graphics_107,x:-15.4997,y:174.9998}).wait(1).to({graphics:mask_2_graphics_108,x:-10.7137,y:174.9997}).wait(1).to({graphics:mask_2_graphics_109,x:-5.9276,y:174.9997}).wait(1).to({graphics:mask_2_graphics_110,x:-1.1415,y:174.9996}).wait(1).to({graphics:mask_2_graphics_111,x:3.6446,y:174.9996}).wait(1).to({graphics:mask_2_graphics_112,x:8.4307,y:174.9995}).wait(1).to({graphics:mask_2_graphics_113,x:13.2168,y:174.9994}).wait(1).to({graphics:mask_2_graphics_114,x:18.0029,y:174.9994}).wait(1).to({graphics:mask_2_graphics_115,x:22.789,y:174.9993}).wait(1).to({graphics:mask_2_graphics_116,x:27.5751,y:174.9993}).wait(1).to({graphics:mask_2_graphics_117,x:32.3612,y:174.9992}).wait(1).to({graphics:mask_2_graphics_118,x:37.1472,y:174.9992}).wait(1).to({graphics:mask_2_graphics_119,x:41.9333,y:174.9991}).wait(1).to({graphics:mask_2_graphics_120,x:46.7194,y:174.974}).wait(15).to({graphics:null,x:0,y:0}).wait(87));

	// FreshFood-OUTLINE
	this.instance_12 = new lib.FreshFoodOUTLINE();
	this.instance_12.parent = this;
	this.instance_12.setTransform(24,168.5,1,1,0,0,0,0,-0.8);
	this.instance_12._off = true;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(103).to({_off:false},0).wait(17).to({alpha:0},15).to({_off:true},1).wait(86));

	// FreshFood-ALL
	this.instance_13 = new lib.FreshFoodALL();
	this.instance_13.parent = this;
	this.instance_13.setTransform(24,174.05);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(120).to({_off:false},0).to({alpha:1},15).wait(1).to({x:-130},12,cjs.Ease.quintIn).to({_off:true},1).wait(73));

	// HEAD3
	this.instance_14 = new lib.HEAD3();
	this.instance_14.parent = this;
	this.instance_14.setTransform(80.5,256);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(120).to({_off:false},0).to({alpha:1},8).wait(14).to({x:-80},12,cjs.Ease.quintIn).to({_off:true},1).wait(67));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_151 = new cjs.Graphics().p("AlhTiMAAAgnDILDAAMAAAAnDg");
	var mask_3_graphics_152 = new cjs.Graphics().p("AmRTiMAAAgnDIMjAAMAAAAnDg");
	var mask_3_graphics_153 = new cjs.Graphics().p("AnATiMAAAgnDIOBAAMAAAAnDg");
	var mask_3_graphics_154 = new cjs.Graphics().p("AnwTiMAAAgnDIPhAAMAAAAnDg");
	var mask_3_graphics_155 = new cjs.Graphics().p("AogTiMAAAgnDIRBAAMAAAAnDg");
	var mask_3_graphics_156 = new cjs.Graphics().p("ApQTiMAAAgnDIShAAMAAAAnDg");
	var mask_3_graphics_157 = new cjs.Graphics().p("Ap/TiMAAAgnDIT/AAMAAAAnDg");
	var mask_3_graphics_158 = new cjs.Graphics().p("AqvTiMAAAgnDIVfAAMAAAAnDg");
	var mask_3_graphics_159 = new cjs.Graphics().p("ArfTiMAAAgnDIW/AAMAAAAnDg");
	var mask_3_graphics_160 = new cjs.Graphics().p("AsPTiMAAAgnDIYfAAMAAAAnDg");
	var mask_3_graphics_161 = new cjs.Graphics().p("As+TiMAAAgnDIZ9AAMAAAAnDg");
	var mask_3_graphics_162 = new cjs.Graphics().p("AtuTiMAAAgnDIbdAAMAAAAnDg");
	var mask_3_graphics_163 = new cjs.Graphics().p("AueTiMAAAgnDIc9AAMAAAAnDg");
	var mask_3_graphics_164 = new cjs.Graphics().p("AvOTiMAAAgnDIedAAMAAAAnDg");
	var mask_3_graphics_165 = new cjs.Graphics().p("Av9TiMAAAgnDIf7AAMAAAAnDg");
	var mask_3_graphics_166 = new cjs.Graphics().p("AwtTiMAAAgnDMAhbAAAMAAAAnDg");
	var mask_3_graphics_167 = new cjs.Graphics().p("AxdTiMAAAgnDMAi7AAAMAAAAnDg");
	var mask_3_graphics_168 = new cjs.Graphics().p("AyNTiMAAAgnDMAkbAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:null,x:0,y:0}).wait(151).to({graphics:mask_3_graphics_151,x:-34.6441,y:125}).wait(1).to({graphics:mask_3_graphics_152,x:-29.858,y:124.9999}).wait(1).to({graphics:mask_3_graphics_153,x:-25.0719,y:124.9999}).wait(1).to({graphics:mask_3_graphics_154,x:-20.2858,y:124.9998}).wait(1).to({graphics:mask_3_graphics_155,x:-15.4997,y:124.9998}).wait(1).to({graphics:mask_3_graphics_156,x:-10.7137,y:124.9997}).wait(1).to({graphics:mask_3_graphics_157,x:-5.9276,y:124.9997}).wait(1).to({graphics:mask_3_graphics_158,x:-1.1415,y:124.9996}).wait(1).to({graphics:mask_3_graphics_159,x:3.6446,y:124.9996}).wait(1).to({graphics:mask_3_graphics_160,x:8.4307,y:124.9995}).wait(1).to({graphics:mask_3_graphics_161,x:13.2168,y:124.9994}).wait(1).to({graphics:mask_3_graphics_162,x:18.0029,y:124.9994}).wait(1).to({graphics:mask_3_graphics_163,x:22.789,y:124.9993}).wait(1).to({graphics:mask_3_graphics_164,x:27.5751,y:124.9993}).wait(1).to({graphics:mask_3_graphics_165,x:32.3612,y:124.9992}).wait(1).to({graphics:mask_3_graphics_166,x:37.1472,y:124.9992}).wait(1).to({graphics:mask_3_graphics_167,x:41.9333,y:124.9991}).wait(1).to({graphics:mask_3_graphics_168,x:46.7194,y:124.95}).wait(15).to({graphics:null,x:0,y:0}).wait(39));

	// GradHat-OUTLINE
	this.instance_15 = new lib.GradHatOUTLINE();
	this.instance_15.parent = this;
	this.instance_15.setTransform(142,179.75,1,1,0,0,0,0,0.7);
	this.instance_15._off = true;

	var maskedShapeInstanceList = [this.instance_15];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(151).to({_off:false},0).wait(17).to({alpha:0},15).to({_off:true},1).wait(38));

	// GradHat-ALL
	this.instance_16 = new lib.GradHatALL();
	this.instance_16.parent = this;
	this.instance_16.setTransform(142,179.75,1,1,0,0,0,0,0.7);
	this.instance_16.alpha = 0;
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(168).to({_off:false},0).to({alpha:1},15).wait(8).to({x:2},14,cjs.Ease.quintIn).to({_off:true},12).wait(5));

	// HEAD4
	this.instance_17 = new lib.HEAD4();
	this.instance_17.parent = this;
	this.instance_17.setTransform(80.5,264);
	this.instance_17.alpha = 0;
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(168).to({_off:false},0).to({alpha:1},8).wait(22).to({x:-81},14,cjs.Ease.quintIn).to({_off:true},5).wait(5));

	// bkgd
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_1.setTransform(80.0172,299.9971,0.5333,2.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(222));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-88.8,299.5,319.8,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 160,
	height: 600,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_MoreThan_160x600_atlas_.png?1570127347290", id:"CO_MoreThan_160x600_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;