(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_Child_300x250_atlas_", frames: [[0,0,259,107]]}
];


// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_Child_300x250_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.RULE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,2,1).p("A3LAAMAuXAAA");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.RULE, new cjs.Rectangle(-149.3,-1,298.70000000000005,2), null);


(lib.MotherChildoutlineai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-outline.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AXdJgIjTAAQhNgDgngfQghgZgUg5QgOg/gJgaQgLgcgYgmQgVghgjgVQgEgDhFgiIgWgJIgJgIQgbgQgYgEIglAAQgMAFgKAIQAZgWAGgjQAFgggNghQgYhBhEgsQgogbgtgJQAIgPAEgQQAEgPACgbQACgfACgLQAEgWASg+IAGgYQAUABALgJQAVgRgJgyQgPhKg7g+QgugwgEgEQgegdgbgNQgXgLgwgFQgkgEgkADQhAAFguAaQgHgZgfgOQgagLgdACQgfACgfAOQgfANgYAVQgXAUgJAXQgMAcAMAYQgaAFgPAQQgWAaAKAoQAKAnAeARQgVAYgHAbQgHAhATAWQATAWAdgEQAZgEAXgUQATgRAHAaQAFAWACAtQABAHADASQADAQAGAIIADAKQAHASADAGQAIAPAKAEQASAIAEgYQAEgSgEgQQgCgKgGgUQABgTgJgaQgEgLgPgfIgFgNIgBgDQANgQAWgMIgBABQgHAsAOArQAIAXANARQAFAGAKAKQAIAJgBAKQgCA6gOAsQgeBjhMAfQgOAHgfAOQgeANgPAIQgzAbgdAXQhQA/gUBcQgKAuAKBAQAIAyAQAqIAHAOI18AAAC1jgIgBAAIAAAAg");
	this.shape.setTransform(150.125,61.5596);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.2,302.3,123.60000000000001);


(lib.MotherChildallai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-all.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AOQDQQALAEALAGQBFAiAEADQAjAVAVAhQAYAmALAcQAJAaAOA/QAUA5AhAZQAnAfBNADIDTAAAI6mkQAAAAAAAAQAvALAWALQAoASALAeQAGAQgEAXQgBAFgCALQgCAJgEAOQgSA+gEAWQgCALgCAfQgCAbgEAPQgEAQgHAPQAqAIAqAcQBEAsAYBBQANAhgFAgQgEAYgNASQgEAEgDAEQgDACgDADQADgCACgCQACgBABgBQgBABgBAAQAAABgBAAQgCACgCACQABgBABgBQACgBADgDIAAAAQADgDACgEAEqpLQAtgaBBgFQAkgDAkAEQAwAFAXALQAbANAeAdQAEAEAuAwQA7A+APBKQAJAygVARQgMAKgTgBQgMgBgNgGQgjgMgbgeQgSgUgLgtQgCgFgBgGQgLgjgRgTQgXgagpgRQgUgJgKgDQgYgHgFALQgDAIAJAOQACADANAPQAYAbAjAQQAZALAuALAElk3QAJALAIADQAPAFAPgNQAHgHAOgUQAKgRATgLQAMgHAagMQAXgKAIgFQARgMACgOQADgTgTgGQgQgGgSAGQgVAIgUAeQgUAkgLARQgTAdgkALQgEACgEABQgzAQgaAPQAEgWAKgQQAPgWAUAFQAKADANAPQACAEADACgAC0j7QgKgVgFgMQgNgdgGgVQgNg4AxhKQAdgqARgUQAcgiAbgSQAHgFAIgEAC1j8QgRg/AFgsQAEgfAUgcQAKgPAfgjQAjglAJgNQAXgigCgbQgBgEAAgEQgGgXgcgOQgbgNggACQgfACgfAOQgfANgYAVQgXAUgJAXQgMAcAMAYQgaAFgPAQQgWAaAKAoQAKAnAeARQgVAYgHAbQgHAhATAWQATAWAdgEQAZgEAXgUQATgRAHAaQAFAWACAtQADAXACAHQADANAFAHQACAEABAFQAHASADAGQAIAPAKAEQASAIAEgYQAEgSgEgQQgCgNgFgQQABgTgJgYQgEgKgQgjQgCgFgCgFQgCgDgBgCQgSAVgEAaQgEAfAPA0QADADACABQANAJANgLQANgKABgOQABgCAAgDQgEgMgFgPQgQgtgDgKQgCgIgCgIQgBgDgBgDQgBAAAAABADYkYQgCACgCAAQgTAMgMAOAhhJCQgDgGgDgIQgQgqgIgyQgKhAAKguQAUhcBQg/QAdgXAzgbQAPgIAegNQAfgOAOgHQBMgfAehiQAOgtACg6QABgKgIgJQgKgKgFgGQgNgRgIgXQgOgrAHgsQAAAAABgBAGZBEQgRgJgVgQQgIgGgHgGQgYgTgRgVQgigtAOgYQAKgTAQAUQAKAMAJAVQALAaAEAuQAAACABABQAFA2AEAVQAJArATAeQALARANANQAMAMABAAQAEAEAFACQADABADgBQAKgCAIgNQACgDAJgTQAQgpAOgUQAWggAegIQAagIAqANQA4ARANABQARACAIgFQAHgEgBgGQAAgBgDgLQgCgGACgFQADgGAGgBQAJAAANAMQANALAIAOQAJAQAAAPQAAAPgOAJQgHAFgDAFQgDAFABAJQAAAMAGAYQADARgGAaQgHAkgNAZQAMgFAPgJQASgLAMgGQgHgJgDgLQgGgTAHgSQAOgoAzAAQAdAAAfALQApAjAVAlQAeAzgKAxQgeA7hOAIQgXAChygJQg4gBgFgBQgjgHgHgeQgBAGgKgCQgMgDgCAAQgOgEgYgNQgYgNgNgEQgTgFgKgDQgRgGgIgKQgUgXAkgMQgSgRgSgUQgTgXgOgWQgggzgDgxQgDgdAIgeQACgGADgHQAMgiAZgcQAYgcAigSQAhgSAlgEQAfgDAeAFQgKAVgOATQgWAcgfAaQgJAHgXARQgVAPgKAJQgaAYgogOQgLgDgOgIgAH8E1QAAAAABgBQAPgFAogEQAYgCANABQAVABANALQAHAHAFAKQADAHAAAHQAEgBAEgBQAMgDAUgCQAWgCAJgCQAIgBAKgEQgFAIgFAHQguBDhYgnQgugVgpgmgAMsC2QABAAACgBIAlAAQAYAEAbAQQAEAEAFADAMiC6QAEgDAGgBAMaDAIgBACQAAAAAAgBQABAAAAgBAMaDBQgBABAAAAAMbDAQAAAAgBAAQAAABAAAAQAIgGAKgFAMcEmQAIgEAFgCQAZgLAVAHQAKAEAHAGQAKAJgEAJQgGASgcgIQgXgGgPgMQgGgEgEgGgAKKFVQAAADgBACQgBAFgEAGQgEAIgFAAQgFAAABgGQAAgFAEgEQAFgFAKgEgAhhJCIALAAQAmAAAUAUQASARgLAPQgLAOgcgVQgXgSgOgbgA3cJCIV7AA");
	this.shape.setTransform(150.125,64.3508);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.2,302.3,129.2);


(lib.HEAD3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAJQgDgEAAgFQAAgFADgEQAEgDAFAAQAFAAAEADQAEAEAAAFQAAAFgEAEQgEAEgFAAQgFAAgEgEg");
	this.shape.setTransform(97.7,39.525);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_1.setTransform(88.025,33.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggBlIAAgLIAWAAQADAAABgGIAAikQgBgGgDAAIgWAAIAAgLIAJAAQATAAAMgDIAAC4QAAAGADAAIAVAAIAAALg");
	this.shape_2.setTransform(77.05,30.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgrBBQgBAOgEAUIgLAAQACgRAAghIAAiDQAAgGgDAAIgVAAIAAgLIAHAAQAUAAANgDIAABaQAQgkAoAAQAeAAATAUQASAVAAAhQAAAjgSAVQgTAUgeABQgpAAgRgmgAgagTQgPARAAAbIAAADQAAAcAPASQAPARAXAAQAZgBAPgQQAPgRAAgdIAAgDQAAgcgPgRQgPgQgZAAQgXAAgPARg");
	this.shape_3.setTransform(64.625,30.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhnQAAgMgHAAIgSAAIAAgMIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhWQAAgGAEgDQADgEAFAAQAFAAAEAEQADADAAAGQAAAFgDAEQgEADgFAAQgMAAAAgMg");
	this.shape_4.setTransform(52.975,30.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhMBNQAAgZAkgJQgbgDAAgVQAAgTAXgGQgVgOAAgcQAAgXARgPQARgOAZAAQAdAAARATQAEgbAUAAQAGAAAEADQADAEAAAFQAAAMgKAAQgKAAgBgKQgIAHgDAOQAHALAAAOQAAAYgRAOQgQANgaAAQgQAAgMgEQgTADAAAOQAAAPAXAAIA3AAQAuAAAAAhQAAAXgWALQgUALgjAAQhFAAAAgggAgzA4QgMAIAAALQAAAYA4AAQBAAAAAggQAAgWgjABIgtAAQgSADgKAHgAgmhPQgMAMAAATIAAAAQAAAUALALQAMALAUgBQAUABAMgLQAMgLAAgSIAAgCQAAgTgMgMQgMgLgTAAQgUAAgMALg");
	this.shape_5.setTransform(42.175,35.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhnQAAgMgHAAIgSAAIAAgMIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhWQAAgGAEgDQADgEAFAAQAFAAAEAEQADADAAAGQAAAFgDAEQgEADgFAAQgMAAAAgMg");
	this.shape_6.setTransform(31.075,30.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgfBlIAAgLIAVAAQAEAAgBgGIAAikQABgGgEAAIgVAAIAAgLIAIAAQASAAANgDIAAC4QAAAGADAAIAWAAIAAALg");
	this.shape_7.setTransform(24,30.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_8.setTransform(13.075,33.275);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglBmIAAgLIASAAQAEAAAAgGIAAhzIgWAAIAAgMIAWAAIAAgVQAAgmAhAAQAMAAAIAEIAAAMQgHgFgLAAQgLAAgFAGQgEAHAAAPIAAAUIAfAAIAAAMIgfAAIAABzQAAAGACAAIAXAAIAAALg");
	this.shape_9.setTransform(-4.125,30.275);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhnQAAgMgHAAIgSAAIAAgMIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhWQAAgGAEgDQADgEAFAAQAFAAAEAEQADADAAAGQAAAFgDAEQgEADgFAAQgMAAAAgMg");
	this.shape_10.setTransform(-11.825,30.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag3AcIAAhUQAAgGgEAAIgVAAIAAgLIAoAAIAABkQAAAjAhAAQAVAAANgTQAOgSAAgcIAAg1QAAgGgEAAIgVAAIAAgLIAoAAIAAB+QAAAHAEAAIAVAAIAAALIgIAAQgTAAgNACIAAgmQgPAngkAAQgtAAAAgug");
	this.shape_11.setTransform(-29.975,33.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgyA3QgUgWAAghQAAghAUgVQAUgVAfAAQAfAAAUAVQATAVAAAhQAAAhgUAVQgUAWgfAAQgfAAgTgVgAgoguQgPARAAAdIAAABQAAAdAPARQAPARAZAAQAaAAAPgRQAPgSAAgcIAAgBQAAgdgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_12.setTransform(-45.775,33.275);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhDBcQgJgGAAgLQAAgGAEgFQAEgEAGAAQAKAAAAAJQAAAJgJAEQAEAGALAAQANAAAJgKQAJgLAMgcIAAgCIg5h2QgDgGgDAAIgPAAIAAgLIA4AAIAAALIgPAAQgHAAACAGIAxBmIAshmQADgGgHAAIgRAAIAAgLIA3AAIAAALIgPAAQgFAAgCAGIg3B9QgMAfgIAKQgMAOgTAAQgNAAgIgHg");
	this.shape_13.setTransform(-61.375,35.925);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgyA3QgUgWAAghQAAghAUgVQAUgVAfAAQAfAAAUAVQATAVAAAhQAAAhgUAVQgUAWgfAAQgfAAgTgVgAgoguQgPARAAAdIAAABQAAAdAPARQAPARAZAAQAaAAAPgRQAPgSAAgcIAAgBQAAgdgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_14.setTransform(-83.475,33.275);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgGBTQgJgJAAgTIAAhjIgXAAIAAgKIASgCQAHAAABgHIACgaIAKAAIAAAhIAkAAIAAAMIgkAAIAABjQAAAZAVAAQAHgBALgDIAAALQgKAEgKAAQgSgBgHgHg");
	this.shape_15.setTransform(-95.35,31.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgGBSQgJgIAAgTIAAhjIgXAAIAAgKIASgBQAHgBABgHIACgaIAKAAIAAAhIAkAAIAAAMIgkAAIAABjQAAAZAVAAQAHAAALgEIAAAMQgKADgKAAQgSAAgHgJg");
	this.shape_16.setTransform(119.75,1.65);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgzA+IAAgkIAMAAIAAAdQAPAJAYAAQAmAAAAgdQAAgOgMgHQgIgEgUgFQgXgFgLgFQgPgKAAgTQAAgSAOgLQAOgMAXAAQAcAAAUANIAAAkIgMAAIAAgcQgPgKgVAAQgRAAgKAIQgKAHAAANQAAAPANAGQAHAEAVAEQAXAFALAHQAOAKAAASQAAAUgNALQgPAMgYAAQgdAAgWgOg");
	this.shape_17.setTransform(109.525,3.225);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgyA3QgUgWAAghQAAghAUgVQAUgVAfAAQAfAAAUAVQATAVAAAhQAAAhgUAVQgUAWgfAAQgfAAgTgVgAgoguQgPARAAAdIAAABQAAAdAPARQAPARAZAAQAaAAAPgRQAPgSAAgcIAAgBQAAgdgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_18.setTransform(95.625,3.225);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgwA3QgTgVAAgiQAAggAUgWQAVgVAfAAQAcAAARAOQASAOAAAXQAAAHgEAFQgEAEgGAAQgMAAAAgLQAAgMANAAQgIghgqAAQgZAAgQASQgQARAAAcIAAACQAAAcAPARQAQASAZAAQArAAAKgpIALADQgFAXgQANQgRAOgaAAQggAAgUgVg");
	this.shape_19.setTransform(80.875,3.225);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgyA3QgUgWAAghQAAghAUgVQAUgVAfAAQAfAAAUAVQATAVAAAhQAAAhgUAVQgUAWgfAAQgfAAgTgVgAgoguQgPARAAAdIAAABQAAAdAPARQAPARAZAAQAaAAAPgRQAPgSAAgcIAAgBQAAgdgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_20.setTransform(59.325,3.225);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AASBKIAAgLIAUAAQAEAAAAgGIAAhQQAAgmghAAQgWAAgOAUQgOAUAAAhIAAAtQAAAGAEAAIAVAAIAAALIhBAAIAAgLIAVAAQAFAAAAgGIAAhtQAAgGgFAAIgVAAIAAgMIAJAAQASAAANgCIAAApQAQgqAkAAQAuAAAAAxIAABRQAAAGAEAAIAUAAIAAALg");
	this.shape_21.setTransform(43.25,3.05);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGBSQgJgIAAgTIAAhjIgXAAIAAgKIASgBQAHgBAAgHIADgaIAKAAIAAAhIAkAAIAAAMIgkAAIAABjQAAAZAVAAQAHAAALgEIAAAMQgKADgKAAQgSAAgHgJg");
	this.shape_22.setTransform(24.25,1.65);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_23.setTransform(13.075,3.225);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_24.setTransform(-8.675,3.225);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgGgDAAIgWAAIAAgMIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAALQAAARgOAAQgEAAgEgCQgDgEAAgDQAAgLALAAQgDgMgOAAQgTAAgJAUQgJARAAAeIAAA0QAAAGADAAIAWAAIAAALg");
	this.shape_25.setTransform(-21.825,3.05);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgyA3QgUgWAAghQAAghAUgVQAUgVAfAAQAfAAAUAVQATAVAAAhQAAAhgUAVQgUAWgfAAQgfAAgTgVgAgoguQgPARAAAdIAAABQAAAdAPARQAPARAZAAQAaAAAPgRQAPgSAAgcIAAgBQAAgdgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_26.setTransform(-35.325,3.225);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AA6BKIAAgLIATAAQAEAAAAgGIAAhLQAAgXgIgJQgIgLgSAAQgTAAgKAPQgKARAAAcIAAA6QAAAGADAAIAXAAIAAALIhAAAIAAgLIAUAAQAEAAAAgGIAAhQQAAgmghAAQgUAAgKAQQgLAQAAAcIAAA6QAAAGAEAAIAVAAIAAALIhBAAIAAgLIAVAAQAEAAAAgGIAAhtQAAgGgEAAIgVAAIAAgMIAIAAQATAAANgCIAAAeQANgfAeAAQAkAAAGAkQANgkAgAAQAuAAAAA2IAABMQAAAGAEAAIAVAAIAAALg");
	this.shape_27.setTransform(-55.325,3.05);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("Ag+BSQgUgVABgiQgBgiAUgVQASgUAfAAQAoAAAPAlIAAhHQAAgGgDAAIgVAAIAAgLIAJAAQASAAANgDIAAC4QAAAGAEAAIAVAAIAAALIgmAAQgCgNAAgVQgQAmgoAAQgfgBgSgUgAgzgUQgPARAAAcIAAADQAAAdAPARQAQARAYAAQAYAAAPgRQAOgRAAgdIAAgDQAAgbgOgRQgPgRgYAAQgYAAgQAQg");
	this.shape_28.setTransform(-82.6,0.55);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AATBKIAAgLIATAAQAEAAAAgGIAAhQQAAgmghAAQgWAAgNAUQgOAUgBAhIAAAtQABAGADAAIAVAAIAAALIhAAAIAAgLIAVAAQADAAAAgGIAAhtQAAgGgDAAIgVAAIAAgMIAIAAQASAAANgCIAAApQAQgqAlAAQAtAAAAAxIAABRQAAAGADAAIAWAAIAAALg");
	this.shape_29.setTransform(-99.8,3.05);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_30.setTransform(-115.375,3.225);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_31.setTransform(64.875,-26.825);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgGgDAAIgWAAIAAgMIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAALQAAARgOAAQgEAAgEgCQgDgDAAgFQAAgKALAAQgDgLgOAAQgTgBgJAUQgJARAAAdIAAA1QAAAGADAAIAWAAIAAALg");
	this.shape_32.setTransform(51.725,-27);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_33.setTransform(38.825,-26.825);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgwA3QgTgVAAgiQAAggAUgWQAVgVAfAAQAcAAARAOQASAOAAAXQAAAHgEAFQgEAEgGAAQgMAAAAgLQAAgMANAAQgIghgqAAQgZAAgQASQgQARAAAcIAAACQAAAcAPARQAQASAZAAQArAAAKgpIALADQgFAXgQANQgRAOgaAAQggAAgUgVg");
	this.shape_34.setTransform(23.825,-26.825);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AASBlIAAgLIAUAAQAEAAAAgGIAAhTQgBgjggAAQgWAAgNAUQgPATAAAiIAAAtQAAAGAEAAIAVAAIAAALIhAAAIAAgLIAUAAQAFAAAAgGIAAikQAAgGgFAAIgUAAIAAgLIAIAAQASAAANgDIAABeQARgoAjAAQAuAAgBAuIAABUQABAGADAAIAVAAIAAALg");
	this.shape_35.setTransform(1.75,-29.675);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgGBSQgJgIAAgUIAAhiIgXAAIAAgKIASgBQAHgBABgHIACgaIAKAAIAAAhIAkAAIAAAMIgkAAIAABiQAAAaAWAAQAFAAAMgEIAAAMQgKACgKAAQgSABgHgJg");
	this.shape_36.setTransform(-10.65,-28.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AggBlIAAgLIAWAAQADAAABgGIAAikQgBgGgDAAIgWAAIAAgLIAJAAQASAAANgDIAAC4QAAAGADAAIAVAAIAAALg");
	this.shape_37.setTransform(-18.25,-29.675);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_38.setTransform(-28.925,-26.825);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_39.setTransform(-44.275,-26.825);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAeBjIAAgLIAXAAQADABAAgHIAAhOIhvAAIAABOQAAAHAEgBIAWAAIAAALIhCAAIAAgLIAWAAQADABAAgHIAAikQAAgGgDAAIgWAAIAAgLIBCAAIAAALIgWAAQgEAAAAAGIAABLIBvAAIAAhLQAAgGgDAAIgXAAIAAgLIBCAAIAAALIgWAAQgDAAAAAGIAACkQAAAHADgBIAWAAIAAALg");
	this.shape_40.setTransform(-61.7,-29.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-148.8,-51,297.8,102.1), null);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAJQgDgEAAgFQAAgFADgEQAEgDAFAAQAFAAAEADQAEAEAAAFQAAAFgEAEQgEAEgFAAQgFAAgEgEg");
	this.shape.setTransform(75.2,9.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgGgDAAIgWAAIAAgMIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAALQAAARgOAAQgEAAgEgCQgDgEAAgDQAAgLALAAQgDgMgOAAQgTAAgJAUQgJARAAAeIAAA0QAAAGADAAIAWAAIAAALg");
	this.shape_1.setTransform(66.675,3.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_2.setTransform(53.025,3.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhoQAAgMgHABIgSAAIAAgMIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhWQAAgGAEgDQADgEAFAAQAFAAAEAEQADADAAAGQAAAFgDAEQgEADgFAAQgMAAAAgMg");
	this.shape_3.setTransform(41.525,0.45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AATBlIAAgLIATAAQADAAAAgGIAAhTQABgjgiAAQgVAAgOAUQgOATABAiIAAAtQAAAGADAAIAVAAIAAALIhBAAIAAgLIAWAAQADAAAAgGIAAikQAAgGgDAAIgWAAIAAgLIAIAAQATAAAOgDIAABeQAPgoAlAAQAsAAABAuIAABUQgBAGAEAAIAWAAIAAALg");
	this.shape_4.setTransform(29.25,0.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgGBSQgJgIAAgTIAAhjIgXAAIAAgKIASgBQAHgBABgHIACgaIAKAAIAAAhIAkAAIAAAMIgkAAIAABjQAAAZAWAAQAFAAAMgEIAAAMQgKADgKAAQgSAAgHgJg");
	this.shape_5.setTransform(16.35,1.65);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgfBlIAAgLIAVAAQAEAAgBgGIAAikQABgGgEAAIgVAAIAAgLIAIAAQASAAANgDIAAC4QAAAGADAAIAWAAIAAALg");
	this.shape_6.setTransform(8.25,0.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_7.setTransform(-2.925,3.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_8.setTransform(-18.775,3.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AASBlIAAgLIAUAAQADAAABgGIAAhTQAAgjgiAAQgVAAgOAUQgNATAAAiIAAAtQAAAGADAAIAVAAIAAALIhBAAIAAgLIAVAAQAFAAAAgGIAAikQAAgGgFAAIgVAAIAAgLIAIAAQATAAAOgDIAABeQAQgoAjAAQAuAAgBAuIAABUQAAAGAEAAIAVAAIAAALg");
	this.shape_9.setTransform(-34.95,0.375);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgzA+IAAgkIAMAAIAAAdQAPAJAYAAQAmAAAAgdQAAgOgMgHQgIgEgUgFQgXgFgLgFQgPgKAAgTQAAgSAOgLQAOgMAXAAQAcAAAUANIAAAkIgMAAIAAgcQgPgKgVAAQgRAAgKAIQgKAHAAANQAAAPANAGQAHAEAVAEQAXAFALAHQAOAKAAASQAAAUgNALQgPAMgYAAQgdAAgWgOg");
	this.shape_10.setTransform(-56.775,3.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhoQAAgMgHABIgSAAIAAgMIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhWQAAgGAEgDQADgEAFAAQAFAAAEAEQADADAAAGQAAAFgDAEQgEADgFAAQgMAAAAgMg");
	this.shape_11.setTransform(-67.025,0.45);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag/BSQgSgVgBgiQABgiASgUQAUgVAeAAQAoAAAQAlIAAhGQgBgHgDAAIgVAAIAAgLIAIAAQATAAANgDIAAC4QAAAGAEAAIAUAAIAAALIgmAAQgBgNAAgVQgRAlgnAAQgfAAgTgUgAgzgUQgPARABAcIAAADQgBAeAPAQQAQARAZAAQAXgBAOgQQAPgSABgcIAAgDQgBgbgPgRQgOgRgXAAQgZAAgQAQg");
	this.shape_12.setTransform(57.75,-29.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AggBlIAAgLIAWAAQADAAAAgGIAAikQAAgGgDAAIgWAAIAAgLIAJAAQASAAANgDIAAC4QAAAGADAAIAVAAIAAALg");
	this.shape_13.setTransform(44.85,-29.675);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhoQAAgMgHABIgSAAIAAgMIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhWQAAgGAEgDQADgEAFAAQAFAAAEAEQADAEAAAFQAAAFgDAEQgEADgFAAQgMAAAAgMg");
	this.shape_14.setTransform(37.225,-29.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AATBlIAAgLIATAAQAEAAgBgGIAAhTQAAgjggAAQgVAAgOAUQgOATgBAiIAAAtQABAGADAAIAVAAIAAALIhAAAIAAgLIAUAAQAEAAAAgGIAAikQAAgGgEAAIgUAAIAAgLIAIAAQASAAANgDIAABeQAQgoAlAAQAsAAABAuIAABUQAAAGADAAIAWAAIAAALg");
	this.shape_15.setTransform(24.95,-29.675);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgwA3QgTgVAAgiQAAggAUgWQAVgVAfAAQAcAAARAOQASAOAAAXQAAAHgEAFQgEAEgGAAQgMAAAAgLQAAgMANAAQgIghgqAAQgZAAgQASQgQARAAAcIAAACQAAAcAPARQAQASAZAAQArAAAKgpIALADQgFAXgQANQgRAOgaAAQggAAgUgVg");
	this.shape_16.setTransform(9.175,-26.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgGgDAAIgWAAIAAgMIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAALQAAARgOAAQgEAAgEgCQgDgDAAgFQAAgKALAAQgDgLgOAAQgTgBgJAUQgJARAAAdIAAA1QAAAGADAAIAWAAIAAALg");
	this.shape_17.setTransform(-11.375,-27);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag3AcIAAhUQAAgGgEAAIgVAAIAAgLIAoAAIAABkQAAAjAhAAQAVAAANgTQAOgSAAgcIAAg1QAAgGgEAAIgVAAIAAgLIAoAAIAAB+QAAAHAEAAIAVAAIAAALIgIAAQgTAAgNACIAAgmQgPAngkAAQgtAAAAgug");
	this.shape_18.setTransform(-25.875,-26.675);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgyA3QgUgWAAghQAAghAUgVQAUgVAfAAQAfAAAUAVQATAVAAAhQAAAhgUAVQgUAWgfAAQgfAAgTgVgAgoguQgPARAAAdIAAABQAAAdAPARQAPARAZAAQAaAAAPgRQAPgSAAgcIAAgBQAAgdgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_19.setTransform(-42.175,-26.825);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhDBcQgJgGAAgLQAAgGAEgFQAEgEAGAAQAKAAAAAJQAAAJgJAEQAEAGALAAQANAAAJgKQAJgLAMgcIAAgCIg5h2QgDgGgDAAIgPAAIAAgLIA4AAIAAALIgPAAQgHAAACAGIAxBmIAshmQADgGgHAAIgRAAIAAgLIA3AAIAAALIgPAAQgFAAgCAGIg3B9QgMAfgIAKQgMAOgTAAQgNAAgIgHg");
	this.shape_20.setTransform(-58.275,-24.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-80.5,-51,161,72.1), null);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgHgDABIgWAAIAAgMIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAAMQAAAQgOABQgEAAgEgDQgDgEAAgDQAAgKALgBQgDgMgOAAQgTAAgJATQgJASAAAeIAAA0QAAAGADAAIAWAAIAAALg");
	this.shape.setTransform(52.075,33.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_1.setTransform(38.425,33.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhnQAAgMgHAAIgSAAIAAgMIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhWQAAgGAEgDQADgEAFAAQAFAAAEAEQADADAAAGQAAAFgDAEQgEADgFAAQgMAAAAgMg");
	this.shape_2.setTransform(26.925,30.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AASBlIAAgLIAUAAQADAAABgGIAAhTQAAgjgiAAQgUAAgPAUQgNATAAAiIAAAtQgBAGAEAAIAVAAIAAALIhBAAIAAgLIAWAAQADAAAAgGIAAikQAAgGgDAAIgWAAIAAgLIAIAAQATAAAOgDIAABeQAQgoAkAAQAtAAAAAuIAABUQAAAGADAAIAVAAIAAALg");
	this.shape_3.setTransform(14.65,30.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgGBTQgJgJAAgTIAAhjIgXAAIAAgKIASgCQAHAAAAgHIADgaIAKAAIAAAhIAkAAIAAAMIgkAAIAABjQAAAZAVAAQAHgBALgDIAAALQgKAEgKAAQgSgBgHgHg");
	this.shape_4.setTransform(1.75,31.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggBlIAAgLIAWAAQADAAAAgGIAAikQAAgGgDAAIgWAAIAAgLIAJAAQASAAANgDIAAC4QAAAGADAAIAWAAIAAALg");
	this.shape_5.setTransform(-6.35,30.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_6.setTransform(-17.525,33.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_7.setTransform(-33.375,33.275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AASBlIAAgLIAUAAQAEAAAAgGIAAhTQgBgjggAAQgWAAgNAUQgPATAAAiIAAAtQAAAGAEAAIAVAAIAAALIhAAAIAAgLIAUAAQAFAAAAgGIAAikQAAgGgFAAIgUAAIAAgLIAIAAQASAAANgDIAABeQARgoAjAAQAuAAgBAuIAABUQABAGADAAIAVAAIAAALg");
	this.shape_8.setTransform(-49.55,30.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_9.setTransform(41.825,3.225);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgGgDAAIgWAAIAAgMIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAALQAAARgOAAQgEAAgEgCQgDgEAAgDQAAgLALAAQgDgMgOAAQgTAAgJAUQgJARAAAeIAAA0QAAAGADAAIAWAAIAAALg");
	this.shape_10.setTransform(28.175,3.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_11.setTransform(14.775,3.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag3AcIAAhUQAAgGgEAAIgVAAIAAgLIAoAAIAABkQAAAjAhAAQAVAAANgTQAOgSAAgcIAAg1QAAgGgEAAIgVAAIAAgLIAoAAIAAB+QAAAHAEAAIAVAAIAAALIgIAAQgTAAgNACIAAgmQgPAngkAAQgtAAAAgug");
	this.shape_12.setTransform(-8.825,3.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgyA3QgUgWAAghQAAghAUgVQAUgVAfAAQAfAAAUAVQATAVAAAhQAAAhgUAVQgUAWgfAAQgfAAgTgVgAgoguQgPARAAAdIAAABQAAAdAPARQAPARAZAAQAaAAAPgRQAPgSAAgcIAAgBQAAgdgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_13.setTransform(-25.125,3.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhDBcQgJgGAAgLQAAgGAEgFQAEgEAGAAQAKAAAAAJQAAAJgJAEQAEAGALAAQANAAAJgKQAJgLAMgcIAAgCIg5h2QgDgGgDAAIgPAAIAAgLIA4AAIAAALIgPAAQgHAAACAGIAxBmIAshmQADgGgHAAIgRAAIAAgLIA3AAIAAALIgPAAQgFAAgCAGIg3B9QgMAfgIAKQgMAOgTAAQgNAAgIgHg");
	this.shape_14.setTransform(-41.225,5.875);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AATBKIAAgLIATAAQAEAAAAgGIAAhQQAAgmghAAQgWAAgNAUQgOAUAAAhIAAAtQAAAGADAAIAVAAIAAALIhAAAIAAgLIAVAAQADAAAAgGIAAhtQAAgGgDAAIgVAAIAAgMIAIAAQASAAAOgCIAAApQAPgqAlAAQAtAAAAAxIAABRQAAAGADAAIAWAAIAAALg");
	this.shape_15.setTransform(31.15,-27);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_16.setTransform(14.825,-26.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AATBlIAAgLIATAAQADAAAAgGIAAhTQABgjgiAAQgVAAgOAUQgOATABAiIAAAtQAAAGADAAIAVAAIAAALIhBAAIAAgLIAWAAQADAAAAgGIAAikQAAgGgDAAIgWAAIAAgLIAIAAQATAAAOgDIAABeQAPgoAlAAQAsAAABAuIAABUQgBAGAEAAIAWAAIAAALg");
	this.shape_17.setTransform(-1.35,-29.675);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AA2BkIg2iqIg2CqIgNAAIgyi2QgDgGgEAAIgTAAIAAgLIBAAAIAAALIgUAAQgFAAABAFIAsCeIA0igQABAAAAgBQAAgBAAAAQgBgBAAAAQAAAAgBAAIgZAAIAAgLIBHAAIAAALIgaAAQgBAAAAAAQgBAAAAABQgBAAAAABQAAABAAAAIA1CgIAsieQABgFgFAAIgWAAIAAgLIBAAAIAAALIgTAAQgFAAgCAGIgzC2g");
	this.shape_18.setTransform(-24.8,-29.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-80.5,-51,161,102.1), null);


(lib.covwhiteeps = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// co-v-white.eps
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(-0.029,0.0085,0.2192,0.2192);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(3.0555,-12.024,0.2192,0.2192);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(51.8592,17.404,0.2192,0.2192);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(39.6438,17.5082,0.2192,0.2192);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(28.1409,20.0455,0.2192,0.2192);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(17.1805,17.5082,0.2192,0.2192);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(8.4122,17.404,0.2192,0.2192);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(-4.7019,16.3135,0.2192,0.2192);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(-18.8901,17.5082,0.2192,0.2192);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(-27.505,17.404,0.2192,0.2192);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(-37.8516,17.5082,0.2192,0.2192);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(-50.3629,16.434,0.2192,0.2192);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.5,-27.5,113,55.1);


(lib.BUTTONbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnmC7Qg1AAgmgmQglglAAg1IAAh1QAAg1AlglQAmgmA1AAIPNAAQA1AAAmAmQAlAlAAA1IAAB1QAAA1glAlQgmAmg1AAg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-18.6,123,37.3);


(lib.BUTTON = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("AgaA1IAAgQIAHAAIADgBIAAgFIAAgVIgagpQgDgFgEAAIgEAAIAAgQIA2AAIAAAQIgEAAQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAACABADIAMAUIAMgWQADgFgGAAIgGAAIAAgQIAsAAIAAAQIgFAAQgEAAgEAFIgZAoIAAAWQAAAFAEABIAHAAIAAAQg");
	this.shape.setTransform(31.525,7.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_1.setTransform(21.625,7.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAAKAIQALAHAAARQAAASgKAGQgKAIgXAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgEgEQgDgEgIAAIgHAAg");
	this.shape_2.setTransform(12.35,7.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAALAIQAKAHAAARQAAASgKAGQgLAIgWAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgDgEQgEgEgIAAIgHAAg");
	this.shape_3.setTransform(2.6,7.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_4.setTransform(-7.975,7.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaABQgZgBgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAJQAFAGAKABQALgBAFgGQAFgJAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_5.setTransform(-22.575,7.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF8300").s().p("AgbA1IAAgQIAHAAQAEgBAAgFIAAhDIgCAAIgKABQgCABgBAFIgCAIIgPAAIAAgfIBhAAIAAAfIgPAAIgBgIQgBgEgEgCIgKgBIgCAAIAABDQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAAAAAAAQABAAAAAAQABABAAAAIAHAAIAAAQg");
	this.shape_6.setTransform(-33.15,7.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF8300").s().p("AASA1IgSg2IgSA2IgaAAIgZhTQgCgGgEAAIgFAAIAAgQIAzAAIAAAQIgEAAIgEABIABAEIANArIANgrQACgFgFAAIgFAAIAAgQIAwAAIAAAQIgFAAQgEAAACAFIAOAsIANgsQABgFgEAAIgGAAIAAgQIAoAAIAAAQIgFAAIgEABIgCAFIgaBTg");
	this.shape_7.setTransform(38.15,-6.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaAAQgZAAgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAIQAFAIAKAAQALAAAFgIQAFgIAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_8.setTransform(24.525,-6.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF8300").s().p("AAHA1IAAgQIAFAAQAEgBAAgFIAAgYIgfAAIAAAYQAAAFAEABIAFAAIAAAQIg0AAIAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgGAAIAAgQIA0AAIAAAQIgFAAQgEAAAAAFIAAAYIAfAAIAAgYQAAgFgEAAIgFAAIAAgQIA0AAIAAAQIgGAAQgEAAAAAFIAAA+QAAAFAEABIAGAAIAAAQg");
	this.shape_9.setTransform(13.075,-6.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF8300").s().p("AAXA1IgxhEIAAAuQAAAFAEABIAHAAIAAAQIgpAAIAAgQIAHAAQAEgBAAgFIAAg+QAAgFgEAAIgHAAIAAgQIArAAIAnA3IAAgiQAAgFgDAAIgHAAIAAgQIApAAIAAAQIgHAAQgEAAAAAFIAABUg");
	this.shape_10.setTransform(-1.625,-6.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF8300").s().p("AAcA1QgRAAgCgcQgCgJgCgDQgDgFgGABIgFAAIAAAWQAAAFADABIAGAAIAAAQIg0AAIAAgQIAFAAQAFgBAAgFIAAg+QAAgFgFAAIgFAAIAAgQIA8AAQAnAAAAAdQgBAVgWADQALAEAFAGQAEAHABALQAAAIAGAAIACAAIAAAQgAgJgEIAGAAQAIAAAFgEQADgDAAgKQAAgHgDgEQgEgEgHAAIgIAAg");
	this.shape_11.setTransform(-12.4,-6.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_12.setTransform(-23.375,-6.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF8300").s().p("AguA1IAAgQIAGAAQAEgBAAgFIAAg+QAAgFgEAAIgGAAIAAgQIBcAAIAAAeIgQAAIgDgIQgCgEgCgBIgJgBIgRAAIAAAcIAIAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAIABgGIAAgDIAPAAIAAAlIgPAAIAAgEQAAgIgFABIgIAAIAAAdIASAAQAHAAACgBQACgBADgFIACgHIAQAAIAAAeg");
	this.shape_13.setTransform(-33.925,-6.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_14.setTransform(-43.125,-6.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.instance = new lib.BUTTONbkgd();
	this.instance.parent = this;
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_3
	this.instance_1 = new lib.Buttonshad();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-69,-27,0.5544,0.5544);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-69,-27,143.6,59.3), null);


(lib.ARToutline = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.MotherChildoutlineai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0.05,1,1,0,0,0,150.1,61.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ARToutline, new cjs.Rectangle(-151.1,-61.8,302.29999999999995,123.6), null);


(lib.ARTall = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.MotherChildallai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,-0.05,1,1,0,0,0,150.1,64.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ARTall, new cjs.Rectangle(-151.1,-64.6,302.29999999999995,129.2), null);


// stage content:
(lib.CO_Child_300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_187 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(187).call(this.frame_187).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A3WzcMAutAAAMAAAAm5MgutAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(188));

	// RULE
	this.instance = new lib.RULE();
	this.instance.parent = this;
	this.instance.setTransform(447.1,155.7,1.0111,1,0,0,0,0.1,0.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(124).to({_off:false},0).to({x:150.1},12,cjs.Ease.quintIn).wait(52));

	// LOGO
	this.instance_1 = new lib.covwhiteeps("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(348.5,332.5,1,1,0,0,0,266.9,125.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(177).to({_off:false},0).to({alpha:1},10).wait(1));

	// BUTTON
	this.instance_2 = new lib.BUTTON();
	this.instance_2.parent = this;
	this.instance_2.setTransform(226.05,206.95);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(177).to({_off:false},0).to({alpha:1},10).wait(1));

	// ART-all
	this.instance_3 = new lib.ARTall();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150.1,97.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(31).to({_off:false},0).to({alpha:1},15).wait(78).to({x:-151},12,cjs.Ease.quintIn).to({_off:true},1).wait(51));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AgSTiMAAAgnDIAlAAMAAAAnDg");
	var mask_graphics_1 = new cjs.Graphics().p("AhTTiMAAAgnDICnAAMAAAAnDg");
	var mask_graphics_2 = new cjs.Graphics().p("AiTTiMAAAgnDIEnAAMAAAAnDg");
	var mask_graphics_3 = new cjs.Graphics().p("AjUTiMAAAgnDIGpAAMAAAAnDg");
	var mask_graphics_4 = new cjs.Graphics().p("AkUTiMAAAgnDIIpAAMAAAAnDg");
	var mask_graphics_5 = new cjs.Graphics().p("AlUTiMAAAgnDIKpAAMAAAAnDg");
	var mask_graphics_6 = new cjs.Graphics().p("AmVTiMAAAgnDIMrAAMAAAAnDg");
	var mask_graphics_7 = new cjs.Graphics().p("AnVTiMAAAgnDIOrAAMAAAAnDg");
	var mask_graphics_8 = new cjs.Graphics().p("AoVTiMAAAgnDIQrAAMAAAAnDg");
	var mask_graphics_9 = new cjs.Graphics().p("ApWTiMAAAgnDIStAAMAAAAnDg");
	var mask_graphics_10 = new cjs.Graphics().p("AqWTiMAAAgnDIUtAAMAAAAnDg");
	var mask_graphics_11 = new cjs.Graphics().p("ArWTiMAAAgnDIWtAAMAAAAnDg");
	var mask_graphics_12 = new cjs.Graphics().p("Ar9TiMAAAgnDIX7AAMAAAAnDg");
	var mask_graphics_13 = new cjs.Graphics().p("AskTiMAAAgnDIZJAAMAAAAnDg");
	var mask_graphics_14 = new cjs.Graphics().p("AtKTiMAAAgnDIaVAAMAAAAnDg");
	var mask_graphics_15 = new cjs.Graphics().p("AtxTiMAAAgnDIbjAAMAAAAnDg");
	var mask_graphics_16 = new cjs.Graphics().p("AuYTiMAAAgnDIcxAAMAAAAnDg");
	var mask_graphics_17 = new cjs.Graphics().p("Au+TiMAAAgnDId9AAMAAAAnDg");
	var mask_graphics_18 = new cjs.Graphics().p("AvlTiMAAAgnDIfLAAMAAAAnDg");
	var mask_graphics_19 = new cjs.Graphics().p("AwLTiMAAAgnDMAgXAAAMAAAAnDg");
	var mask_graphics_20 = new cjs.Graphics().p("AwyTiMAAAgnDMAhlAAAMAAAAnDg");
	var mask_graphics_21 = new cjs.Graphics().p("AxZTiMAAAgnDMAizAAAMAAAAnDg");
	var mask_graphics_22 = new cjs.Graphics().p("Ax/TiMAAAgnDMAj/AAAMAAAAnDg");
	var mask_graphics_23 = new cjs.Graphics().p("AymTiMAAAgnDMAlNAAAMAAAAnDg");
	var mask_graphics_24 = new cjs.Graphics().p("AzMTiMAAAgnDMAmZAAAMAAAAnDg");
	var mask_graphics_25 = new cjs.Graphics().p("AzzTiMAAAgnDMAnnAAAMAAAAnDg");
	var mask_graphics_26 = new cjs.Graphics().p("A0aTiMAAAgnDMAo1AAAMAAAAnDg");
	var mask_graphics_27 = new cjs.Graphics().p("A1ATiMAAAgnDMAqBAAAMAAAAnDg");
	var mask_graphics_28 = new cjs.Graphics().p("A1nTiMAAAgnDMArPAAAMAAAAnDg");
	var mask_graphics_29 = new cjs.Graphics().p("A2OTiMAAAgnDMAsdAAAMAAAAnDg");
	var mask_graphics_30 = new cjs.Graphics().p("A20TiMAAAgnDMAtpAAAMAAAAnDg");
	var mask_graphics_31 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:1.9003,y:125}).wait(1).to({graphics:mask_graphics_1,x:8.3422,y:125}).wait(1).to({graphics:mask_graphics_2,x:14.784,y:125}).wait(1).to({graphics:mask_graphics_3,x:21.2259,y:125}).wait(1).to({graphics:mask_graphics_4,x:27.6677,y:125}).wait(1).to({graphics:mask_graphics_5,x:34.1096,y:125}).wait(1).to({graphics:mask_graphics_6,x:40.5514,y:125}).wait(1).to({graphics:mask_graphics_7,x:46.9932,y:125}).wait(1).to({graphics:mask_graphics_8,x:53.4351,y:125}).wait(1).to({graphics:mask_graphics_9,x:59.874,y:125}).wait(1).to({graphics:mask_graphics_10,x:66.3128,y:125}).wait(1).to({graphics:mask_graphics_11,x:72.7121,y:125}).wait(1).to({graphics:mask_graphics_12,x:76.5703,y:125}).wait(1).to({graphics:mask_graphics_13,x:80.4284,y:125}).wait(1).to({graphics:mask_graphics_14,x:84.2866,y:125}).wait(1).to({graphics:mask_graphics_15,x:88.1447,y:125}).wait(1).to({graphics:mask_graphics_16,x:92.0028,y:125}).wait(1).to({graphics:mask_graphics_17,x:95.861,y:125}).wait(1).to({graphics:mask_graphics_18,x:99.7191,y:125}).wait(1).to({graphics:mask_graphics_19,x:103.5773,y:125}).wait(1).to({graphics:mask_graphics_20,x:107.4354,y:125}).wait(1).to({graphics:mask_graphics_21,x:111.2936,y:125}).wait(1).to({graphics:mask_graphics_22,x:115.1517,y:125}).wait(1).to({graphics:mask_graphics_23,x:119.0099,y:125}).wait(1).to({graphics:mask_graphics_24,x:122.868,y:125}).wait(1).to({graphics:mask_graphics_25,x:126.7261,y:125}).wait(1).to({graphics:mask_graphics_26,x:130.5843,y:125}).wait(1).to({graphics:mask_graphics_27,x:134.4424,y:125}).wait(1).to({graphics:mask_graphics_28,x:138.3006,y:125}).wait(1).to({graphics:mask_graphics_29,x:142.1587,y:125}).wait(1).to({graphics:mask_graphics_30,x:146.0169,y:125}).wait(1).to({graphics:mask_graphics_31,x:149.975,y:125}).wait(15).to({graphics:null,x:0,y:0}).wait(142));

	// ART-outline
	this.instance_4 = new lib.ARToutline();
	this.instance_4.parent = this;
	this.instance_4.setTransform(150.1,94.8);

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({_off:true},46).wait(142));

	// HEAD1
	this.instance_5 = new lib.HEAD1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(76.8,72.85);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(47).to({_off:false},0).to({alpha:1},8).wait(59).to({x:-60},12,cjs.Ease.quintIn).to({_off:true},1).wait(61));

	// HEAD2
	this.instance_6 = new lib.HEAD2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(196.1,217.45);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(55).to({_off:false},0).to({alpha:1},8).wait(55).to({x:-81},14,cjs.Ease.quintIn).to({_off:true},1).wait(55));

	// HEAD3
	this.instance_7 = new lib.HEAD3();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,66.3,1,1,0,0,0,0,-15);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(141).to({_off:false},0).to({alpha:1},10).wait(37));

	// bkgd
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_1.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(188));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-151.9,124.5,749.9,126);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 250,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_Child_300x250_atlas_.png?1568830928775", id:"CO_Child_300x250_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;