(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_Child_300x600_atlas_", frames: [[0,0,259,107]]}
];


// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_Child_300x600_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.RULE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,2,1).p("A3LAAMAuXAAA");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.RULE, new cjs.Rectangle(-149.3,-1,298.70000000000005,2), null);


(lib.MotherChildoutlineai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-outline.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AXdJgIjTAAQhNgDgngfQghgZgUg5QgOg/gJgaQgLgcgYgmQgVghgjgVQgEgDhFgiIgWgJIgJgIQgbgQgYgEIglAAQgMAFgKAIQAZgWAGgjQAFgggNghQgYhBhEgsQgogbgtgJQAIgPAEgQQAEgPACgbQACgfACgLQAEgWASg+IAGgYQAUABALgJQAVgRgJgyQgPhKg7g+QgugwgEgEQgegdgbgNQgXgLgwgFQgkgEgkADQhAAFguAaQgHgZgfgOQgagLgdACQgfACgfAOQgfANgYAVQgXAUgJAXQgMAcAMAYQgaAFgPAQQgWAaAKAoQAKAnAeARQgVAYgHAbQgHAhATAWQATAWAdgEQAZgEAXgUQATgRAHAaQAFAWACAtQABAHADASQADAQAGAIIADAKQAHASADAGQAIAPAKAEQASAIAEgYQAEgSgEgQQgCgKgGgUQABgTgJgaQgEgLgPgfIgFgNIgBgDQANgQAWgMIgBABQgHAsAOArQAIAXANARQAFAGAKAKQAIAJgBAKQgCA6gOAsQgeBjhMAfQgOAHgfAOQgeANgPAIQgzAbgdAXQhQA/gUBcQgKAuAKBAQAIAyAQAqIAHAOI18AAAC1jgIgBAAIAAAAg");
	this.shape.setTransform(150.125,61.5596);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.2,302.3,123.60000000000001);


(lib.MotherChildMOTHERonlyai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-MOTHERonly.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AO1mkQgKgjgRgTQgXgagpgRQgVgJgKgDQgXgHgFALQgEAIAJAOQADADANAPQAYAbAjAQQAZALAtALgAQtknQgMgBgOgGQgigMgbgeQgSgUgMgtQgBgFgCgGQABAAAAAAQAuALAXALQAnASALAeQAGAQgDAXQgBAFgCALgAKlpLQAugaBAgFQAlgDAkAEQAvAFAXALQAcANAeAdQAEAEAtAwQA8A+AOBKQAKAygVARQgNAKgSgBQgDAJgEAOQgSA+gDAWQgCALgCAfQgCAbgEAPQgKAlgaAiQgVAcggAaQgIAHgXARQgVAPgLAJQgaAYgogOQgZgIgmgcQgIgGgHgGQgYgTgQgVQgigtANgYQAKgTAQAUQALAMAIAVQALAaAFAuQAAACAAABAKgk3QAKALAHADQAQAFAPgNQAHgHANgUQALgRATgLQALgHAagMQAYgKAHgFQASgMACgOQACgTgTgGQgQgGgRAGQgVAIgVAeQgTAkgLARQgUAdgjALQgFACgEABQgyAQgbAPQAFgWAKgQQAOgWAUAFQALADAMAPQADAEACACgAIwj7QgKgVgGgMQgNgdgFgVQgOg4AyhKQAdgqAQgUQAcgiAcgSQAHgFAHgEAIwj8QgRg/AGgsQAEgfATgcQAKgPAggjQAiglAJgNQAYgigDgbQAAgEgBgEQgGgXgbgOQgcgNgfACQggACgfAOQgeANgYAVQgXAUgKAXQgMAcAMAYQgaAFgOAQQgXAaALAoQAKAnAeARQgWAYgGAbQgIAhATAWQATAWAegEQAZgEAXgUQATgRAGAaQAGAWACAtQADAXABAHQADANAGAHQABAEACAFQAHASADAGQAIAPAJAEQASAIAFgYQAEgSgEgQQgDgNgFgQQgEgMgFgPQgPgtgDgKQgDgIgCgIQgBgDgBgCQgTAVgEAaQgEAfAQA0QACADADABQAMAJAOgLQAMgKACgOQAAgCAAgDQABgTgJgYQgDgKgQgjQgDgFgCgFQgBgDgBgDQAAAAAAABAEaJCQgDgGgDgIQgQgqgIgyQgKhAAKguQAUhcBQg/QAegXAygbQAQgIAdgNQAggOANgHQBMgfAfhiQAOgtACg6QAAgKgIgJQgKgKgEgGQgOgRgIgXQgOgrAIgsQAAAAAAgBQgCACgBAAQgTAMgNAOAEaJCIAKAAQAnAAAUAUQASARgMAPQgLAOgbgVQgXgSgOgbgAxhJCIV7AA");
	this.shape.setTransform(-37.827,0.0008);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-151,-64.6,225.6,129.2);


(lib.MotherChildCHILDonlyai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-CHILDonly.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AgfgqQAMAEALAGQBEAhAEADQAjAVAUAhQAZAmAKAcQAKAaAOA/QAUA5AhAZQAnAfBNADIDTAAAn3gYQgggygEgxQgDgkANgkQAMgiAZgdQAZgcAhgSQAigSAlgEQBKgJBHAvQBEAtAYBBQANAhgFAgQgFAegUAUQABgBACAAIAAgBQADgCAEgBAgfgqQAoAiAWAlQAeAzgKAxQgeA7hOAIQgWAChygJQg4gBgFgBQgkgHgHgeQAAAGgLgCQgLgDgDAAQgNgEgYgNQgZgNgNgEQgTgFgJgDQgRgGgIgKQgUgYAjgLQgSgRgRgUQgUgWgNgXQADABADAAQAKgCAIgNQABgDAJgTQARgpAOgUQAWggAdgIQAbgIAqANQA4ARANABQAQACAJgFQAGgEAAgGQAAgBgDgLQgCgGACgFQADgGAGgBQAJAAANAMQAMALAJAOQAJAQAAAPQAAAPgOAJQgIAFgCAFQgDAFAAAJQABAMAGAYQACARgFAZQgHAkgNAYQgFAJgFAHQgvBDhXgnQgugVgqgmQABgBAAAAQAQgFAngEQAZgCAMABQAWABAMALQAIAHAEAKQAEAHgBAHQAEgBAFgBQALgDAVgCQAWgCAIgCQAJgCAKgEQAMgFAOgIQATgLAMgGQAIgFAFgBQAZgLAUAHQALAEAHAGQAKAJgEAJQgGASgcgIQgXgGgPgMQgGgFgEgFQgHgJgDgLQgGgTAGgRQAPgoAzAAQAdAAAeALgAiUg5QAKgIAKgEIAmAAQAYAEAbAQQAEADAEAEAiUg6QABgBABgBQABgBABAAQACgCACgBAiUg6IAAAAQAAAAAAABQgBAAAAABQAAgBABgBQACgCADgDQgCADgDACgAiUg6IgBACAomhHQALARAOANQALAMABAAQAFAEAFABAklBaQABADgBACQgBAFgEAGQgFAIgEAAQgGAAABgGQABgFADgEQAGgGAJgDg");
	this.shape.setTransform(94.3,25.1451);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1.5,1,1).p("AgShKQABAzAFAaQAEAcAbAs");
	this.shape_1.setTransform(37.375,10.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(34.5,-8.7,116.6,67.7);


(lib.MotherChildallai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-all.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AOQDQQALAEALAGQBFAiAEADQAjAVAVAhQAYAmALAcQAJAaAOA/QAUA5AhAZQAnAfBNADIDTAAAI6mkQgLgjgRgTQgXgagpgRQgUgJgKgDQgYgHgFALQgDAIAJAOQACADANAPQAYAbAjAQQAZALAuALgAKxknQgMgBgNgGQgjgMgbgeQgSgUgLgtQgCgFgBgGQAAAAAAAAQAvALAWALQAoASALAeQAGAQgEAXQgBAFgCALgAEqpLQAtgaBBgFQAkgDAkAEQAwAFAXALQAbANAeAdQAEAEAuAwQA7A+APBKQAJAygVARQgMAKgTgBQgCAJgEAOQgSA+gEAWQgCALgCAfQgCAbgEAPQgEAQgHAPQAqAIAqAcQBEAsAYBBQANAhgFAgQgEAYgNASQgEAEgDAEQAAABgBAAQgCACgCACQABgBABgBQACgBADgDIAAAAQAEgDAGgBQABAAACgBIAlAAQAYAEAbAQQAEAEAFADQApAjAVAlQAeAzgKAxQgeA7hOAIQgXAChygJQg4gBgFgBQgjgHgHgeQgBAGgKgCQgMgDgCAAQgOgEgYgNQgYgNgNgEQgTgFgKgDQgRgGgIgKQgUgXAkgMQAAAAABgBQAPgFAogEQAYgCANABQAVABANALQAHAHAFAKQADAHAAAHQAEgBAEgBQAMgDAUgCQAWgCAJgCQAIgBAKgEQgFAIgFAHQguBDhYgnQgugVgpgmQgSgRgSgUQgTgXgOgWQADABADgBQAKgCAIgNQACgDAJgTQAQgpAOgUQAWggAegIQAagIAqANQA4ARANABQARACAIgFQAHgEgBgGQAAgBgDgLQgCgGACgFQADgGAGgBQAJAAANAMQANALAIAOQAJAQAAAPQAAAPgOAJQgHAFgDAFQgDAFABAJQAAAMAGAYQADARgGAaQgHAkgNAZQAMgFAPgJQASgLAMgGQAIgEAFgCQAZgLAVAHQAKAEAHAGQAKAJgEAJQgGASgcgIQgXgGgPgMQgGgEgEgGQgHgJgDgLQgGgTAHgSQAOgoAzAAQAdAAAfALAElk3QAJALAIADQAPAFAPgNQAHgHAOgUQAKgRATgLQAMgHAagMQAXgKAIgFQARgMACgOQADgTgTgGQgQgGgSAGQgVAIgUAeQgUAkgLARQgTAdgkALQgEACgEABQgzAQgaAPQAEgWAKgQQAPgWAUAFQAKADANAPQACAEADACgAC0j7QgKgVgFgMQgNgdgGgVQgNg4AxhKQAdgqARgUQAcgiAbgSQAHgFAIgEAC1j8QgRg/AFgsQAEgfAUgcQAKgPAfgjQAjglAJgNQAXgigCgbQgBgEAAgEQgGgXgcgOQgbgNggACQgfACgfAOQgfANgYAVQgXAUgJAXQgMAcAMAYQgaAFgPAQQgWAaAKAoQAKAnAeARQgVAYgHAbQgHAhATAWQATAWAdgEQAZgEAXgUQATgRAHAaQAFAWACAtQADAXACAHQADANAFAHQACAEABAFQAHASADAGQAIAPAKAEQASAIAEgYQAEgSgEgQQgCgNgFgQQgEgMgFgPQgQgtgDgKQgCgIgCgIQgCgDgBgCQgSAVgEAaQgEAfAPA0QADADACABQANAJANgLQANgKABgOQABgCAAgDQABgTgJgYQgEgKgQgjQgCgFgCgFQgBgDgBgDQgBAAAAABAhhJCQgDgGgDgIQgQgqgIgyQgKhAAKguQAUhcBQg/QAdgXAzgbQAPgIAegNQAfgOAOgHQBMgfAehiQAOgtACg6QABgKgIgJQgKgKgFgGQgNgRgIgXQgOgrAHgsQAAAAABgBQgCACgCAAQgTAMgMAOAGZBEQgRgJgVgQQgIgGgHgGQgYgTgRgVQgigtAOgYQAKgTAQAUQAKAMAJAVQALAaAEAuQAAACABABQAFA2AEAVQAJArATAeQALARANANQAMAMABAAQAEAEAFACQgggzgDgxQgDgdAIgeQACgGADgHQAMgiAZgcQAYgcAigSQAhgSAlgEQAfgDAeAFQgKAVgOATQgWAcgfAaQgJAHgXARQgVAPgKAJQgaAYgogOQgLgDgOgIgAMiC6QADgDACgEAMgC7QgDACgDADQADgCACgCQACgBABgBQgBABgBAAgAMaDAQAAABAAAAQgBABAAAAQAAAAAAgBQABAAAAgBAMbDAQAAAAgBAAIgBACAMaDBQAIgGAKgFAKKFVQAAADgBACQgBAFgEAGQgEAIgFAAQgFAAABgGQAAgFAEgEQAFgFAKgEgAhhJCIALAAQAmAAAUAUQASARgLAPQgLAOgcgVQgXgSgOgbgA3cJCIV7AA");
	this.shape.setTransform(150.125,64.3508);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.2,302.3,129.2);


(lib.HEAD3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAQQgHgGABgKQgBgJAHgHQAGgGAJAAQAJAAAHAGQAGAHABAJQgBAKgGAGQgHAHgJAAQgJAAgGgHg");
	this.shape.setTransform(98.45,-100.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhUBeQgiglABg5QgBg5AjgkQAjglA1AAQAzAAAgAhQAeAiABA3IAAALIjRAAQAAAvAaAeQAaAfAtAAQBKAAARhHIAUAGQgJAngbAWQgeAYguAAQg4AAgiglgABcgOQAAgtgYgaQgXgagoAAQgoAAgaAbQgaAagDAsIC2AAIAAAAg");
	this.shape_1.setTransform(81.3,-111.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag3CuIAAgTIAkAAQAHAAAAgKIAAkcQAAgMgHAAIgkAAIAAgTIAOAAQAhAAAWgDIAAE+QAAAKAFAAIAlAAIAAATg");
	this.shape_2.setTransform(61.9,-116.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhLBxQgCAYgIAiIgSAAQAEgeAAg4IAAjjQAAgMgGAAIglAAIAAgTIANAAQAjAAAWgDIAACcQAchABFAAQA2AAAgAkQAgAjAAA6QAAA8ggAkQghAlg1gBQhHAAgdhAgAgugiQgaAdAAAwIAAAGQAAAwAaAeQAaAeApAAQArAAAagdQAagdAAgyIAAgGQAAgxgagdQgagcgrgBQgpABgaAdg");
	this.shape_3.setTransform(39.975,-116.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag3CtIAAgTIAlAAQAGAAAAgKIAAi1QAAgVgMAAIgfAAIAAgTIAOAAQAhAAAWgEIAADhQAAAKAGAAIAkAAIAAATgAgViXQAAgJAGgGQAGgGAJAAQAIAAAHAGQAGAGAAAJQAAAKgGAGQgHAGgIAAQgVAAAAgWg");
	this.shape_4.setTransform(19.425,-116.475);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AiFCGQAAgrA+gQQgugGAAgjQAAghAogLQglgZAAgxQAAgmAegbQAdgaArAAQA0ABAcAhQAJgvAhAAQAKAAAIAHQAGAGAAAJQAAATgTAAQgPAAgDgQQgNALgGAZQALAUAAAZQAAAogdAZQgcAXgtgBQgbABgWgJQghAHAAAYQAAAaApAAIBfAAQBQAAABA6QgBAmglAUQgkATg+AAQh3AAAAg3gAhaBiQgUAOAAATQABApBgAAQBwAAAAg3QAAglg9AAIhOAAQggAEgSAOgAhDiIQgVATgBAhIAAACQABAgAUAUQAVATAiAAQAjAAAUgTQAVgTAAggIAAgCQAAghgVgUQgUgVgiAAQgiAAgVAVg");
	this.shape_5.setTransform(0.35,-107.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag3CtIAAgTIAlAAQAGAAAAgKIAAi1QAAgVgMAAIgfAAIAAgTIAOAAQAhAAAWgEIAADhQAAAKAGAAIAkAAIAAATgAgViXQAAgJAGgGQAGgGAJAAQAIAAAHAGQAGAGAAAJQAAAKgGAGQgHAGgIAAQgVAAAAgWg");
	this.shape_6.setTransform(-19.275,-116.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag3CuIAAgTIAkAAQAHAAgBgKIAAkcQABgMgHAAIgkAAIAAgTIAOAAQAhAAAVgDIAAE+QAAAKAHAAIAkAAIAAATg");
	this.shape_7.setTransform(-31.95,-116.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhUBeQgiglAAg5QAAg5AjgkQAiglA2AAQA0AAAeAhQAgAiAAA3IAAALIjSAAQAAAvAaAeQAcAfArAAQBLAAARhHIAUAGQgJAngbAWQgeAYguAAQg4AAgiglgABcgOQAAgtgYgaQgXgagoAAQgpAAgZAbQgaAagEAsIC3AAIAAAAg");
	this.shape_8.setTransform(-51.3,-111.675);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhBCxIAAgTIAgAAQAFAAAAgKIAAjKIgmAAIAAgTIAmAAIAAglQAAhCA7AAQAVAAAPAHIAAAVQgOgJgTABQgTAAgJAKQgHALAAAaIAAAkIA2AAIAAATIg2AAIAADKQAAAKAFAAIAnAAIAAATg");
	this.shape_9.setTransform(-81.9,-116.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag3CtIAAgTIAlAAQAGAAAAgKIAAi1QAAgVgMAAIgfAAIAAgTIAOAAQAhAAAWgEIAADhQAAAKAGAAIAkAAIAAATgAgViXQAAgJAGgGQAGgGAJAAQAIAAAHAGQAGAGAAAJQAAAKgGAGQgHAGgIAAQgVAAAAgWg");
	this.shape_10.setTransform(-95.625,-116.475);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhgAvIAAiRQAAgKgHAAIgkAAIAAgTIBGAAIAACtQgBA9A5AAQAlAAAYghQAXgfAAgxIAAhcQAAgKgGAAIglAAIAAgTIBFAAIAADbQAAALAGAAIAlAAIAAATIgNAAQgiAAgVAEIAAhBQgbBEg/gBQhPAAABhRg");
	this.shape_11.setTransform(54.2,-169.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhYBfQgjglABg6QAAg5AjglQAigkA3AAQA2AAAhAkQAjAkgBA6QAAA6giAkQgjAlg2AAQg2AAgigkgAhFhRQgbAeAAAyIAAACQAAAyAbAeQAZAeAsAAQAtAAAageQAbgegBgyIAAgCQAAgygageQgagegsAAQgsAAgaAeg");
	this.shape_12.setTransform(26.45,-169.625);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ah1CgQgOgLAAgSQAAgMAGgIQAHgHAKAAQASAAAAAQQAAAPgRAHQAHALAUAAQAWAAAPgSQARgSAUgyIAAgDIhijOQgFgKgFAAIgbAAIAAgTIBiAAIAAATIgbAAQgMAAAEALIBVCyIBMiyQAFgLgMAAIgcAAIAAgTIBeAAIAAATIgaAAQgIAAgDAKIhfDbQgWA1gPASQgVAYggAAQgWAAgPgMg");
	this.shape_13.setTransform(-0.975,-165.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhYBfQgiglAAg6QgBg5AkglQAigkA3AAQA2AAAhAkQAjAkgBA6QAAA6giAkQgjAlg2AAQg2AAgigkgAhFhRQgbAeAAAyIAAACQAAAyAbAeQAaAeArAAQAtAAAageQAageAAgyIAAgCQAAgygageQgZgegtAAQgsAAgaAeg");
	this.shape_14.setTransform(-40.05,-169.625);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgLCOQgPgOAAghIAAitIgoAAIAAgRIAegCQANgBABgNIADgtIATAAIAAA7IA+AAIAAATIg+AAIAACtQAAArAlAAQALgBAUgFIAAATQgRAGgSAAQgfAAgNgPg");
	this.shape_15.setTransform(-60.95,-172.35);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgMCOQgOgOAAghIAAitIgpAAIAAgRIAfgCQANgBABgNIADgtIAUAAIAAA7IA+AAIAAATIg/AAIAACtQAAArAmAAQAKgBATgFIAAATQgQAGgSAAQgfAAgOgPg");
	this.shape_16.setTransform(97.75,-230.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhaBrIAAg/IAVAAIAAA0QAbAQApAAQBDAAAAgzQAAgYgVgMQgOgIgjgIQgpgJgSgKQgbgRAAggQAAggAZgUQAYgTApAAQAwAAAjAXIAAA+IgVAAIAAgyQgZgQglAAQgeAAgSANQgRAMAAAYQAAAYAWAMQAMAGAlAHQApAIATANQAZARAAAhQAAAhgZAUQgYAUgrAAQgzAAgmgYg");
	this.shape_17.setTransform(79.675,-227.575);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhYBfQgjglABg6QAAg5AiglQAjgkA2AAQA3AAAhAkQAjAkAAA6QgBA6giAkQgjAlg2AAQg2AAgigkgAhGhRQgaAeAAAyIAAACQAAAyAaAeQAaAeAsAAQAtAAAageQAbgegBgyIAAgCQAAgygageQgagegsAAQgsAAgbAeg");
	this.shape_18.setTransform(55.15,-227.575);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhTBfQgiglAAg6QAAg5AkglQAkgkA3AAQAvAAAeAYQAfAYAAAoQAAAMgHAIQgGAIgLAAQgUAAAAgTQAAgVAVgBQgNg4hIAAQgtAAgbAeQgcAeAAAxIAAADQAAAyAaAeQAaAeAuAAQBKAAARhHIATAGQgJAngcAXQgdAXgtAAQg4AAgigkg");
	this.shape_19.setTransform(29.225,-227.575);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhYBfQgiglAAg6QgBg5AkglQAigkA3AAQA1AAAjAkQAhAkAAA6QABA6gjAkQgjAlg2AAQg2AAgigkgAhFhRQgbAeAAAyIAAACQAAAyAbAeQAaAeArAAQAtAAAageQAageAAgyIAAgCQAAgygZgeQgagegtAAQgsAAgaAeg");
	this.shape_20.setTransform(-8.9,-227.575);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAgCAIAAgTIAiAAQAGAAAAgKIAAiNQAAhAg5AAQglAAgZAiQgYAjAAA6IAABOQAAAKAGAAIAkAAIAAATIhvAAIAAgTIAkAAQAGAAABgKIAAi+QgBgMgGAAIgkAAIAAgTIAOAAQAgAAAXgEIAABHQAbhIBAAAQBPAAAABUIAACOQgBAKAHAAIAkAAIAAATg");
	this.shape_21.setTransform(-37.15,-227.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLCOQgPgOAAghIAAitIgoAAIAAgRIAegCQANgBABgNIADgtIATAAIAAA7IA+AAIAAATIg+AAIAACtQAAArAlAAQALgBAUgFIAAATQgRAGgSAAQgfAAgNgPg");
	this.shape_22.setTransform(-70.85,-230.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AhjBwQgWgSAAgeQAAgpAqgVQApgVBbgJIAAgOQAAgkgRgRQgRgQgjAAQg2AAgUAfQARADAAARQAAATgVAAQgWAAAAgaQAAgbAegSQAegSAqAAQBeAAAABYIAACKQAAAKAGAAIAkAAIAAATIg+AAQgEgWgCgjQgKAdgbARQgaARghAAQgkAAgVgTgAg7AMQgkARAAAhQAAAWAQANQAQAOAaAAQAoAAAZgcQAZgcAAgsIAAgWQhPAIghAPg");
	this.shape_23.setTransform(-90.525,-227.575);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhUBeQgiglAAg5QAAg5AjgkQAiglA2AAQA0AAAeAhQAgAiAAA3IAAALIjSAAQAAAvAaAeQAbAfAsAAQBLAAARhHIAUAGQgJAngbAWQgeAYguAAQg4AAgiglgABcgOQgBgtgXgaQgXgagoAAQgoAAgaAbQgaAagEAsIC3AAIAAAAg");
	this.shape_24.setTransform(94.6,-285.525);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhdCAIAAgTIAkAAQAGAAAAgKIAAi+QAAgMgGAAIglAAIAAgTIANAAQAgAAAXgEIAAA9QATg+AzAAQAYAAAOAOQANAMAAATQAAAegYAAQgIAAgGgFQgFgFAAgHQAAgRASgCQgEgTgZAAQghAAgQAgQgQAfAAA0IAABbQAAAKAGAAIAmAAIAAATg");
	this.shape_25.setTransform(71.425,-285.825);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AhYBfQgjglABg6QAAg5AjglQAigkA3AAQA2AAAhAkQAjAkgBA6QAAA6giAkQgjAlg2AAQg2AAgigkgAhFhRQgbAeAAAyIAAACQAAAyAbAeQAZAeAsAAQAtAAAageQAbgegBgyIAAgCQAAgygageQgagegsAAQgsAAgaAeg");
	this.shape_26.setTransform(47.6,-285.525);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("ABkCAIAAgTIAiAAQAGAAAAgKIAAiCQAAgogOgRQgNgSgfAAQghAAgSAbQgRAbgBAxIAABmQABAKAFAAIAnAAIAAATIhuAAIAAgTIAiAAQAGAAAAgKIAAiLQAAhCg5AAQgiAAgSAbQgSAbAAAxIAABmQAAAKAGAAIAkAAIAAATIhvAAIAAgTIAkAAQAHAAgBgKIAAi+QABgMgHAAIgkAAIAAgTIANAAQAhAAAWgEIAAA0QAXg1A1AAQA9AAALA+QAXg+A4AAQBPAAAABdIAACFQABAKAFAAIAlAAIAAATg");
	this.shape_27.setTransform(12.55,-285.825);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AhuCNQgggjAAg8QAAg7AggjQAhgkA1AAQBGAAAcBAIAAh6QAAgMgHAAIglAAIAAgTIAQAAQAfAAAYgDIAAE+QAAAKAFAAIAlAAIAAAUIhCAAQgDgYABgjQgdBAhFAAQg2AAghgkgAhYgjQgbAcABAyIAAAGQgBAyAbAdQAaAcArAAQAoAAAagcQAageABgyIAAgFQgBgwgagdQgagegoAAQgrAAgaAdg");
	this.shape_28.setTransform(-35.45,-290.15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAgCAIAAgTIAiAAQAGAAAAgKIAAiNQAAhAg5AAQgmAAgYAiQgYAjAAA6IAABOQAAAKAGAAIAkAAIAAATIhvAAIAAgTIAkAAQAHAAAAgKIAAi+QAAgMgHAAIgkAAIAAgTIAOAAQAgAAAXgEIAABHQAahIBBAAQBOAAAABUIAACOQAAAKAHAAIAkAAIAAATg");
	this.shape_29.setTransform(-65.7,-285.825);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AhjBwQgWgSAAgeQAAgpAqgVQApgVBbgJIAAgOQAAgkgRgRQgRgQgjAAQg2AAgUAfQARADAAARQAAATgVAAQgWAAAAgaQAAgbAegSQAegSAqAAQBeAAAABYIAACKQAAAKAGAAIAkAAIAAATIg+AAQgEgWgCgjQgKAdgbARQgaARghAAQgkAAgVgTgAg7AMQgkARAAAhQAAAWAQANQAQAOAaAAQAoAAAZgcQAZgcAAgsIAAgWQhPAIghAPg");
	this.shape_30.setTransform(-93.025,-285.525);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhUBeQghglgBg5QABg5AigkQAjglA2AAQAzAAAeAhQAfAiAAA3IAAALIjRAAQAAAvAaAeQAcAfAsAAQBKAAARhHIATAGQgHAngcAWQgeAYguAAQg3AAgjglgABcgOQAAgtgXgaQgYgagoAAQgpAAgaAbQgZAagEAsIC3AAIAAAAg");
	this.shape_31.setTransform(114.1,-343.475);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AhdCAIAAgTIAkAAQAGAAAAgKIAAi+QAAgMgGAAIglAAIAAgTIANAAQAgAAAXgEIAAA9QATg+AzAAQAYAAAOAOQANAMAAATQAAAegYAAQgIAAgGgFQgFgFAAgHQAAgRASgCQgEgTgZAAQghAAgQAgQgQAfAAA0IAABbQAAAKAGAAIAmAAIAAATg");
	this.shape_32.setTransform(90.925,-343.775);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AhjBwQgWgSAAgeQAAgpAqgVQApgVBbgJIAAgOQAAgkgRgRQgRgQgjAAQg2AAgUAfQARADAAARQAAATgVAAQgWAAAAgaQAAgbAegSQAegSAqAAQBeAAAABYIAACKQAAAKAGAAIAkAAIAAATIg+AAQgEgWgCgjQgKAdgbARQgaARghAAQgkAAgVgTgAg7AMQgkARAAAhQAAAWAQANQAQAOAaAAQAoAAAZgcQAZgcAAgsIAAgWQhPAIghAPg");
	this.shape_33.setTransform(68.225,-343.475);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AhTBfQgiglAAg6QAAg5AkglQAkgkA3AAQAvAAAeAYQAfAYAAAoQAAAMgHAIQgGAIgLAAQgUAAAAgTQAAgVAVgBQgNg4hIAAQgtAAgbAeQgcAeAAAxIAAADQAAAyAaAeQAaAeAuAAQBKAAARhHIATAGQgJAngcAXQgdAXgtAAQg4AAgigkg");
	this.shape_34.setTransform(41.825,-343.475);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AAgCvIAAgUIAiAAQAGAAAAgJIAAiPQAAg/g5AAQglAAgYAiQgYAjAAA6IAABPQgBAJAHAAIAjAAIAAAUIhvAAIAAgUIAkAAQAHAAAAgJIAAkdQAAgLgHAAIgkAAIAAgUIAPAAQAfAAAYgEIAACjQAbhGBAAAQBOAAAABRIAACSQAAAJAFAAIAlAAIAAAUg");
	this.shape_35.setTransform(2.8,-348.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgMCPQgOgPAAghIAAiuIgoAAIAAgQIAegCQANgBABgNIADgtIATAAIAAA7IA+AAIAAASIg+AAIAACuQAAAqAmAAQAKAAAUgFIAAAUQgSAFgRAAQgfAAgOgOg");
	this.shape_36.setTransform(-19,-346.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("Ag3CvIAAgUIAlAAQAFAAAAgJIAAkdQAAgLgFAAIglAAIAAgUIAOAAQAhAAAVgEIAAFAQABAJAFAAIAlAAIAAAUg");
	this.shape_37.setTransform(-32.55,-348.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AhjBwQgWgSAAgeQAAgpAqgVQApgVBbgJIAAgOQAAgkgRgRQgRgQgjAAQg2AAgUAfQARADAAARQAAATgVAAQgWAAAAgaQAAgbAegSQAegSAqAAQBeAAAABYIAACKQAAAKAGAAIAkAAIAAATIg+AAQgEgWgCgjQgKAdgbARQgaARghAAQgkAAgVgTgAg7AMQgkARAAAhQAAAWAQANQAQAOAaAAQAoAAAZgcQAZgcAAgsIAAgWQhPAIghAPg");
	this.shape_38.setTransform(-51.375,-343.475);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AhUBeQghglgBg5QAAg5AjgkQAiglA2AAQA0AAAeAhQAfAiABA3IAAALIjSAAQAAAvAaAeQAcAfArAAQBLAAARhHIATAGQgHAngcAWQgeAYguAAQg4AAgiglgABcgOQAAgtgYgaQgXgagoAAQgpAAgaAbQgZAagEAsIC3AAIAAAAg");
	this.shape_39.setTransform(-78.4,-343.475);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AA1CtIAAgUIAlAAQAGAAABgKIAAiIIjBAAIAACIQAAAKAHAAIAlAAIAAAUIhyAAIAAgUIAlAAQAGAAAAgKIAAkdQAAgKgGAAIglAAIAAgUIByAAIAAAUIglAAQgHAAAAAKIAACDIDBAAIAAiDQgBgKgGAAIglAAIAAgUIBxAAIAAAUIglAAQgGAAAAAKIAAEdQAAAKAGAAIAlAAIAAAUg");
	this.shape_40.setTransform(-108.95,-348.225);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-148.8,-384,297.8,301.8), null);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLAMQgFgFAAgHQAAgGAFgGQAEgFAHAAQAHAAAFAFQAFAGAAAGQAAAHgFAFQgFAGgHAAQgHAAgEgGg");
	this.shape.setTransform(100.225,31.725);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhIBjIAAgPIAcAAQAGAAAAgIIAAiSQAAgJgGAAIgcAAIAAgOIAKAAQAZAAARgDIAAAuQAPgwAnAAQATAAAKALQAKAKAAAOQAAAXgTAAQgFAAgFgEQgEgEAAgFQAAgNAOgBQgDgPgTAAQgaAAgMAZQgNAXAAAoIAABGQAAAIAGAAIAcAAIAAAPg");
	this.shape_1.setTransform(88.9,23.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhABIQgagcAAgsQAAgrAagdQAbgcApAAQAoAAAXAaQAYAaAAAqIAAAJIigAAQAAAjAUAXQAUAZAiAAQA5AAANg3IAQAFQgHAdgVASQgXASgjAAQgrAAgagdgABHgLQAAgigSgUQgSgVgfABQgfAAgUAUQgTAVgDAhICMAAIAAAAg");
	this.shape_2.setTransform(70.675,23.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgqCFIAAgPIAdAAQAEAAAAgHIAAiLQAAgQgJAAIgYAAIAAgPIALAAQAZAAARgDIAACtQgBAHAFAAIAcAAIAAAPgAgQh0QAAgHAFgEQAFgFAGAAQAGAAAGAFQAEAEAAAHQAAAHgEAFQgGAFgGAAQgQAAAAgRg");
	this.shape_3.setTransform(55.35,19.725);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAYCGIAAgPIAbAAQAEAAAAgHIAAhuQAAgwgrAAQgdAAgSAbQgTAaAAAsIAAA9QAAAHAFAAIAcAAIAAAPIhWAAIAAgPIAcAAQAEAAABgHIAAjbQgBgJgEAAIgdAAIAAgOIALAAQAZAAASgDIAAB9QAVg2AwAAQA9AAAAA+IAABwQAAAHAEAAIAcAAIAAAPg");
	this.shape_4.setTransform(38.95,19.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgIBuQgMgMAAgZIAAiFIgfAAIAAgNIAXgCQAKAAABgKIADgjIAOAAIAAAtIAwAAIAAAPIgwAAIAACFQAAAhAdAAQAIAAAPgEIAAAOQgNAFgNAAQgYAAgKgLg");
	this.shape_5.setTransform(21.775,21.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgqCGIAAgPIAcAAQAFAAAAgHIAAjbQAAgJgFAAIgcAAIAAgOIALAAQAZAAAQgDIAAD1QAAAHAFAAIAcAAIAAAPg");
	this.shape_6.setTransform(10.975,19.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhMBWQgRgNAAgXQAAggAggQQAggQBGgHIAAgKQAAgdgNgNQgNgNgbABQgqAAgPAYQANADAAAMQAAAPgQAAQgRAAAAgUQAAgVAXgOQAXgOAgAAQBJAAAABEIAABqQAAAIAEAAIAcAAIAAAOIgwAAQgDgQgBgcQgIAWgVAOQgTANgaAAQgcAAgQgPgAgtAKQgcAMAAAaQAAARANAKQAMALAUAAQAeAAAUgVQATgWAAgiIAAgRQg9AGgZAMg");
	this.shape_7.setTransform(-3.925,23.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhABIQgagcAAgsQAAgrAagdQAbgcApAAQAoAAAXAaQAYAaAAAqIAAAJIigAAQAAAjAUAXQAUAZAiAAQA5AAANg3IAQAFQgHAdgVASQgXASgjAAQgrAAgagdgABHgLQAAgigSgUQgSgVgfABQgfAAgUAUQgTAVgDAhICMAAIAAAAg");
	this.shape_8.setTransform(-25.075,23.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAZCGIAAgPIAaAAQAEAAAAgHIAAhuQAAgwgrAAQgdAAgSAbQgTAaAAAsIAAA9QAAAHAFAAIAcAAIAAAPIhWAAIAAgPIAcAAQAEAAABgHIAAjbQgBgJgEAAIgdAAIAAgOIALAAQAZAAASgDIAAB9QAVg2AxAAQA8AAAAA+IAABwQAAAHAEAAIAcAAIAAAPg");
	this.shape_9.setTransform(-46.65,19.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhFBTIAAgxIARAAIAAAoQAUAMAgAAQAzAAAAgmQAAgUgQgJQgLgGgbgGQgfgHgOgHQgVgNAAgaQAAgXATgQQATgPAfAAQAlAAAbASIAAAwIgQAAIAAgnQgUgMgcAAQgXgBgNALQgOAKAAARQAAAUARAIQAKAFAcAFQAfAHAPAJQATAOAAAYQAAAagTAQQgTAPggAAQgnAAgegSg");
	this.shape_10.setTransform(-75.725,23.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgqCFIAAgPIAdAAQAEAAAAgHIAAiLQAAgQgJAAIgYAAIAAgPIALAAQAZAAAQgDIAACtQAAAHAFAAIAcAAIAAAPgAgQh0QAAgHAFgEQAFgFAGAAQAHAAAEAFQAGAEgBAHQABAHgGAFQgEAFgHAAQgQAAAAgRg");
	this.shape_11.setTransform(-89.4,19.725);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhUBtQgZgcAAguQAAgsAZgcQAZgcApAAQA1ABAWAxIAAheQAAgJgFAAIgcAAIAAgOIALAAQAYAAATgEIAAD2QgBAHAFAAIAcAAIAAAPIgyAAQgDgSAAgbQgWAxg1ABQgpAAgZgcgAhEgbQgTAXgBAlIAAAFQABAnATAVQAUAXAhAAQAgAAATgXQAVgXgBglIAAgFQABgkgVgXQgTgXggAAQghAAgUAWg");
	this.shape_12.setTransform(77,-22.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgqCGIAAgPIAcAAQAFAAAAgHIAAjbQAAgJgFAAIgcAAIAAgOIALAAQAZAAAQgDIAAD1QAAAHAFAAIAcAAIAAAPg");
	this.shape_13.setTransform(59.775,-23.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgqCFIAAgPIAcAAQAFAAAAgHIAAiLQAAgQgJAAIgYAAIAAgPIALAAQAZAAARgDIAACtQgBAHAFAAIAcAAIAAAPgAgQh0QAAgHAFgEQAEgFAHAAQAHAAAFAFQAEAEAAAHQAAAHgEAFQgFAFgHAAQgQAAAAgRg");
	this.shape_14.setTransform(49.6,-23.075);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAYCGIAAgPIAaAAQAFAAABgHIAAhuQgBgwgrAAQgdAAgSAbQgTAaAAAsIAAA9QAAAHAFAAIAcAAIAAAPIhWAAIAAgPIAcAAQAEAAAAgHIAAjbQAAgJgEAAIgdAAIAAgOIAMAAQAYAAASgDIAAB9QAVg2AwAAQA9AAAAA+IAABwQAAAHAEAAIAcAAIAAAPg");
	this.shape_15.setTransform(33.2,-23.175);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhABJQgagcAAgtQAAgrAcgcQAbgdAqAAQAlAAAXATQAYATAAAeQAAAKgGAFQgEAGgIABQgQAAAAgQQAAgPAQgBQgKgsg4AAQghABgWAXQgVAXAAAmIAAACQAAAmAUAXQAVAYAiAAQA5AAANg3IAPAFQgHAegWARQgWASgjAAQgqAAgbgcg");
	this.shape_16.setTransform(12.15,-19.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhHBjIAAgPIAcAAQAEAAAAgIIAAiSQAAgJgEAAIgdAAIAAgOIAKAAQAZAAARgDIAAAuQAOgwAoAAQASAAAMALQAJAKAAAOQAAAXgSAAQgHAAgDgEQgFgEAAgFQAAgNAOgBQgDgPgUAAQgZAAgMAZQgNAXAAAoIAABGQABAIAEAAIAdAAIAAAPg");
	this.shape_17.setTransform(-15.2,-19.625);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhKAlIAAhwQAAgIgEAAIgdAAIAAgPIA2AAIAACFQAAAvArAAQAcAAATgZQARgYAAglIAAhHQAAgIgEAAIgdAAIAAgPIA2AAIAACpQAAAIAFAAIAcAAIAAAPIgLAAQgZAAgRADIAAgyQgVA0gwAAQg8AAAAg+g");
	this.shape_18.setTransform(-34.575,-19.175);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhEBJQgagdAAgsQAAgrAbgcQAagdAqAAQAqAAAaAcQAaAcAAAsQAAAsgaAcQgbAdgqAAQgpAAgbgcgAg1g+QgUAXAAAnIAAABQAAAmAUAYQAUAXAhAAQAiAAAVgXQAUgYAAgmIAAgBQAAgngUgXQgUgXgiAAQghAAgVAXg");
	this.shape_19.setTransform(-56.3,-19.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhZB7QgMgJAAgOQAAgJAFgGQAFgFAHAAQAPAAAAAMQAAAMgNAFQAFAJAQAAQAQAAANgOQAMgOAPgnIAAgCIhLieQgDgIgFAAIgUAAIAAgOIBLAAIAAAOIgUAAQgKAAAEAIIBACJIA7iJQADgIgJAAIgVAAIAAgOIBIAAIAAAOIgUAAQgFAAgDAIIhKCoQgQAogMAOQgPATgZAAQgSAAgKgJg");
	this.shape_20.setTransform(-77.75,-15.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-150,-51,300,97.6), null);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhHBjIAAgPIAbAAQAFAAABgIIAAiSQgBgJgFAAIgcAAIAAgOIAKAAQAYAAATgDIAAAuQANgwAoAAQATAAAKALQAKAKAAAOQAAAXgTAAQgFAAgFgEQgEgEAAgFQAAgNAOgBQgDgPgTAAQgZAAgNAZQgMAXAAAoIAABGQAAAIAEAAIAeAAIAAAPg");
	this.shape.setTransform(102.65,23.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhABIQgagcAAgsQAAgrAagdQAbgcApAAQAoAAAXAaQAYAaAAAqIAAAJIigAAQAAAjAUAXQAUAZAiAAQA5AAANg3IAQAFQgHAdgVASQgXASgjAAQgrAAgagdgABHgLQAAgigSgUQgSgVgfABQgfAAgUAUQgTAVgDAhICMAAIAAAAg");
	this.shape_1.setTransform(84.425,23.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgqCFIAAgPIAdAAQAEAAAAgHIAAiLQAAgQgJAAIgYAAIAAgPIALAAQAZAAAQgDIAACtQAAAHAFAAIAcAAIAAAPgAgQh0QAAgHAFgEQAFgFAGAAQAGAAAGAFQAEAEAAAHQAAAHgEAFQgGAFgGAAQgQAAAAgRg");
	this.shape_2.setTransform(69.1,19.725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAZCGIAAgPIAaAAQAEAAAAgHIAAhuQAAgwgrAAQgdAAgSAbQgTAaAAAsIAAA9QAAAHAFAAIAcAAIAAAPIhWAAIAAgPIAcAAQAFAAAAgHIAAjbQAAgJgFAAIgdAAIAAgOIALAAQAZAAASgDIAAB9QAVg2AxAAQA8AAAAA+IAABwQAAAHAEAAIAcAAIAAAPg");
	this.shape_3.setTransform(52.7,19.625);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIBuQgMgMAAgZIAAiFIgfAAIAAgNIAXgCQAKAAABgKIADgjIAOAAIAAAtIAwAAIAAAPIgwAAIAACFQAAAhAdAAQAIAAAPgEIAAAOQgNAFgNAAQgYAAgKgLg");
	this.shape_4.setTransform(35.525,21.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgqCGIAAgPIAcAAQAFAAAAgHIAAjbQAAgJgFAAIgcAAIAAgOIALAAQAZAAAQgDIAAD1QAAAHAFAAIAcAAIAAAPg");
	this.shape_5.setTransform(24.725,19.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhMBWQgRgNAAgXQAAggAggQQAggQBGgHIAAgKQAAgdgNgNQgNgNgbABQgqAAgPAYQANADAAAMQAAAPgQAAQgRAAAAgUQAAgVAXgOQAXgOAgAAQBJAAAABEIAABqQAAAIAEAAIAcAAIAAAOIgwAAQgDgQgBgcQgIAWgVAOQgTANgaAAQgcAAgQgPgAgtAKQgcAMAAAaQAAARANAKQAMALAUAAQAeAAAUgVQATgWAAgiIAAgRQg9AGgZAMg");
	this.shape_6.setTransform(9.825,23.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhABIQgagcAAgsQAAgrAagdQAbgcApAAQAoAAAXAaQAYAaAAAqIAAAJIigAAQAAAjAUAXQAUAZAiAAQA5AAANg3IAQAFQgHAdgVASQgXASgjAAQgrAAgagdgABHgLQAAgigSgUQgSgVgfABQgfAAgUAUQgTAVgDAhICMAAIAAAAg");
	this.shape_7.setTransform(-11.325,23.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAZCGIAAgPIAaAAQAEAAAAgHIAAhuQAAgwgrAAQgdAAgSAbQgTAaAAAsIAAA9QAAAHAFAAIAbAAIAAAPIhVAAIAAgPIAcAAQAFAAAAgHIAAjbQAAgJgFAAIgcAAIAAgOIAKAAQAZAAASgDIAAB9QAVg2AxAAQA8AAAAA+IAABwQAAAHAFAAIAbAAIAAAPg");
	this.shape_8.setTransform(-32.9,19.625);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhABIQgagcAAgsQAAgrAagdQAbgcApAAQAoAAAXAaQAYAaAAAqIAAAJIigAAQAAAjAUAXQAUAZAiAAQA5AAANg3IAQAFQgHAdgVASQgXASgjAAQgrAAgagdgABHgLQAAgigSgUQgSgVgfABQgfAAgUAUQgTAVgDAhICMAAIAAAAg");
	this.shape_9.setTransform(-63.575,23.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhIBjIAAgPIAcAAQAGAAAAgIIAAiSQAAgJgGAAIgcAAIAAgOIAKAAQAYAAATgDIAAAuQANgwAoAAQASAAALALQAKAKAAAOQAAAXgTAAQgGAAgEgEQgEgEAAgFQAAgNAOgBQgDgPgTAAQgZAAgNAZQgNAXAAAoIAABGQAAAIAGAAIAdAAIAAAPg");
	this.shape_10.setTransform(-81.75,23.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhMBWQgRgNAAgXQAAggAggQQAggQBGgHIAAgKQAAgdgNgNQgNgNgbABQgqAAgPAYQANADAAAMQAAAPgQAAQgRAAAAgUQAAgVAXgOQAXgOAgAAQBJAAAABEIAABqQAAAIAEAAIAcAAIAAAOIgwAAQgDgQgBgcQgIAWgVAOQgTANgaAAQgcAAgQgPgAgtAKQgcAMAAAaQAAARANAKQAMALAUAAQAeAAAUgVQATgWAAgiIAAgRQg9AGgZAMg");
	this.shape_11.setTransform(-99.625,23.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhKAlIAAhwQAAgIgEAAIgdAAIAAgPIA2AAIAACFQAAAvArAAQAcAAATgZQARgYAAglIAAhHQAAgIgEAAIgdAAIAAgPIA2AAIAACpQAAAIAFAAIAcAAIAAAPIgLAAQgZAAgRADIAAgyQgVA0gwAAQg8AAAAg+g");
	this.shape_12.setTransform(78.975,-19.175);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhEBJQgagdAAgsQAAgrAbgcQAbgdApAAQAqAAAaAcQAaAcAAAsQAAAsgaAcQgbAdgqAAQgpAAgbgcgAg1g+QgUAXgBAnIAAABQABAmAUAYQAUAXAhAAQAjAAAUgXQAVgYgBgmIAAgBQABgngVgXQgUgXgiAAQghAAgVAXg");
	this.shape_13.setTransform(57.25,-19.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhaB7QgLgJAAgOQAAgJAFgGQAFgFAIAAQAOAAAAAMQAAAMgNAFQAFAJAPAAQASAAAMgOQAMgOAQgnIAAgCIhMieQgDgIgFAAIgUAAIAAgOIBKAAIAAAOIgUAAQgJAAAEAIIBACJIA7iJQADgIgIAAIgXAAIAAgOIBJAAIAAAOIgUAAQgGAAgDAIIhJCoQgQAogLAOQgQATgaAAQgQAAgMgJg");
	this.shape_14.setTransform(35.8,-15.825);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAZBjIAAgPIAaAAQAEAAAAgIIAAhsQAAgxgrAAQgdAAgTAaQgTAbAAAsIAAA8QAAAIAFAAIAcAAIAAAPIhWAAIAAgPIAcAAQAFAAAAgIIAAiSQAAgJgFAAIgcAAIAAgOIALAAQAZAAARgDIAAA2QAVg4AxAAQA9AAAABBIAABtQAAAIAFAAIAcAAIAAAPg");
	this.shape_15.setTransform(4.175,-19.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhABIQgagcAAgsQAAgsAagbQAbgdApAAQAoAAAXAaQAYAaAAAqIAAAIIigAAQAAAlAUAXQAUAYAiAAQA5AAANg3IAQAFQgHAegVAQQgXATgjAAQgrAAgagdgABHgKQAAgjgSgUQgSgUgfgBQgfAAgUAWQgTAUgDAiICMAAIAAAAg");
	this.shape_16.setTransform(-17.625,-19.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAZCGIAAgPIAaAAQAEAAAAgHIAAhuQAAgwgrAAQgdAAgSAbQgTAaAAAsIAAA9QAAAHAFAAIAbAAIAAAPIhVAAIAAgPIAcAAQAFAAAAgHIAAjbQAAgJgFAAIgcAAIAAgOIAKAAQAZAAASgDIAAB9QAVg2AxAAQA8AAAAA+IAABwQAAAHAFAAIAbAAIAAAPg");
	this.shape_17.setTransform(-39.2,-23.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("ABJCFIhJjjIhIDjIgRAAIhEjyQgDgJgGAAIgZAAIAAgOIBWAAIAAAOIgbAAQgHAAACAIIA7DTIBGjWQABgFgEAAIggAAIAAgOIBeAAIAAAOIgiAAQgGAAACAFIBGDVIA6jSQACgIgGAAIgeAAIAAgOIBVAAIAAAOIgZAAQgHAAgCAJIhEDyg");
	this.shape_18.setTransform(-70.45,-22.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-150,-51,300,97.6), null);


(lib.covwhiteRGBai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// co-v-white-RGB.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(526.5006,189.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(271.9321,70.8329);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(494.55,205.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(438.825,205.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(386.35,217.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(336.35,205.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(296.35,205.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(236.525,200.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(171.8,205.55);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(132.5,205.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(85.3,205.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(28.225,200.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0.1,533.9,251.3);


(lib.BUTTONbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnmC7Qg1AAgmgmQglglAAg1IAAh1QAAg1AlglQAmgmA1AAIPNAAQA1AAAmAmQAlAlAAA1IAAB1QAAA1glAlQgmAmg1AAg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-18.6,123,37.3);


(lib.covwhiteeps = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.covwhiteRGBai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.36,0.36,0,0,0,266.8,125.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-96,-45.2,192.2,90.5);


(lib.BUTTON = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("AgaA1IAAgQIAHAAIADgBIAAgFIAAgVIgagpQgDgFgEAAIgEAAIAAgQIA2AAIAAAQIgEAAQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAACABADIAMAUIAMgWQADgFgGAAIgGAAIAAgQIAsAAIAAAQIgFAAQgEAAgEAFIgZAoIAAAWQAAAFAEABIAHAAIAAAQg");
	this.shape.setTransform(31.525,7.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_1.setTransform(21.625,7.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAAKAIQALAHAAARQAAASgKAGQgKAIgXAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgEgEQgDgEgIAAIgHAAg");
	this.shape_2.setTransform(12.35,7.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAALAIQAKAHAAARQAAASgKAGQgLAIgWAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgDgEQgEgEgIAAIgHAAg");
	this.shape_3.setTransform(2.6,7.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_4.setTransform(-7.975,7.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaABQgZgBgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAJQAFAGAKABQALgBAFgGQAFgJAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_5.setTransform(-22.575,7.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF8300").s().p("AgbA1IAAgQIAHAAQAEgBAAgFIAAhDIgCAAIgKABQgCABgBAFIgCAIIgPAAIAAgfIBhAAIAAAfIgPAAIgBgIQgBgEgEgCIgKgBIgCAAIAABDQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAAAAAAAQABAAAAAAQABABAAAAIAHAAIAAAQg");
	this.shape_6.setTransform(-33.15,7.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF8300").s().p("AASA1IgSg2IgSA2IgaAAIgZhTQgCgGgEAAIgFAAIAAgQIAzAAIAAAQIgEAAIgEABIABAEIANArIANgrQACgFgFAAIgFAAIAAgQIAwAAIAAAQIgFAAQgEAAACAFIAOAsIANgsQABgFgEAAIgGAAIAAgQIAoAAIAAAQIgFAAIgEABIgCAFIgaBTg");
	this.shape_7.setTransform(38.15,-6.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaAAQgZAAgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAIQAFAIAKAAQALAAAFgIQAFgIAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_8.setTransform(24.525,-6.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF8300").s().p("AAHA1IAAgQIAFAAQAEgBAAgFIAAgYIgfAAIAAAYQAAAFAEABIAFAAIAAAQIg0AAIAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgGAAIAAgQIA0AAIAAAQIgFAAQgEAAAAAFIAAAYIAfAAIAAgYQAAgFgEAAIgFAAIAAgQIA0AAIAAAQIgGAAQgEAAAAAFIAAA+QAAAFAEABIAGAAIAAAQg");
	this.shape_9.setTransform(13.075,-6.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF8300").s().p("AAXA1IgxhEIAAAuQAAAFAEABIAHAAIAAAQIgpAAIAAgQIAHAAQAEgBAAgFIAAg+QAAgFgEAAIgHAAIAAgQIArAAIAnA3IAAgiQAAgFgDAAIgHAAIAAgQIApAAIAAAQIgHAAQgEAAAAAFIAABUg");
	this.shape_10.setTransform(-1.625,-6.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF8300").s().p("AAcA1QgRAAgCgcQgCgJgCgDQgDgFgGABIgFAAIAAAWQAAAFADABIAGAAIAAAQIg0AAIAAgQIAFAAQAFgBAAgFIAAg+QAAgFgFAAIgFAAIAAgQIA8AAQAnAAAAAdQgBAVgWADQALAEAFAGQAEAHABALQAAAIAGAAIACAAIAAAQgAgJgEIAGAAQAIAAAFgEQADgDAAgKQAAgHgDgEQgEgEgHAAIgIAAg");
	this.shape_11.setTransform(-12.4,-6.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_12.setTransform(-23.375,-6.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF8300").s().p("AguA1IAAgQIAGAAQAEgBAAgFIAAg+QAAgFgEAAIgGAAIAAgQIBcAAIAAAeIgQAAIgDgIQgCgEgCgBIgJgBIgRAAIAAAcIAIAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAIABgGIAAgDIAPAAIAAAlIgPAAIAAgEQAAgIgFABIgIAAIAAAdIASAAQAHAAACgBQACgBADgFIACgHIAQAAIAAAeg");
	this.shape_13.setTransform(-33.925,-6.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_14.setTransform(-43.125,-6.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.instance = new lib.BUTTONbkgd();
	this.instance.parent = this;
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_3
	this.instance_1 = new lib.Buttonshad();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-69,-27,0.5544,0.5544);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-69,-27,143.6,59.3), null);


(lib.ARToutline = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.MotherChildoutlineai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0.05,1,1,0,0,0,150.1,61.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ARToutline, new cjs.Rectangle(-151.1,-61.8,302.29999999999995,123.6), null);


(lib.ARTall = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.MotherChildallai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,-0.05,1,1,0,0,0,150.1,64.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ARTall, new cjs.Rectangle(-151.1,-64.6,302.29999999999995,129.2), null);


// stage content:
(lib.CO_Child_300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_165 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(165).call(this.frame_165).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A3WzcMAutAAAMAAAAm5MgutAAAg");
	this.shape.setTransform(150,300.0216,1,2.4056);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(166));

	// RULE
	this.instance = new lib.RULE();
	this.instance.parent = this;
	this.instance.setTransform(447.1,415.1,1.0111,1,0,0,0,0.1,0.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(124).to({_off:false},0).to({x:150.1},12,cjs.Ease.quintIn).wait(30));

	// LOGO
	this.instance_1 = new lib.covwhiteeps("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(416.9,645.7,1,1,0,0,0,266.9,125.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(166));

	// BUTTON
	this.instance_2 = new lib.BUTTON();
	this.instance_2.parent = this;
	this.instance_2.setTransform(155,415);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(155).to({_off:false},0).to({alpha:1},10).wait(1));

	// Child
	this.instance_3 = new lib.MotherChildCHILDonlyai();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150.1,233.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.instance_4 = new lib.ARTall();
	this.instance_4.parent = this;
	this.instance_4.setTransform(150.1,233.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(71).to({_off:false},0).to({alpha:1},8).to({_off:true},45).wait(42));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(124).to({_off:false},0).to({x:-151},12,cjs.Ease.quintIn).to({_off:true},1).wait(29));

	// Mother
	this.instance_5 = new lib.MotherChildMOTHERonlyai();
	this.instance_5.parent = this;
	this.instance_5.setTransform(150.1,233.6);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.instance_6 = new lib.ARTall();
	this.instance_6.parent = this;
	this.instance_6.setTransform(150.1,233.6);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(31).to({_off:false},0).to({alpha:1},8).to({_off:true},85).wait(42));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(124).to({_off:false},0).to({x:-151},12,cjs.Ease.quintIn).to({_off:true},1).wait(29));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgASAu4MAAAhdvIAlAAMAAABdvg");
	var mask_graphics_1 = new cjs.Graphics().p("EgBTAu4MAAAhdvICnAAMAAABdvg");
	var mask_graphics_2 = new cjs.Graphics().p("EgCTAu4MAAAhdvIEnAAMAAABdvg");
	var mask_graphics_3 = new cjs.Graphics().p("EgDUAu4MAAAhdvIGpAAMAAABdvg");
	var mask_graphics_4 = new cjs.Graphics().p("EgEUAu4MAAAhdvIIpAAMAAABdvg");
	var mask_graphics_5 = new cjs.Graphics().p("EgFUAu4MAAAhdvIKpAAMAAABdvg");
	var mask_graphics_6 = new cjs.Graphics().p("EgGVAu4MAAAhdvIMrAAMAAABdvg");
	var mask_graphics_7 = new cjs.Graphics().p("EgHVAu4MAAAhdvIOrAAMAAABdvg");
	var mask_graphics_8 = new cjs.Graphics().p("EgIVAu4MAAAhdvIQrAAMAAABdvg");
	var mask_graphics_9 = new cjs.Graphics().p("EgJWAu4MAAAhdvIStAAMAAABdvg");
	var mask_graphics_10 = new cjs.Graphics().p("EgKWAu4MAAAhdvIUtAAMAAABdvg");
	var mask_graphics_11 = new cjs.Graphics().p("EgLWAu4MAAAhdvIWtAAMAAABdvg");
	var mask_graphics_12 = new cjs.Graphics().p("EgL9Au4MAAAhdvIX7AAMAAABdvg");
	var mask_graphics_13 = new cjs.Graphics().p("EgMkAu4MAAAhdvIZJAAMAAABdvg");
	var mask_graphics_14 = new cjs.Graphics().p("EgNKAu4MAAAhdvIaVAAMAAABdvg");
	var mask_graphics_15 = new cjs.Graphics().p("EgNxAu4MAAAhdvIbjAAMAAABdvg");
	var mask_graphics_16 = new cjs.Graphics().p("EgOYAu4MAAAhdvIcxAAMAAABdvg");
	var mask_graphics_17 = new cjs.Graphics().p("EgO+Au4MAAAhdvId9AAMAAABdvg");
	var mask_graphics_18 = new cjs.Graphics().p("EgPlAu4MAAAhdvIfLAAMAAABdvg");
	var mask_graphics_19 = new cjs.Graphics().p("EgQLAu4MAAAhdvMAgXAAAMAAABdvg");
	var mask_graphics_20 = new cjs.Graphics().p("EgQyAu4MAAAhdvMAhlAAAMAAABdvg");
	var mask_graphics_21 = new cjs.Graphics().p("EgRZAu4MAAAhdvMAizAAAMAAABdvg");
	var mask_graphics_22 = new cjs.Graphics().p("EgR/Au4MAAAhdvMAj/AAAMAAABdvg");
	var mask_graphics_23 = new cjs.Graphics().p("EgSmAu4MAAAhdvMAlNAAAMAAABdvg");
	var mask_graphics_24 = new cjs.Graphics().p("EgTMAu4MAAAhdvMAmZAAAMAAABdvg");
	var mask_graphics_25 = new cjs.Graphics().p("EgTzAu4MAAAhdvMAnnAAAMAAABdvg");
	var mask_graphics_26 = new cjs.Graphics().p("EgUaAu4MAAAhdvMAo1AAAMAAABdvg");
	var mask_graphics_27 = new cjs.Graphics().p("EgVAAu4MAAAhdvMAqBAAAMAAABdvg");
	var mask_graphics_28 = new cjs.Graphics().p("EgVnAu4MAAAhdvMArPAAAMAAABdvg");
	var mask_graphics_29 = new cjs.Graphics().p("EgWOAu4MAAAhdvMAsdAAAMAAABdvg");
	var mask_graphics_30 = new cjs.Graphics().p("EgW0Au4MAAAhdvMAtpAAAMAAABdvg");
	var mask_graphics_31 = new cjs.Graphics().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:1.9003,y:300.0246}).wait(1).to({graphics:mask_graphics_1,x:8.3422,y:300.0246}).wait(1).to({graphics:mask_graphics_2,x:14.784,y:300.0246}).wait(1).to({graphics:mask_graphics_3,x:21.2259,y:300.0246}).wait(1).to({graphics:mask_graphics_4,x:27.6677,y:300.0246}).wait(1).to({graphics:mask_graphics_5,x:34.1096,y:300.0246}).wait(1).to({graphics:mask_graphics_6,x:40.5514,y:300.0246}).wait(1).to({graphics:mask_graphics_7,x:46.9932,y:300.0246}).wait(1).to({graphics:mask_graphics_8,x:53.4351,y:300.0246}).wait(1).to({graphics:mask_graphics_9,x:59.874,y:300.0246}).wait(1).to({graphics:mask_graphics_10,x:66.3128,y:300.0246}).wait(1).to({graphics:mask_graphics_11,x:72.7121,y:300.0246}).wait(1).to({graphics:mask_graphics_12,x:76.5703,y:300.0246}).wait(1).to({graphics:mask_graphics_13,x:80.4284,y:300.0246}).wait(1).to({graphics:mask_graphics_14,x:84.2866,y:300.0246}).wait(1).to({graphics:mask_graphics_15,x:88.1447,y:300.0246}).wait(1).to({graphics:mask_graphics_16,x:92.0028,y:300.0246}).wait(1).to({graphics:mask_graphics_17,x:95.861,y:300.0246}).wait(1).to({graphics:mask_graphics_18,x:99.7191,y:300.0246}).wait(1).to({graphics:mask_graphics_19,x:103.5773,y:300.0246}).wait(1).to({graphics:mask_graphics_20,x:107.4354,y:300.0246}).wait(1).to({graphics:mask_graphics_21,x:111.2936,y:300.0246}).wait(1).to({graphics:mask_graphics_22,x:115.1517,y:300.0246}).wait(1).to({graphics:mask_graphics_23,x:119.0099,y:300.0246}).wait(1).to({graphics:mask_graphics_24,x:122.868,y:300.0246}).wait(1).to({graphics:mask_graphics_25,x:126.7261,y:300.0246}).wait(1).to({graphics:mask_graphics_26,x:130.5843,y:300.0246}).wait(1).to({graphics:mask_graphics_27,x:134.4424,y:300.0246}).wait(1).to({graphics:mask_graphics_28,x:138.3006,y:300.0246}).wait(1).to({graphics:mask_graphics_29,x:142.1587,y:300.0246}).wait(1).to({graphics:mask_graphics_30,x:146.0169,y:300.0246}).wait(1).to({graphics:mask_graphics_31,x:149.975,y:300.0246}).wait(49).to({graphics:null,x:0,y:0}).wait(86));

	// ART-outline
	this.instance_7 = new lib.ARToutline();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150.1,230.8);

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},80).wait(86));

	// HEAD1
	this.instance_8 = new lib.HEAD1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,106.05);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(31).to({_off:false},0).to({alpha:1},8).wait(75).to({x:-60},12,cjs.Ease.quintIn).to({_off:true},1).wait(39));

	// HEAD2
	this.instance_9 = new lib.HEAD2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(150,360.05);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(71).to({_off:false},0).to({alpha:1},8).wait(39).to({x:-81},14,cjs.Ease.quintIn).to({_off:true},1).wait(33));

	// HEAD3
	this.instance_10 = new lib.HEAD3();
	this.instance_10.parent = this;
	this.instance_10.setTransform(150,416.3,1,1,0,0,0,0,-15);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(141).to({_off:false},0).to({alpha:1},10).wait(15));

	// bkgd
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(166));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-151.9,299.5,749.9,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 600,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_Child_300x600_atlas_.png?1570215988206", id:"CO_Child_300x600_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;