(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_MoreThan_300x250_atlas_", frames: [[0,0,259,107]]}
];


// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_MoreThan_300x250_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.RULE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,2,1).p("A3LAAMAuXAAA");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.RULE, new cjs.Rectangle(-149.3,-1,298.70000000000005,2), null);


(lib.HousingOUTLINEai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Housing-OUTLINE.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,1,1).p("A3bk3IIHAAQBHAOBgAVQA/AOAWACQAYgFBVgWQBPgVAdgJQAHANAzBHQAvBEAdAnQAkgIAxgZQAcgOA+ghQAHAOAhBKQAeBGAKAVQAAEDAABWIZWAA");
	this.shape.setTransform(150.5,32.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-0.5,302,65.6);


(lib.HousingALLai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Housing-ALL.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,1,1).p("AkJhhIAAB6IBIAMIgChzgArsj3IDfhiQAJAOAzBFQAtA9ASAYQA+AZADgDQAwgdBNgyQAUAzAiBQIAkACQgKgUgehGQghhLgHgOQg+AhgcAPQgxAZgkAHQgdgmgvhEQgzhIgHgMQgdAIhPAVQhVAXgYAFQgWgDg/gOQhggVhHgOQgDCPAAD0QgBCIAAD9QAEAAAGgBQAWgEApgJQAzgLANgFQAAiSgFnpQAEABAEABQAXAGArANQAwAPAaAGQABA1ACDjQABCsADBsQABAAAEAAQAZgEB6gSQBbgOA7gNQgChKAAiKQAAiSgChCQADACAEABQAJAEAOAFQALADAVAHQAFCEAAEOIAMgCQB9gVAhgEQAFAAAQgDQASgEAAgBQABhVAAkEApjBHIADDVICNgOIgCjCgApYi0IAECgICDAUIgCiXgAjmBnIAAB6IAigEIAAh0gAs0jEIgCBTIBLALIAAhRgAs5BlIACDjIBPgKIgBjZgA3bmBIIHAAAh7D0IZXAA");
	this.shape.setTransform(150.5,39.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-0.5,302,80.3);


(lib.HEAD4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AANA8IAAgMIAOAAQADABAAgGIAAg9QAAgbgYAAQgQgBgJAOQgKAPAAAYIAAAkQAAAGADgBIAPAAIAAAMIg2AAIAAgMIAPAAQADABAAgGIAAhRQAAgHgDAAIgPAAIAAgKIAJAAQARAAAKgCIAAAeQALggAdAAQAlAAAAApIAAA9QAAAGADgBIAPAAIAAAMg");
	this.shape.setTransform(46.475,0.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgpAsQgRgRAAgbQAAgaARgRQARgRAZAAQAaAAAPARQARARgBAaQABAbgRARQgQARgaAAQgZAAgQgRgAgdgjQgKANAAAWIAAABQAAAXAKAMQALANASAAQAUAAAKgNQALgMAAgXIAAgBQAAgWgLgNQgKgNgTAAQgTAAgLANg");
	this.shape_1.setTransform(32.95,0.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaBRIAAgLIAPAAQADAAAAgGIAAhOQAAgJgGAAIgMAAIAAgLIAKAAQAQAAAJgCIAABkQAAAGADAAIAPAAIAAALgAgJg7QgDgDAAgGQAAgFADgDQAEgEAFAAQAFAAAEAEQADADAAAFQAAAGgDADQgEAEgFAAQgFAAgEgEg");
	this.shape_2.setTransform(23.375,-2.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHBCQgHgHAAgRIAAhLIgSAAIAAgKIANgBQAIgBABgHIABgVIAMAAIAAAdIAbAAIAAALIgbAAIAABLQAAALAEAEQAEAEAJAAQAGABAHgDIAAALQgIADgJAAQgQABgHgIg");
	this.shape_3.setTransform(16.525,-1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgvA0QgKgIAAgOQAAgTATgKQATgJApgEIAAgHQAAgPgHgHQgHgHgQAAQgUAAgJAKQAIACAAAJQAAAFgDADQgEADgFAAQgNAAAAgOQAAgNAPgJQAOgIAUAAQAXAAALAKQALAKAAAVIAAA9QAAAFADAAIAPAAIAAALIggAAQgCgKgBgOQgGAMgLAHQgMAIgPAAQgRAAgJgJgAgYAGQgPAIAAAOQgBAJAIAGQAGAGAKAAQARAAALgMQAKgMAAgTIAAgJQggADgOAGg");
	this.shape_4.setTransform(7,0.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgnAsQgQgQAAgcQAAgaARgRQAQgRAaAAQAXAAAOALQAPAMAAASQAAAHgEAFQgFAEgGAAQgFAAgEgDQgDgDAAgFQAAgLAMgBQgGgWgeAAQgTAAgLANQgLANAAAVIAAACQAAAWAKANQALANATAAQAfAAAJgeIAMAEQgLAmgqAAQgaAAgQgRg");
	this.shape_5.setTransform(-5.55,0.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgvAVIAAg/QAAgFgCAAIgQAAIAAgLIAkAAIAABOQAAAbAZAAQAOAAAKgOQAKgNAAgUIAAgqQgBgFgDAAIgPAAIAAgLIAlAAIAABiQAAAGADAAIAPAAIAAALIgKAAQgRAAgJACIAAgcQgMAcgcAAQglAAAAgmg");
	this.shape_6.setTransform(-18.65,0.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgzBBQgPgQAAgcQAAgaAPgRQAPgRAYAAQAfAAAMAdIAAg0QAAgGgDAAIgQAAIAAgLIALAAQAQAAAKgCIAACQQAAAFADAAIAPAAIAAALIgiAAIgCgZQgMAcgfAAQgYAAgPgRgAgkgOQgLANAAAVIAAADQAAAWALAMQAKAMATAAQAQAAALgMQALgNAAgWIAAgCQAAgVgLgMQgLgNgQAAQgTAAgKAMg");
	this.shape_7.setTransform(-32.425,-1.925);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag8BQIAAgLIAQAAQADAAAAgGIAAh9QAAgFgDAAIgQAAIAAgMIB0AAIAAAjIgNAAIgBgSQgBgFgIAAIg4AAIAAA9IAjAAQAGAAAAgFIAAgLIALAAIAAAsIgLAAIAAgMQAAgFgGAAIgjAAIAABAIA9AAQAJAAAAgGIABgSIANAAIAAAjg");
	this.shape_8.setTransform(-46.85,-1.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD4, new cjs.Rectangle(-80.5,-14,161,28), null);


(lib.HEAD3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgzBBQgPgQAAgcQAAgaAPgRQAPgRAYAAQAfAAAMAdIAAg0QAAgGgDAAIgQAAIAAgLIALAAQAQAAAKgCIAACQQAAAFADAAIAPAAIAAALIgiAAIgCgZQgMAcgfAAQgYAAgPgRgAgkgOQgLANAAAVIAAADQAAAWALAMQAKAMATAAQAQAAALgMQALgNAAgWIAAgCQAAgVgLgMQgLgNgQAAQgTAAgKAMg");
	this.shape.setTransform(52.275,-1.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgpAsQgQgRAAgbQAAgaAQgRQAQgRAZAAQAbAAAQARQAPARABAaQgBAbgPARQgRARgaAAQgZAAgQgRgAgdgjQgKANAAAWIAAABQAAAXAKAMQALANASAAQATAAALgNQALgMAAgXIAAgBQAAgWgLgNQgKgNgUAAQgSAAgLANg");
	this.shape_1.setTransform(38.5,0.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpAsQgQgRgBgbQABgaAQgRQAQgRAZAAQAaAAARARQAPARAAAaQAAAbgPARQgRARgaAAQgZAAgQgRgAgcgjQgLANAAAWIAAABQAAAXALAMQAKANASAAQAUAAAKgNQALgMAAgXIAAgBQAAgWgLgNQgLgNgTAAQgSAAgKANg");
	this.shape_2.setTransform(25.6,0.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag6BQIAAgLIAQAAQADAAAAgGIAAh9QAAgFgDAAIgQAAIAAgMIB1AAIAAAjIgNAAIgBgSQgBgFgIAAIg5AAIAABBIAiAAQAGAAAAgFIAAgLIALAAIAAArIgLAAIAAgLQAAgFgGAAIgiAAIAAA2QAAAGAEAAIAQAAIAAALg");
	this.shape_3.setTransform(12.375,-1.975);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AANBRIAAgMIAOAAQADABAAgGIAAg+QAAgbgYABQgPgBgKAOQgKAOAAAZIAAAkQAAAGADgBIAOAAIAAAMIg2AAIAAgMIAQAAQADABAAgGIAAh9QAAgFgDgBIgQAAIAAgLIALAAQARAAAJgBIAABIQAMgfAcAAQAlAAAAAnIAAA/QAAAGADgBIAPAAIAAAMg");
	this.shape_4.setTransform(-6.45,-2.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgrAyIAAgdIAOAAIAAAXQALAGARAAQAcAAAAgVQAAgLgJgFQgGgDgPgEQgTgEgJgEQgMgIAAgPQAAgQAMgJQAMgKAUAAQAXAAARALIAAAdIgOAAIAAgWQgKgHgQAAQgbAAAAAVQAAAKAJAFQAGADAPADQATAEAJAFQAMAIAAAQQAAAQgMAJQgMAKgUAAQgYAAgTgLg");
	this.shape_5.setTransform(-18.525,0.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnAsQgQgRAAgbQAAgaARgQQAQgSAZAAQAYAAAPAQQAOAQAAAaIAAAFIhdAAQABAUAKANQAMANASAAQAgAAAHgeIAMAEQgEARgMAKQgPALgUAAQgbAAgQgRgAAmgHQAAgUgKgKQgJgLgRAAQgQAAgLALQgKALgCATIBLAAIAAAAg");
	this.shape_6.setTransform(-29.9,0.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AguA8IAAgMIAQAAQADABAAgGIAAhRQAAgHgDAAIgQAAIAAgKIAKAAQAQAAAKgCIAAAbQAJgdAXAAQAMABAGAGQAHAHAAAKQAAARgPAAQgFAAgDgDQgDgDAAgFQAAgIAKgCQgCgHgLAAQgOgBgGAOQgHAOAAAVIAAApQAAAGADgBIAPAAIAAAMg");
	this.shape_7.setTransform(-41.05,0.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag6BQIAAgLIAQAAQADAAAAgGIAAh9QAAgFgDAAIgQAAIAAgMIB1AAIAAAjIgNAAIgBgSQgBgFgIAAIg5AAIAABBIAiAAQAGAAAAgFIAAgLIALAAIAAArIgLAAIAAgLQAAgFgGAAIgiAAIAAA2QAAAGAEAAIAQAAIAAALg");
	this.shape_8.setTransform(-52.925,-1.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-80.5,-14,161,28), null);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhAA/QABgTAdgGQgXgEABgRQgBgQAUgFQgSgLAAgWQABgSAOgMQAOgMAWAAQAVAAAPANQAEgWAQAAQAFAAAEADQADAEAAAEQAAAFgDADQgCADgFAAQgHAAgCgIQgFAFgEAJQAIAKAAANQAAATgOALQgOAKgVAAQgNAAgKgDQgPACAAAKQABALASAAIAtAAQAlAAAAAdQAAASgRAJQgRAKgeAAQg5AAgBgagAgwA+QgBARAsAAQAxAAAAgXQAAgJgHgEQgGgDgOAAIgmAAQgcAFABARgAgcg8QgJAIAAAPIAAABQAAAOAJAIQAIAIAPAAQAOAAAIgIQAIgIAAgOIAAgBQAAgPgIgIQgIgJgNAAQgQAAgIAJg");
	this.shape.setTransform(37.15,2.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AANA8IAAgMIAOAAQADABAAgGIAAg9QAAgbgYAAQgQgBgJAOQgKAPAAAYIAAAkQAAAGADgBIAPAAIAAAMIg2AAIAAgMIAPAAQADABAAgGIAAhRQAAgHgDAAIgPAAIAAgKIAJAAQARAAAKgCIAAAeQALggAdAAQAlAAAAApIAAA9QAAAGADgBIAPAAIAAAMg");
	this.shape_1.setTransform(23.725,0.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaBRIAAgLIAPAAQADAAAAgGIAAhOQAAgJgGAAIgMAAIAAgLIAKAAQAQAAAJgCIAABkQAAAGADAAIAPAAIAAALgAgJg7QgDgDAAgGQAAgFADgDQAEgEAFAAQAFAAAEAEQADADAAAFQAAAGgDADQgEAEgFAAQgFAAgEgEg");
	this.shape_2.setTransform(13.525,-2.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgrAyIAAgdIAOAAIAAAXQALAGARAAQAcAAAAgVQAAgLgJgFQgGgDgPgEQgTgEgJgEQgMgIAAgPQAAgQAMgJQAMgKAUAAQAXAAARALIAAAdIgOAAIAAgWQgKgHgQAAQgbAAAAAVQAAAKAJAFQAGADAPADQATAEAJAFQAMAIAAAQQAAAQgMAJQgMAKgUAAQgYAAgTgLg");
	this.shape_3.setTransform(5.175,0.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgvAVIAAg/QAAgFgCAAIgQAAIAAgLIAkAAIAABOQAAAbAZAAQAOAAAKgOQAKgNAAgUIAAgqQgBgFgDAAIgPAAIAAgLIAlAAIAABiQAAAGADAAIAPAAIAAALIgKAAQgRAAgJACIAAgcQgMAcgcAAQglAAAAgmg");
	this.shape_4.setTransform(-6.95,0.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpAsQgRgRAAgbQAAgaARgRQARgRAZAAQAaAAAPARQARARgBAaQABAbgRARQgQARgaAAQgZAAgQgRgAgdgjQgKANAAAWIAAABQAAAXAKAMQALANASAAQAUAAAKgNQALgMAAgXIAAgBQAAgWgLgNQgKgNgTAAQgTAAgLANg");
	this.shape_5.setTransform(-20.15,0.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAWBQIAAgLIAQAAQAEAAAAgGIAAg7IhTAAIAAA7QAAAGAEAAIAPAAIAAALIg4AAIAAgLIAQAAQADAAAAgGIAAh9QAAgFgDAAIgQAAIAAgMIA4AAIAAAMIgPAAQgEAAAAAFIAAA4IBTAAIAAg4QAAgFgEAAIgQAAIAAgMIA5AAIAAAMIgQAAQgDAAAAAFIAAB9QAAAGADAAIAQAAIAAALg");
	this.shape_6.setTransform(-34.925,-1.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-80.5,-14,161,28), null);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoAsQgPgRAAgbQAAgaAQgQQARgSAZAAQAYAAAOAQQAPAQAAAaIAAAFIhcAAQAAAUALANQALANASAAQAfAAAJgeIALAEQgEARgNAKQgNALgWAAQgbAAgQgRgAAmgHQAAgUgJgKQgKgLgRAAQgQAAgKALQgLALgBATIBKAAIAAAAg");
	this.shape.setTransform(56.45,0.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgtA8IAAgMIAOAAQAEABAAgGIAAhRQAAgHgEAAIgOAAIAAgKIAJAAQAQAAALgCIAAAbQAHgdAYAAQALABAHAGQAGAHABAKQgBARgOAAQgEAAgDgDQgEgDAAgFQAAgIAJgCQgBgHgKAAQgPgBgGAOQgHAOAAAVIAAApQAAAGADgBIAPAAIAAAMg");
	this.shape_1.setTransform(45.3,0.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgvA0QgKgIAAgOQAAgTATgKQATgJApgEIAAgHQAAgPgIgHQgGgHgPAAQgVAAgJAKQAIACAAAJQAAAFgDADQgEADgFAAQgNAAAAgOQAAgNAOgJQAPgIAUAAQAXAAALAKQALAKAAAVIAAA9QAAAFADAAIAPAAIAAALIggAAQgDgKAAgOQgFAMgNAHQgLAIgPAAQgRAAgJgJgAgYAGQgQAIAAAOQAAAJAIAGQAGAGALAAQAQAAALgMQAKgMAAgTIAAgJQggADgOAGg");
	this.shape_2.setTransform(34.2,0.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgxA9QgVgWAAgmQAAglAVgXQAVgWAfAAQATAAANAJQANAIAGAPIAEgeIALAAIAAA6IgPAAQgJgwgoAAQgZAAgPASQgQASAAAgIAAADQAAAgAPASQAPASAaAAQAUAAAPgLQAOgLADgYIAOACQgDAagRAPQgTAPgcAAQggAAgVgVg");
	this.shape_3.setTransform(19.7,-1.975);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AANBRIAAgMIAOAAQADABAAgGIAAg+QAAgbgYABQgQgBgJAOQgKAOAAAZIAAAkQAAAGADgBIAOAAIAAAMIg2AAIAAgMIAQAAQADABAAgGIAAh9QAAgFgDgBIgQAAIAAgLIALAAQARAAAJgBIAABIQAMgfAdAAQAkAAAAAnIAAA/QAAAGADgBIAQAAIAAAMg");
	this.shape_4.setTransform(-0.55,-2.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgHBCQgHgHAAgRIAAhLIgSAAIAAgKIANgBQAIgBABgHIABgVIAMAAIAAAdIAbAAIAAALIgbAAIAABLQAAALAEAEQAEAEAJAAQAGABAHgDIAAALQgIADgJAAQgQABgHgIg");
	this.shape_5.setTransform(-11.125,-1.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgaBRIAAgMIAPAAQADABAAgGIAAh9QAAgFgDgBIgPAAIAAgLIAKAAQAQAAAKgBIAACPQAAAGACgBIAPAAIAAAMg");
	this.shape_6.setTransform(-17.8,-2.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgvA0QgKgIAAgOQAAgTAUgKQASgJApgEIAAgHQAAgPgHgHQgIgHgPAAQgUAAgIAKQAHACAAAJQAAAFgEADQgDADgFAAQgNAAAAgOQAAgNAPgJQANgIAVAAQAXAAALAKQALAKAAAVIAAA9QAAAFADAAIAPAAIAAALIggAAQgCgKgBgOQgGAMgLAHQgMAIgPAAQgQAAgKgJgAgYAGQgPAIAAAOQAAAJAGAGQAHAGAKAAQARAAAKgMQALgMAAgTIAAgJQggADgOAGg");
	this.shape_7.setTransform(-26.95,0.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgoAsQgPgRAAgbQAAgaAQgQQARgSAYAAQAZAAAOAQQAPAQAAAaIAAAFIhcAAQAAAUALANQALANASAAQAfAAAJgeIALAEQgEARgNAKQgNALgWAAQgaAAgRgRgAAmgHQAAgUgKgKQgJgLgRAAQgQAAgLALQgKALgBATIBKAAIAAAAg");
	this.shape_8.setTransform(-39.75,0.175);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAWBQIAAgLIAQAAQAEAAAAgGIAAg7IhTAAIAAA7QAAAGAEAAIAPAAIAAALIg4AAIAAgLIAQAAQADAAAAgGIAAh9QAAgFgDAAIgQAAIAAgMIA4AAIAAAMIgPAAQgEAAAAAFIAAA4IBTAAIAAg4QAAgFgEAAIgQAAIAAgMIA5AAIAAAMIgQAAQgDAAAAAFIAAB9QAAAGADAAIAQAAIAAALg");
	this.shape_9.setTransform(-54.275,-1.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-80.5,-14,161,28), null);


(lib.HEADend = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLAMQgFgFAAgHQAAgGAFgFQAFgFAGAAQAHAAAFAFQAFAFAAAGQAAAHgFAFQgFAFgHAAQgGAAgFgFg");
	this.shape.setTransform(92.45,29.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag/BGQgZgbAAgrQAAgqAagbQAagcAoAAQAngBAXAaQAXAZAAApIAAAJIidAAQAAAjAUAWQAUAYAhgBQA4AAAMg1IAPAFQgGAcgVASQgWASgjAAQgpAAgagdgABFgLQAAghgSgTQgRgUgeAAQgeAAgUAUQgTAUgDAgICJAAIAAAAg");
	this.shape_1.setTransform(79.725,21.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhGBgIAAgOIAbAAQAFAAABgIIAAiOQgBgJgFAAIgbAAIAAgOIAJAAQAZAAARgDIAAAtQAOguAmAAQASAAALAKQAJAKAAAOQAAAWgRAAQgGAAgFgEQgEgDAAgGQAAgMAOgCQgDgOgUAAQgYAAgMAYQgMAXAAAnIAABEQAAAIAFAAIAcAAIAAAOg");
	this.shape_2.setTransform(62.5,21.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhKBUQgQgNAAgXQAAgeAfgQQAegQBFgHIAAgKQAAgbgNgNQgNgMgaAAQgpAAgOAXQANADAAAMQAAAOgQAAQgQABgBgUQABgUAWgOQAWgNAgAAQBGgBAABCIAABoQAAAIAEAAIAbAAIAAAOIguAAQgDgRgBgaQgIAVgUANQgTAOgZAAQgbAAgQgPgAgtAJQgaAMAAAaQAAAQAMAKQAMAKAUAAQAdAAATgUQATgWAAggIAAgQQg7AFgaALg");
	this.shape_3.setTransform(45.6,21.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag+BHQgagbAAgsQAAgrAbgbQAbgcApABQAkAAAWASQAXASAAAeQAAAJgFAGQgFAGgHgBQgQAAAAgOQAAgPAQgBQgJgqg3AAQghAAgVAXQgVAWAAAlIAAACQAAAlAUAWQAUAXAiAAQA3ABANg2IAPAFQgHAdgVARQgWASgiAAQgpAAgagcg");
	this.shape_4.setTransform(25.925,21.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAYCDIAAgPIAZAAQAFAAAAgHIAAhrQAAgvgrAAQgcAAgRAaQgTAZAAAsIAAA7QAAAHAFAAIAbAAIAAAPIhTAAIAAgPIAbAAQAFAAAAgHIAAjVQAAgJgFAAIgcAAIAAgOIALAAQAYAAARgDIAAB6QAVg1AvAAQA7AAAAA9IAABtQAAAHAEAAIAcAAIAAAPg");
	this.shape_5.setTransform(-3.125,17.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgIBrQgLgLAAgZIAAiCIgfAAIAAgMIAXgCQAKAAABgKIACgiIAOAAIAAAsIAvAAIAAAOIgvAAIAACCQAAAgAcAAQAIAAAPgEIAAAOQgNAFgNAAQgXAAgKgLg");
	this.shape_6.setTransform(-19.375,19.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgpCDIAAgPIAbAAQAFAAAAgHIAAjVQAAgJgFAAIgbAAIAAgOIAKAAQAZAAAQgDIAADvQAAAHAEAAIAcAAIAAAPg");
	this.shape_7.setTransform(-29.4,17.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhKBUQgRgNAAgXQABgeAfgQQAegQBFgHIAAgKQAAgbgNgNQgNgMgaAAQgpAAgOAXQANADAAAMQAAAOgQAAQgQABAAgUQAAgUAWgOQAWgNAfAAQBHgBAABCIAABoQAAAIAEAAIAbAAIAAAOIguAAQgDgRgBgaQgIAVgUANQgTAOgZAAQgbAAgQgPgAgtAJQgaAMAAAaQAAAQAMAKQAMAKAUAAQAdAAATgUQATgWAAggIAAgQQg7AFgaALg");
	this.shape_8.setTransform(-43.4,21.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag/BGQgZgbAAgrQAAgqAagbQAagcAoAAQAngBAXAaQAXAZAAApIAAAJIidAAQAAAjAUAWQAUAYAhgBQA4AAAMg1IAPAFQgGAcgVASQgWASgjAAQgpAAgagdgABFgLQAAghgSgTQgRgUgeAAQgeAAgUAUQgTAUgDAgICJAAIAAAAg");
	this.shape_9.setTransform(-63.525,21.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAYCDIAAgPIAZAAQAFAAAAgHIAAhrQAAgvgrAAQgcAAgRAaQgTAZAAAsIAAA7QAAAHAFAAIAbAAIAAAPIhTAAIAAgPIAbAAQAFAAAAgHIAAjVQAAgJgFAAIgcAAIAAgOIALAAQAYAAARgDIAAB6QAVg1AvAAQA7AAAAA9IAABtQAAAHAEAAIAcAAIAAAPg");
	this.shape_10.setTransform(-84.075,17.675);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAYBgIAAgOIAZAAQAFAAAAgIIAAhpQAAgwgrAAQgcAAgSAZQgSAbAAArIAAA6QAAAIAFAAIAbAAIAAAOIhUAAIAAgOIAbAAQAFAAAAgIIAAiOQAAgJgFAAIgbAAIAAgOIALAAQAYAAARgDIAAA1QAUg2AwAAQA7AAAAA/IAABqQAAAIAFAAIAbAAIAAAOg");
	this.shape_11.setTransform(74.175,-20.375);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhKBUQgRgNAAgXQABgeAfgQQAegQBFgHIAAgKQAAgbgNgNQgNgMgaAAQgpAAgOAXQANADAAAMQAAAOgQAAQgQAAAAgTQAAgUAWgOQAWgNAfAAQBHAAAABBIAABoQAAAIAEgBIAbAAIAAAPIguAAQgDgRgBgaQgIAVgUANQgTAOgZAAQgbAAgQgPgAgtAJQgaAMAAAaQAAAQAMAKQAMALAUAAQAdgBATgUQATgWAAggIAAgQQg7AFgaALg");
	this.shape_12.setTransform(53.8,-20.15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAYCDIAAgPIAZAAQAFAAAAgHIAAhrQAAgvgrAAQgcAAgRAaQgTAZAAAsIAAA7QAAAHAFAAIAbAAIAAAPIhTAAIAAgPIAbAAQAFAAAAgHIAAjVQAAgJgFAAIgcAAIAAgOIALAAQAYAAARgDIAAB6QAVg1AvAAQA7AAAAA9IAABtQAAAHAEAAIAcAAIAAAPg");
	this.shape_13.setTransform(32.525,-23.825);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgIBrQgLgLAAgZIAAiCIgfAAIAAgMIAXgCQAKAAABgKIACgiIAOAAIAAAsIAvAAIAAAOIgvAAIAACCQAAAgAcAAQAIAAAPgEIAAAOQgNAFgNAAQgXAAgKgLg");
	this.shape_14.setTransform(16.275,-22.175);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag/BGQgZgbAAgrQAAgqAagbQAagcAoAAQAnAAAXAZQAXAZAAApIAAAJIidAAQAAAiAUAXQAUAYAhAAQA4AAAMg2IAPAFQgGAcgVASQgWASgjAAQgpAAgagdgABFgLQAAghgSgUQgRgTgeAAQgeAAgUAUQgTAUgDAgICJAAIAAAAg");
	this.shape_15.setTransform(-7.225,-20.15);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhGBgIAAgOIAbAAQAFAAABgIIAAiOQgBgJgFAAIgbAAIAAgOIAJAAQAZAAARgDIAAAtQAOguAmAAQASAAALAKQAJAKAAAOQAAAWgRAAQgHAAgEgEQgEgDAAgGQAAgMAOgCQgDgOgUAAQgYAAgMAYQgMAXAAAnIAABEQAAAIAFAAIAcAAIAAAOg");
	this.shape_16.setTransform(-24.45,-20.375);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhBBHQgagbAAgsQAAgrAagbQAagbAoAAQApAAAZAbQAZAbAAArQAAAsgZAbQgaAcgpAAQgoAAgZgcgAg0g8QgUAWAAAmIAAABQAAAlAUAXQATAXAhAAQAiAAATgXQAUgXAAglIAAgBQAAgmgUgWQgTgXgiAAQggAAgUAXg");
	this.shape_17.setTransform(-42.15,-20.15);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgLCCIhfjxIAADaQAAAHAFAAIAcAAIAAAPIhRAAIAAgPIAcAAQAFAAAAgHIAAjWQAAgHgFAAIgcAAIAAgPIA/AAIBaDlIBejlIA+AAIAAAPIgbAAQgFAAAAAHIAADWQAAAHAFAAIAbAAIAAAPIhVAAIAAgPIAcAAQAFAAAAgHIAAjcIhkDzg");
	this.shape_18.setTransform(-68.375,-23.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEADend, new cjs.Rectangle(-148.8,-51,297.8,95), null);


(lib.GradHatOUTLINEai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// GradHat-OUTLINE.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AxTimICmBKIgCBAQgDBHAAAkQAAAtCDA5QCHA8B0gEQB9gEBQgkQBWgmAAg+QAAhUgDhEQA5AmAHBrQADA6gIBcQAAAuAOAjQAGASAGAJIASh3IAMB7QAKgdAJgiQAShDgIgVQgIgVgLgKIgKgGQAGg2gGg7QgLh0g3gYICVhiIpwi6ImVDPImIAAAhOi7IYqAA");
	this.shape.setTransform(150,37.9416);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.4,302,76.5);


(lib.GradHatALLai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// GradHat-ALL.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AkVg4QgCgBgCgCQACABADABQAAABAAABQgBgBAAAAIjrCaImti+IimhKIGVjPIJwC6IYqAAAo5jQICPAwQCYA0AoAQQAEABADACIgxAgIgBABAkUg3QADBEAABUQAAA+hWAmQhQAkh9AEQh0AEiHg8QiDg5AAgtQAAgkADhHIAChAAjjhZQA3AXALBxQAGA8gGA5IAKAGQALAKAIAVQAIAVgSBDQgJAigKAdIgMh7IgSB3QgGgJgGgSQgOgjAAguQAKhqgHhAQgKhag0gjAhOi7IiVBiAo5jQQACgQAAgCQAAgOgQAFQgPAFgRAPQgRAQgCAOQgDAQAVAEQAOACAZAHQAAgDABgEQAFgdACgQgAkZg7QgOgIgRgFQgRgEgRgFQg4gPhAgOQhTgTgSAAQgNAAADgbQBHAUCgA3QAfALAiALgAxTimImIAA");
	this.shape.setTransform(150,37.9416);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.4,302,76.5);


(lib.FreshFoodOUTLINEai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FreshFood-OUTLINE.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AXcGPIlWAAIAGgLQAegFgDg4QAAgVgNhCQARgGAGgbQAFgZgFgdQgFgegOgNQgPgQgUANQAngbg5giQg1ghgpACQgKgtgvAHQgaAFgIgCQgQgCgGgVQgHgYggABQgTABgUAKQgUAJgPAOIAAjOIhhhpIgBg2IkhADIAAA2IhoBaIAAKJI8ZAA");
	this.shape.setTransform(150,40.3462);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-2.2,302,83.4);


(lib.FreshFoodALLai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FreshFood-ALL.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,1).p("AOyhEQgFABgGAAQgjACgaALQggghgbAoQgaAnAaAgQgvgCgJAsQgJAsAuAMQgQArAJAOQALARA7ADQAAAMgHAkQgBADABADQg0Adg7AcQh3A4gogCQgugCgTggQgTgfAagSQAWgOgDgRIgIgPQADgBADgBQBYgbASgGQBSgdANgSQAFgHgFgQQgDgJgFgLQgPgcAggVQgWgPAKgYQAKgaAugbQgQgXAegbQACgCACgBQAhgcAlgCQAggBAHAYQAGAVAQACQABAAABAAQADABAGgBQAEAAAFgBQAGgBAIgBQAvgHAKAuQApgCA1AhQA5AhgnAbQAUgNAPAQQAOANAFAeQAFAdgFAZQgGAbgRAGQAAACABACASmEHQADgcgOgnQAIAsADAXQABAKAAAGQADA4geAFQgDAGgDAFQgOAYgdAMQglAOgagXQg7gCgfgHQg4gLALggQgpAIgeAQQgXANgpAgQgoAghEAOQhGAPgNgdQgMgZACgMQABgMAPgIQAVgKBlgjQBaglAegVQALgIACgEQADAWAcAAQgNAcA0ARQA0ASAigaQAPAUAkAGQAlAGAigNQA3gUAFgygAXcFfIlWAAALImHIgBg2IkhADIAAA2IhoBaIAAKJI8ZAAAKRj9IA3iKAMpkeIhhhpAKRj9ICYghIAADNANUD/QAAgBAAgBAKRCrQgCAAgCABQhNAfgrACIAIAcALmCCQgZAQg8AZIAAmo");
	this.shape.setTransform(150,45.1307);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.5,302,91.3);


(lib.DrChildOUTLINEai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// DrChild-OUTLINE.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AaLGUIpggHQgPgDgLgOQAlh1gBgeQgBgrgCgVQgDgjgIgbQgNgpgSgKQgQgCgBgDQgFgTAGgrQAAgEAVgLQAXgMAKgnQAeh0gkguQgLgPgRgGQgPgEgBgCQgbgohoAhQhkAfgRAmQgDAHASANQgIARABAYQAAACAGAgQADAVgEAOQAAABgJAPQgFAKAFAGQABACAIACQAJACACACQADADADAPQADAJAEAOQAFALAMAHQAGADAcACQAWACAFAMQACAEADANQACAKAFAFQgJAHgCACQgLALgKAXQgEANgFAOQgIgGgeADQglADgEgBQgVgCgNAGQgTAIgRAZQAEgYABgOQABgagQgCQgKgBgDgBQgGAAgFABQgfAHALgJQAUgQAAgBQAAgHgNgNQgOgOgDgEQgHgJgXgUQgSgQgHgPQgLgagKgIQgFgEghgPIgMgGQACgQgBgHQgBgJgEgGQgEgHgFgBIgCgYQgDgUAJgSQAPggACgFQAFgRgFgUQgEgUgNgFQgIgDgdANIgDgHQAggtgngQQABgHgCgIQgIgjgjgdQgigbgjgEQgWgDgoAGQgrAGgTALQhLAqgGBuQgCAnAHAlQAHAgAIAJQAfAiAcgaQACAIAFALQgNALgeAeQgYAYgFAEQgmAWgKBiQgCAVAGAOQAEAIAMAMQAEArAJAhQALAsATAbQAUAdANAqQAEANAXAlQAUAgAAANQgQABrIgBQhlAAh0AAQurgBgsAB");
	this.shape.setTransform(167.4704,44.2755);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.5,337,89.9);


(lib.DrChildALLai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// DrChild-ALL.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AQREyQAOgtAHgbQAQg3gBgWQgBgqgCgVQgDgkgIgaQgNgogSgKQgQgDgBgDQgFgSAGgtQAAgEAVgKQAXgMAKgoQAeh0gkguQgLgOgRgHQgPgEgBgBQgbgohoAgQhkAggRAlQgDAHATANQAEAEAHAEQAkAYAEAFQAMAPALAaQAIAVACABQAJADAOgUQAPgTAMADQAVAGAIAoQAHAlAQAAQAHAAATABQARABAFgEQAQgOACgCQAGgHAFgOQAVg9gOg5QgNgxgYgLQghgOgaAAQgmgBg8AZQgeANgFACQgUALgKAMQgHAJgEAKQgJATABAWQAAADAGAgQADAUgEAPQAAABgJAPQgFAJAFAHQABACAIACQAJACACABQADAEADAPQADAJAEAOQAFAMAMAGQAGADAcADQAWACAFAMQACAEADANQACAKAFAEQAAAAAAAAQAJAJAYgNQAtgYgkAKQgaAHgQALQgGAEgFAEQgLAMgKAXQgEAMgFAPQgIgGgeACQglADgEAAQgVgCgNAFQgTAIgRAZQAEgXABgOQABgagQgCQgKgCgDAAQgGgBgFACQgfAHALgJQAUgRAAgBQAAgGgNgOQgOgNgDgEQgHgJgXgTQgSgQgHgQQgLgagKgIQgFgFghgOQgHgEgFgDQgSgLgLgGQgYgNgDAPQgBACgFA7QgTgBgJgCQgKgCgCgHQgBgBgBgCQgCgIgCgDQgMgOgIgDQgJgFgPACQgTACgZgEQgKgTgDgQQAAgEgBgEQgLgGgIgIQgHgJgEgEQgFgGgIgCQgIgCgbAYQgDgHgCgHQgBgDgBgDQgNAMgMAAQgQABgSgUQgIgJgHghQgHglACgnQAGhtBLgrQATgKArgGQAogGAWADQAjAEAiAbQAjAcAIAkQACAIgBAGQgBAKgJAFQgLAGgcABQgTAAgkAUQgjATgQASQgHAIAYgFQAigGAKACQAVAFAGAAQAPABABgJQABgJAOgOQAOgOAJgBQAJgBADAKQAFAHAEAJQABADABADQAEgBAFgCQAWgJAGADQANAFAEAUQAFATgFASQgCAFgPAgQgJASADATQACAPAAAJQABAVgHgJIgBgEQABgKAGACQACABABABQAJAGACAPQABAKgCANQgBAHgCAJQgDANgHAZQgHAkAPAlQAJAWAZAtQA6BzAeAWQgSACgsg6Qgsg7ADgTQADgMgIgKQgOgPgMgRQgFgGgLgvQgKgpgNgDQgDAAgDAAQgBAFAAAGQgGA3gMAHQgNAJhIhWQgTgXgLgVQgKgCgLgCQgtgKgNgSQgHgKgGgOQgJAHgLALQgyAxgCABQgmAXgKBjQgDAeAUAUQACACABABQADAmAKAmQALAtATAaQAUAdANAqQAEAOAXAlQAUAgAAANQgTABuegBQurgBgsABAQREyQgKgMgBgTQgDgkgIgzQgIg1gHgUQgEgJgIARQgIARgGAdQgQBOAWAlQgPABhOAqQhBAkgHgSQgBgDgBgDQgDgKABgLQAAgJAEgVQAEgVANgZQANgZAEgVQABgIgEgeQgEgZAIgNQAIgMAHgMQAFgEADASQADAPADAeQACAbAFARQAEAPARAjQAMAWgHAGQgpAeg6AgQgkAUgqAVQgnAUgPAMQgcAWgDAdQACgEAKgGQABgBABAAQgSAXALASQAFgEAIgPQAIgRAEgFQgRAdAFAfQAAACACgCQAFgDAHgMQAFgHAIgNQgJAXgBAKQAAACACABQACABACgCQAHgMAXgUQAHgHAPgHQAQgGAGgGQAEgEAKgTQAIgSAIgEQANgJBAgLQBAgMAMgHQAFgEAqgRQAdgMAGgOQADgJACgIgAMJC3QgCAAgDAAAMJC3QAOAAAeAGQAIABACABQAGACABAFQADAIgEAGQgFAHgGgDQgIgEgQgBQgSgCgHAFQACABAPACQAOADADADQAIAJgPAGIgFABQAAAAALgBQABATgdAQQgTALgNABQgJAAgagGQgMgCgWAAQgOgBgbALQhiAmg8AAQgXgBgIgBQgKAAgGAGQgIAPgDAEQgEAHgCgUQgFgfBEhZQAhgBA1AAQA8gCAogPQAKgEAXgUQAWgTAKgDQAIgBAPABQAPABAHgBQAWgEAPADQAUAFgBAQQgBAJg3ADgAaLFIIpggGQgJgCgJgGQgEgEgEgEAHPmSQAZALgFAYQgCAOgKANQgFAHgHAHQgBABgBABAHLlGQAEgDAKgFQAMAjgJA5QgIAygOATQgSAagmgJQgqgJgSgGQgRgEgMgHQgHgkgHgSQgEgJgRgLQgUgOgEgEQgHgJAHgMQAKgPgBgKQgCgZAfgMQAKgEAqgHQANgDATgUQASgTARAAQAlAAATAIAGhhnQgBgGACgIQAHAAACAEQABAEgFAEQgEADgCgBgADgjXQgIgYAJgKQAKgLAHAFQAGAGgGAJQgJAQgJAJgAHhDXQADgDACgEQAJgKgTACQgaADgHgIQgCgDACgPQADgNgHgCQgGgBgMAPQgLAPgFgFQgJgJAGgMQAIgSgBgIQgDgVgNgZQgOgbgQgKQgQgLgLgUQgLgYgIgNQgQgjgJgSQgPgfgSgRQgNgNgZAAQgZABgSANQgqAegFBRQgCAYACAZQAXAYAFAYQAKAsAZAhQALAPAxAxQARARAlAnQAjAhAdALQARAHAHgIQAEgEAJgXQADgKAIgbQAGgYAFgNQAFgNAHgDQAFgDAPAAQAIgBAKAAgAKcHEQAHgFABgF");
	this.shape.setTransform(167.4704,51.8167);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.5,337,104.7);


(lib.covwhiteRGBai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// co-v-white-RGB.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(526.5006,189.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(271.9321,70.8329);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(494.55,205.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(438.825,205.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(386.35,217.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(336.35,205.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(296.35,205.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(236.525,200.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(171.8,205.55);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(132.5,205.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(85.3,205.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(28.225,200.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0.1,533.9,251.3);


(lib.BUTTONbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnmC7Qg1AAgmgmQglglAAg1IAAh1QAAg1AlglQAmgmA1AAIPNAAQA1AAAmAmQAlAlAAA1IAAB1QAAA1glAlQgmAmg1AAg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-18.6,123,37.3);


(lib.HousingOUTLINE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.HousingOUTLINEai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,-0.05,1,1,0,0,0,150.5,32.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.HousingOUTLINE, new cjs.Rectangle(-151,-32.7,302,65.5), null);


(lib.HousingALL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.HousingALLai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0,1,1,0,0,0,150.5,39.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.HousingALL, new cjs.Rectangle(-151,-40.1,302,80.30000000000001), null);


(lib.GradHatOUTLINE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.GradHatOUTLINEai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0.75,1,1,0,0,0,150,37.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.GradHatOUTLINE, new cjs.Rectangle(-151,-37.3,302,76.6), null);


(lib.GradHatALL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.GradHatALLai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0.75,1,1,0,0,0,150,37.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.GradHatALL, new cjs.Rectangle(-151,-37.3,302,76.6), null);


(lib.FreshFoodOUTLINE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.FreshFoodOUTLINEai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,-0.75,1,1,0,0,0,150,39.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-151,-42.5,302,83.4);


(lib.FreshFoodALL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.FreshFoodALLai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0,1,1,0,0,0,150,45.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-151,-45.6,302,91.30000000000001);


(lib.DrChildOUTLINE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.DrChildOUTLINEai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.05,0.35,1,1,0,0,0,167.5,44.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.DrChildOUTLINE, new cjs.Rectangle(-168.4,-44.7,336.9,89.80000000000001), null);


(lib.DrChildALL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.DrChildALLai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.05,7,1,1,0,0,0,167.5,51.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.DrChildALL, new cjs.Rectangle(-168.4,-45.3,336.9,104.69999999999999), null);


(lib.covwhiteeps = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.covwhiteRGBai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.26,0.26,0,0,0,266.8,125.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69.3,-32.6,138.8,65.30000000000001);


(lib.BUTTON = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("AgaA1IAAgQIAHAAIADgBIAAgFIAAgVIgagpQgDgFgEAAIgEAAIAAgQIA2AAIAAAQIgEAAQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAACABADIAMAUIAMgWQADgFgGAAIgGAAIAAgQIAsAAIAAAQIgFAAQgEAAgEAFIgZAoIAAAWQAAAFAEABIAHAAIAAAQg");
	this.shape.setTransform(31.525,7.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_1.setTransform(21.625,7.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAAKAIQALAHAAARQAAASgKAGQgKAIgXAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgEgEQgDgEgIAAIgHAAg");
	this.shape_2.setTransform(12.35,7.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAALAIQAKAHAAARQAAASgKAGQgLAIgWAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgDgEQgEgEgIAAIgHAAg");
	this.shape_3.setTransform(2.6,7.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_4.setTransform(-7.975,7.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaABQgZgBgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAJQAFAGAKABQALgBAFgGQAFgJAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_5.setTransform(-22.575,7.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF8300").s().p("AgbA1IAAgQIAHAAQAEgBAAgFIAAhDIgCAAIgKABQgCABgBAFIgCAIIgPAAIAAgfIBhAAIAAAfIgPAAIgBgIQgBgEgEgCIgKgBIgCAAIAABDQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAAAAAAAQABAAAAAAQABABAAAAIAHAAIAAAQg");
	this.shape_6.setTransform(-33.15,7.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF8300").s().p("AASA1IgSg2IgSA2IgaAAIgZhTQgCgGgEAAIgFAAIAAgQIAzAAIAAAQIgEAAIgEABIABAEIANArIANgrQACgFgFAAIgFAAIAAgQIAwAAIAAAQIgFAAQgEAAACAFIAOAsIANgsQABgFgEAAIgGAAIAAgQIAoAAIAAAQIgFAAIgEABIgCAFIgaBTg");
	this.shape_7.setTransform(38.15,-6.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaAAQgZAAgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAIQAFAIAKAAQALAAAFgIQAFgIAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_8.setTransform(24.525,-6.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF8300").s().p("AAHA1IAAgQIAFAAQAEgBAAgFIAAgYIgfAAIAAAYQAAAFAEABIAFAAIAAAQIg0AAIAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgGAAIAAgQIA0AAIAAAQIgFAAQgEAAAAAFIAAAYIAfAAIAAgYQAAgFgEAAIgFAAIAAgQIA0AAIAAAQIgGAAQgEAAAAAFIAAA+QAAAFAEABIAGAAIAAAQg");
	this.shape_9.setTransform(13.075,-6.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF8300").s().p("AAXA1IgxhEIAAAuQAAAFAEABIAHAAIAAAQIgpAAIAAgQIAHAAQAEgBAAgFIAAg+QAAgFgEAAIgHAAIAAgQIArAAIAnA3IAAgiQAAgFgDAAIgHAAIAAgQIApAAIAAAQIgHAAQgEAAAAAFIAABUg");
	this.shape_10.setTransform(-1.625,-6.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF8300").s().p("AAcA1QgRAAgCgcQgCgJgCgDQgDgFgGABIgFAAIAAAWQAAAFADABIAGAAIAAAQIg0AAIAAgQIAFAAQAFgBAAgFIAAg+QAAgFgFAAIgFAAIAAgQIA8AAQAnAAAAAdQgBAVgWADQALAEAFAGQAEAHABALQAAAIAGAAIACAAIAAAQgAgJgEIAGAAQAIAAAFgEQADgDAAgKQAAgHgDgEQgEgEgHAAIgIAAg");
	this.shape_11.setTransform(-12.4,-6.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_12.setTransform(-23.375,-6.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF8300").s().p("AguA1IAAgQIAGAAQAEgBAAgFIAAg+QAAgFgEAAIgGAAIAAgQIBcAAIAAAeIgQAAIgDgIQgCgEgCgBIgJgBIgRAAIAAAcIAIAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAIABgGIAAgDIAPAAIAAAlIgPAAIAAgEQAAgIgFABIgIAAIAAAdIASAAQAHAAACgBQACgBADgFIACgHIAQAAIAAAeg");
	this.shape_13.setTransform(-33.925,-6.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_14.setTransform(-43.125,-6.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.instance = new lib.BUTTONbkgd();
	this.instance.parent = this;
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_3
	this.instance_1 = new lib.Buttonshad();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-69,-27,0.5544,0.5544);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-69,-27,143.6,59.3), null);


// stage content:
(lib.CO_MoreThan_300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_303 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(303).call(this.frame_303).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A3WzcMAutAAAMAAAAm5MgutAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(304));

	// RULE
	this.instance = new lib.RULE();
	this.instance.parent = this;
	this.instance.setTransform(-147.9,163.5,1.0111,1,0,0,0,0.1,0.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(232).to({_off:false},0).to({x:150.1},14,cjs.Ease.quintIn).wait(58));

	// LOGO
	this.instance_1 = new lib.covwhiteeps("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(353.5,332.5,1,1,0,0,0,266.9,125.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(278).to({_off:false},0).to({alpha:1},10).wait(16));

	// BUTTON
	this.instance_2 = new lib.BUTTON();
	this.instance_2.parent = this;
	this.instance_2.setTransform(226.05,206.95);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(278).to({_off:false},0).to({regX:0.1,regY:0.1,scaleX:0.85,scaleY:0.85,x:226.1,alpha:1},10).wait(16));

	// HEAD-end
	this.instance_3 = new lib.HEADend();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,72.3,1,1,0,0,0,0,-15);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(242).to({_off:false},0).to({alpha:1},10).wait(52));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AgSTiMAAAgnDIAlAAMAAAAnDg");
	var mask_graphics_1 = new cjs.Graphics().p("AhCTiMAAAgnDICFAAMAAAAnDg");
	var mask_graphics_2 = new cjs.Graphics().p("AhyTiMAAAgnDIDlAAMAAAAnDg");
	var mask_graphics_3 = new cjs.Graphics().p("AiiTiMAAAgnDIFFAAMAAAAnDg");
	var mask_graphics_4 = new cjs.Graphics().p("AjSTiMAAAgnDIGlAAMAAAAnDg");
	var mask_graphics_5 = new cjs.Graphics().p("AkBTiMAAAgnDIIDAAMAAAAnDg");
	var mask_graphics_6 = new cjs.Graphics().p("AkxTiMAAAgnDIJjAAMAAAAnDg");
	var mask_graphics_7 = new cjs.Graphics().p("AlhTiMAAAgnDILDAAMAAAAnDg");
	var mask_graphics_8 = new cjs.Graphics().p("AmRTiMAAAgnDIMjAAMAAAAnDg");
	var mask_graphics_9 = new cjs.Graphics().p("AnATiMAAAgnDIOBAAMAAAAnDg");
	var mask_graphics_10 = new cjs.Graphics().p("AnwTiMAAAgnDIPhAAMAAAAnDg");
	var mask_graphics_11 = new cjs.Graphics().p("AogTiMAAAgnDIRBAAMAAAAnDg");
	var mask_graphics_12 = new cjs.Graphics().p("ApPTiMAAAgnDISgAAMAAAAnDg");
	var mask_graphics_13 = new cjs.Graphics().p("Ap/TiMAAAgnDIT/AAMAAAAnDg");
	var mask_graphics_14 = new cjs.Graphics().p("AqvTiMAAAgnDIVfAAMAAAAnDg");
	var mask_graphics_15 = new cjs.Graphics().p("ArfTiMAAAgnDIW/AAMAAAAnDg");
	var mask_graphics_16 = new cjs.Graphics().p("AsOTiMAAAgnDIYeAAMAAAAnDg");
	var mask_graphics_17 = new cjs.Graphics().p("As+TiMAAAgnDIZ+AAMAAAAnDg");
	var mask_graphics_18 = new cjs.Graphics().p("AtuTiMAAAgnDIbdAAMAAAAnDg");
	var mask_graphics_19 = new cjs.Graphics().p("AueTiMAAAgnDIc9AAMAAAAnDg");
	var mask_graphics_20 = new cjs.Graphics().p("AvNTiMAAAgnDIecAAMAAAAnDg");
	var mask_graphics_21 = new cjs.Graphics().p("Av9TiMAAAgnDIf8AAMAAAAnDg");
	var mask_graphics_22 = new cjs.Graphics().p("AwtTiMAAAgnDMAhcAAAMAAAAnDg");
	var mask_graphics_23 = new cjs.Graphics().p("AxcTiMAAAgnDMAi6AAAMAAAAnDg");
	var mask_graphics_24 = new cjs.Graphics().p("AyMTiMAAAgnDMAkaAAAMAAAAnDg");
	var mask_graphics_25 = new cjs.Graphics().p("Ay8TiMAAAgnDMAl6AAAMAAAAnDg");
	var mask_graphics_26 = new cjs.Graphics().p("AzsTiMAAAgnDMAnaAAAMAAAAnDg");
	var mask_graphics_27 = new cjs.Graphics().p("A0bTiMAAAgnDMAo4AAAMAAAAnDg");
	var mask_graphics_28 = new cjs.Graphics().p("A1LTiMAAAgnDMAqYAAAMAAAAnDg");
	var mask_graphics_29 = new cjs.Graphics().p("A17TiMAAAgnDMAr4AAAMAAAAnDg");
	var mask_graphics_30 = new cjs.Graphics().p("A2rTiMAAAgnDMAtYAAAMAAAAnDg");
	var mask_graphics_31 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:1.9003,y:125}).wait(1).to({graphics:mask_graphics_1,x:6.6818,y:125}).wait(1).to({graphics:mask_graphics_2,x:11.4632,y:125}).wait(1).to({graphics:mask_graphics_3,x:16.2447,y:125}).wait(1).to({graphics:mask_graphics_4,x:21.0261,y:125}).wait(1).to({graphics:mask_graphics_5,x:25.8075,y:125}).wait(1).to({graphics:mask_graphics_6,x:30.589,y:125}).wait(1).to({graphics:mask_graphics_7,x:35.3704,y:125}).wait(1).to({graphics:mask_graphics_8,x:40.1519,y:125}).wait(1).to({graphics:mask_graphics_9,x:44.9317,y:125}).wait(1).to({graphics:mask_graphics_10,x:49.7102,y:125}).wait(1).to({graphics:mask_graphics_11,x:54.4888,y:125}).wait(1).to({graphics:mask_graphics_12,x:59.2673,y:125}).wait(1).to({graphics:mask_graphics_13,x:64.0458,y:125}).wait(1).to({graphics:mask_graphics_14,x:68.8243,y:125}).wait(1).to({graphics:mask_graphics_15,x:73.6028,y:125}).wait(1).to({graphics:mask_graphics_16,x:78.3814,y:125}).wait(1).to({graphics:mask_graphics_17,x:83.1599,y:125}).wait(1).to({graphics:mask_graphics_18,x:87.9384,y:125}).wait(1).to({graphics:mask_graphics_19,x:92.7169,y:125}).wait(1).to({graphics:mask_graphics_20,x:97.4954,y:125}).wait(1).to({graphics:mask_graphics_21,x:102.274,y:125}).wait(1).to({graphics:mask_graphics_22,x:107.0525,y:125}).wait(1).to({graphics:mask_graphics_23,x:111.831,y:125}).wait(1).to({graphics:mask_graphics_24,x:116.6095,y:125}).wait(1).to({graphics:mask_graphics_25,x:121.388,y:125}).wait(1).to({graphics:mask_graphics_26,x:126.1666,y:125}).wait(1).to({graphics:mask_graphics_27,x:130.9451,y:125}).wait(1).to({graphics:mask_graphics_28,x:135.7236,y:125}).wait(1).to({graphics:mask_graphics_29,x:140.5021,y:125}).wait(1).to({graphics:mask_graphics_30,x:145.2806,y:125}).wait(1).to({graphics:mask_graphics_31,x:149.925,y:125}).wait(15).to({graphics:null,x:0,y:0}).wait(258));

	// DrChild-OUTLINE
	this.instance_4 = new lib.DrChildOUTLINE();
	this.instance_4.parent = this;
	this.instance_4.setTransform(167,68.4,1,1,0,0,0,0,0.4);

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(31).to({alpha:0},15).to({_off:true},1).wait(257));

	// DrChild-ALL
	this.instance_5 = new lib.DrChildALL();
	this.instance_5.parent = this;
	this.instance_5.setTransform(167,75,1,1,0,0,0,0,7);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(31).to({_off:false},0).to({alpha:1},15).wait(62).to({x:468},12,cjs.Ease.quintIn).to({_off:true},20).wait(164));

	// HEAD1
	this.instance_6 = new lib.HEAD1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(89,83);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(31).to({_off:false},0).to({alpha:1},8).wait(75).to({x:365},12,cjs.Ease.quintIn).to({_off:true},1).wait(177));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_47 = new cjs.Graphics().p("AgSTiMAAAgnDIAlAAMAAAAnDg");
	var mask_1_graphics_48 = new cjs.Graphics().p("AhCTiMAAAgnDICFAAMAAAAnDg");
	var mask_1_graphics_49 = new cjs.Graphics().p("AhyTiMAAAgnDIDlAAMAAAAnDg");
	var mask_1_graphics_50 = new cjs.Graphics().p("AiiTiMAAAgnDIFFAAMAAAAnDg");
	var mask_1_graphics_51 = new cjs.Graphics().p("AjSTiMAAAgnDIGlAAMAAAAnDg");
	var mask_1_graphics_52 = new cjs.Graphics().p("AkBTiMAAAgnDIIDAAMAAAAnDg");
	var mask_1_graphics_53 = new cjs.Graphics().p("AkxTiMAAAgnDIJjAAMAAAAnDg");
	var mask_1_graphics_54 = new cjs.Graphics().p("AlhTiMAAAgnDILDAAMAAAAnDg");
	var mask_1_graphics_55 = new cjs.Graphics().p("AmRTiMAAAgnDIMjAAMAAAAnDg");
	var mask_1_graphics_56 = new cjs.Graphics().p("AnATiMAAAgnDIOBAAMAAAAnDg");
	var mask_1_graphics_57 = new cjs.Graphics().p("AnwTiMAAAgnDIPhAAMAAAAnDg");
	var mask_1_graphics_58 = new cjs.Graphics().p("AogTiMAAAgnDIRBAAMAAAAnDg");
	var mask_1_graphics_59 = new cjs.Graphics().p("ApPTiMAAAgnDISgAAMAAAAnDg");
	var mask_1_graphics_60 = new cjs.Graphics().p("Ap/TiMAAAgnDIT/AAMAAAAnDg");
	var mask_1_graphics_61 = new cjs.Graphics().p("AqvTiMAAAgnDIVfAAMAAAAnDg");
	var mask_1_graphics_62 = new cjs.Graphics().p("ArfTiMAAAgnDIW/AAMAAAAnDg");
	var mask_1_graphics_63 = new cjs.Graphics().p("AsOTiMAAAgnDIYeAAMAAAAnDg");
	var mask_1_graphics_64 = new cjs.Graphics().p("As+TiMAAAgnDIZ+AAMAAAAnDg");
	var mask_1_graphics_65 = new cjs.Graphics().p("AtuTiMAAAgnDIbdAAMAAAAnDg");
	var mask_1_graphics_66 = new cjs.Graphics().p("AueTiMAAAgnDIc9AAMAAAAnDg");
	var mask_1_graphics_67 = new cjs.Graphics().p("AvNTiMAAAgnDIecAAMAAAAnDg");
	var mask_1_graphics_68 = new cjs.Graphics().p("Av9TiMAAAgnDIf8AAMAAAAnDg");
	var mask_1_graphics_69 = new cjs.Graphics().p("AwtTiMAAAgnDMAhcAAAMAAAAnDg");
	var mask_1_graphics_70 = new cjs.Graphics().p("AxcTiMAAAgnDMAi6AAAMAAAAnDg");
	var mask_1_graphics_71 = new cjs.Graphics().p("AyMTiMAAAgnDMAkaAAAMAAAAnDg");
	var mask_1_graphics_72 = new cjs.Graphics().p("Ay8TiMAAAgnDMAl6AAAMAAAAnDg");
	var mask_1_graphics_73 = new cjs.Graphics().p("AzsTiMAAAgnDMAnaAAAMAAAAnDg");
	var mask_1_graphics_74 = new cjs.Graphics().p("A0bTiMAAAgnDMAo4AAAMAAAAnDg");
	var mask_1_graphics_75 = new cjs.Graphics().p("A1LTiMAAAgnDMAqYAAAMAAAAnDg");
	var mask_1_graphics_76 = new cjs.Graphics().p("A17TiMAAAgnDMAr4AAAMAAAAnDg");
	var mask_1_graphics_77 = new cjs.Graphics().p("A2rTiMAAAgnDMAtYAAAMAAAAnDg");
	var mask_1_graphics_78 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(47).to({graphics:mask_1_graphics_47,x:1.9003,y:125}).wait(1).to({graphics:mask_1_graphics_48,x:6.6818,y:125}).wait(1).to({graphics:mask_1_graphics_49,x:11.4632,y:125}).wait(1).to({graphics:mask_1_graphics_50,x:16.2447,y:125}).wait(1).to({graphics:mask_1_graphics_51,x:21.0261,y:125}).wait(1).to({graphics:mask_1_graphics_52,x:25.8075,y:125}).wait(1).to({graphics:mask_1_graphics_53,x:30.589,y:125}).wait(1).to({graphics:mask_1_graphics_54,x:35.3704,y:125}).wait(1).to({graphics:mask_1_graphics_55,x:40.1519,y:125}).wait(1).to({graphics:mask_1_graphics_56,x:44.9317,y:125}).wait(1).to({graphics:mask_1_graphics_57,x:49.7102,y:125}).wait(1).to({graphics:mask_1_graphics_58,x:54.4888,y:125}).wait(1).to({graphics:mask_1_graphics_59,x:59.2673,y:125}).wait(1).to({graphics:mask_1_graphics_60,x:64.0458,y:125}).wait(1).to({graphics:mask_1_graphics_61,x:68.8243,y:125}).wait(1).to({graphics:mask_1_graphics_62,x:73.6028,y:125}).wait(1).to({graphics:mask_1_graphics_63,x:78.3814,y:125}).wait(1).to({graphics:mask_1_graphics_64,x:83.1599,y:125}).wait(1).to({graphics:mask_1_graphics_65,x:87.9384,y:125}).wait(1).to({graphics:mask_1_graphics_66,x:92.7169,y:125}).wait(1).to({graphics:mask_1_graphics_67,x:97.4954,y:125}).wait(1).to({graphics:mask_1_graphics_68,x:102.274,y:125}).wait(1).to({graphics:mask_1_graphics_69,x:107.0525,y:125}).wait(1).to({graphics:mask_1_graphics_70,x:111.831,y:125}).wait(1).to({graphics:mask_1_graphics_71,x:116.6095,y:125}).wait(1).to({graphics:mask_1_graphics_72,x:121.388,y:125}).wait(1).to({graphics:mask_1_graphics_73,x:126.1666,y:125}).wait(1).to({graphics:mask_1_graphics_74,x:130.9451,y:125}).wait(1).to({graphics:mask_1_graphics_75,x:135.7236,y:125}).wait(1).to({graphics:mask_1_graphics_76,x:140.5021,y:125}).wait(1).to({graphics:mask_1_graphics_77,x:145.2806,y:125}).wait(1).to({graphics:mask_1_graphics_78,x:149.925,y:125}).wait(15).to({graphics:null,x:0,y:0}).wait(211));

	// Housing-OUTLINE
	this.instance_7 = new lib.HousingOUTLINE();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150.5,175.7);
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(47).to({_off:false},0).wait(31).to({alpha:0},15).to({_off:true},1).wait(210));

	// Housing-ALL
	this.instance_8 = new lib.HousingALL();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150.5,183.05);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(78).to({_off:false},0).to({alpha:1},15).wait(32).to({x:451},14,cjs.Ease.quintIn).to({_off:true},1).wait(164));

	// HEAD2
	this.instance_9 = new lib.HEAD2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(196,186);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(78).to({_off:false},0).to({alpha:1},8).wait(32).to({x:349},14,cjs.Ease.quintIn).to({_off:true},1).wait(171));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_114 = new cjs.Graphics().p("AgSTiMAAAgnDIAlAAMAAAAnDg");
	var mask_2_graphics_115 = new cjs.Graphics().p("AhCTiMAAAgnDICFAAMAAAAnDg");
	var mask_2_graphics_116 = new cjs.Graphics().p("AhyTiMAAAgnDIDlAAMAAAAnDg");
	var mask_2_graphics_117 = new cjs.Graphics().p("AiiTiMAAAgnDIFFAAMAAAAnDg");
	var mask_2_graphics_118 = new cjs.Graphics().p("AjSTiMAAAgnDIGlAAMAAAAnDg");
	var mask_2_graphics_119 = new cjs.Graphics().p("AkBTiMAAAgnDIIDAAMAAAAnDg");
	var mask_2_graphics_120 = new cjs.Graphics().p("AkxTiMAAAgnDIJjAAMAAAAnDg");
	var mask_2_graphics_121 = new cjs.Graphics().p("AlhTiMAAAgnDILDAAMAAAAnDg");
	var mask_2_graphics_122 = new cjs.Graphics().p("AmRTiMAAAgnDIMjAAMAAAAnDg");
	var mask_2_graphics_123 = new cjs.Graphics().p("AnATiMAAAgnDIOBAAMAAAAnDg");
	var mask_2_graphics_124 = new cjs.Graphics().p("AnwTiMAAAgnDIPhAAMAAAAnDg");
	var mask_2_graphics_125 = new cjs.Graphics().p("AogTiMAAAgnDIRBAAMAAAAnDg");
	var mask_2_graphics_126 = new cjs.Graphics().p("ApPTiMAAAgnDISgAAMAAAAnDg");
	var mask_2_graphics_127 = new cjs.Graphics().p("Ap/TiMAAAgnDIT/AAMAAAAnDg");
	var mask_2_graphics_128 = new cjs.Graphics().p("AqvTiMAAAgnDIVfAAMAAAAnDg");
	var mask_2_graphics_129 = new cjs.Graphics().p("ArfTiMAAAgnDIW/AAMAAAAnDg");
	var mask_2_graphics_130 = new cjs.Graphics().p("AsOTiMAAAgnDIYeAAMAAAAnDg");
	var mask_2_graphics_131 = new cjs.Graphics().p("As+TiMAAAgnDIZ+AAMAAAAnDg");
	var mask_2_graphics_132 = new cjs.Graphics().p("AtuTiMAAAgnDIbdAAMAAAAnDg");
	var mask_2_graphics_133 = new cjs.Graphics().p("AueTiMAAAgnDIc9AAMAAAAnDg");
	var mask_2_graphics_134 = new cjs.Graphics().p("AvNTiMAAAgnDIecAAMAAAAnDg");
	var mask_2_graphics_135 = new cjs.Graphics().p("Av9TiMAAAgnDIf8AAMAAAAnDg");
	var mask_2_graphics_136 = new cjs.Graphics().p("AwtTiMAAAgnDMAhcAAAMAAAAnDg");
	var mask_2_graphics_137 = new cjs.Graphics().p("AxcTiMAAAgnDMAi6AAAMAAAAnDg");
	var mask_2_graphics_138 = new cjs.Graphics().p("AyMTiMAAAgnDMAkaAAAMAAAAnDg");
	var mask_2_graphics_139 = new cjs.Graphics().p("Ay8TiMAAAgnDMAl6AAAMAAAAnDg");
	var mask_2_graphics_140 = new cjs.Graphics().p("AzsTiMAAAgnDMAnaAAAMAAAAnDg");
	var mask_2_graphics_141 = new cjs.Graphics().p("A0bTiMAAAgnDMAo4AAAMAAAAnDg");
	var mask_2_graphics_142 = new cjs.Graphics().p("A1LTiMAAAgnDMAqYAAAMAAAAnDg");
	var mask_2_graphics_143 = new cjs.Graphics().p("A17TiMAAAgnDMAr4AAAMAAAAnDg");
	var mask_2_graphics_144 = new cjs.Graphics().p("A2rTiMAAAgnDMAtYAAAMAAAAnDg");
	var mask_2_graphics_145 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(114).to({graphics:mask_2_graphics_114,x:1.9003,y:125}).wait(1).to({graphics:mask_2_graphics_115,x:6.6818,y:125}).wait(1).to({graphics:mask_2_graphics_116,x:11.4632,y:125}).wait(1).to({graphics:mask_2_graphics_117,x:16.2447,y:125}).wait(1).to({graphics:mask_2_graphics_118,x:21.0261,y:125}).wait(1).to({graphics:mask_2_graphics_119,x:25.8075,y:125}).wait(1).to({graphics:mask_2_graphics_120,x:30.589,y:125}).wait(1).to({graphics:mask_2_graphics_121,x:35.3704,y:125}).wait(1).to({graphics:mask_2_graphics_122,x:40.1519,y:125}).wait(1).to({graphics:mask_2_graphics_123,x:44.9317,y:125}).wait(1).to({graphics:mask_2_graphics_124,x:49.7102,y:125}).wait(1).to({graphics:mask_2_graphics_125,x:54.4888,y:125}).wait(1).to({graphics:mask_2_graphics_126,x:59.2673,y:125}).wait(1).to({graphics:mask_2_graphics_127,x:64.0458,y:125}).wait(1).to({graphics:mask_2_graphics_128,x:68.8243,y:125}).wait(1).to({graphics:mask_2_graphics_129,x:73.6028,y:125}).wait(1).to({graphics:mask_2_graphics_130,x:78.3814,y:125}).wait(1).to({graphics:mask_2_graphics_131,x:83.1599,y:125}).wait(1).to({graphics:mask_2_graphics_132,x:87.9384,y:125}).wait(1).to({graphics:mask_2_graphics_133,x:92.7169,y:125}).wait(1).to({graphics:mask_2_graphics_134,x:97.4954,y:125}).wait(1).to({graphics:mask_2_graphics_135,x:102.274,y:125}).wait(1).to({graphics:mask_2_graphics_136,x:107.0525,y:125}).wait(1).to({graphics:mask_2_graphics_137,x:111.831,y:125}).wait(1).to({graphics:mask_2_graphics_138,x:116.6095,y:125}).wait(1).to({graphics:mask_2_graphics_139,x:121.388,y:125}).wait(1).to({graphics:mask_2_graphics_140,x:126.1666,y:125}).wait(1).to({graphics:mask_2_graphics_141,x:130.9451,y:125}).wait(1).to({graphics:mask_2_graphics_142,x:135.7236,y:125}).wait(1).to({graphics:mask_2_graphics_143,x:140.5021,y:125}).wait(1).to({graphics:mask_2_graphics_144,x:145.2806,y:125}).wait(1).to({graphics:mask_2_graphics_145,x:149.925,y:125}).wait(15).to({graphics:null,x:0,y:0}).wait(144));

	// FreshFood-OUTLINE
	this.instance_10 = new lib.FreshFoodOUTLINE();
	this.instance_10.parent = this;
	this.instance_10.setTransform(150,68.5,1,1,0,0,0,0,-0.8);
	this.instance_10._off = true;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(114).to({_off:false},0).wait(31).to({alpha:0},15).to({_off:true},1).wait(143));

	// FreshFood-ALL
	this.instance_11 = new lib.FreshFoodALL();
	this.instance_11.parent = this;
	this.instance_11.setTransform(150,74.05);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(145).to({_off:false},0).to({alpha:1},15).wait(53).to({x:450},12,cjs.Ease.quintIn).wait(79));

	// HEAD3
	this.instance_12 = new lib.HEAD3();
	this.instance_12.parent = this;
	this.instance_12.setTransform(99,83);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(145).to({_off:false},0).to({alpha:1},8).wait(65).to({x:360},12,cjs.Ease.quintIn).to({_off:true},1).wait(73));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_161 = new cjs.Graphics().p("AgSTiMAAAgnDIAlAAMAAAAnDg");
	var mask_3_graphics_162 = new cjs.Graphics().p("AhCTiMAAAgnDICFAAMAAAAnDg");
	var mask_3_graphics_163 = new cjs.Graphics().p("AhyTiMAAAgnDIDlAAMAAAAnDg");
	var mask_3_graphics_164 = new cjs.Graphics().p("AiiTiMAAAgnDIFFAAMAAAAnDg");
	var mask_3_graphics_165 = new cjs.Graphics().p("AjSTiMAAAgnDIGlAAMAAAAnDg");
	var mask_3_graphics_166 = new cjs.Graphics().p("AkBTiMAAAgnDIIDAAMAAAAnDg");
	var mask_3_graphics_167 = new cjs.Graphics().p("AkxTiMAAAgnDIJjAAMAAAAnDg");
	var mask_3_graphics_168 = new cjs.Graphics().p("AlhTiMAAAgnDILDAAMAAAAnDg");
	var mask_3_graphics_169 = new cjs.Graphics().p("AmRTiMAAAgnDIMjAAMAAAAnDg");
	var mask_3_graphics_170 = new cjs.Graphics().p("AnATiMAAAgnDIOBAAMAAAAnDg");
	var mask_3_graphics_171 = new cjs.Graphics().p("AnwTiMAAAgnDIPhAAMAAAAnDg");
	var mask_3_graphics_172 = new cjs.Graphics().p("AogTiMAAAgnDIRBAAMAAAAnDg");
	var mask_3_graphics_173 = new cjs.Graphics().p("ApPTiMAAAgnDISgAAMAAAAnDg");
	var mask_3_graphics_174 = new cjs.Graphics().p("Ap/TiMAAAgnDIT/AAMAAAAnDg");
	var mask_3_graphics_175 = new cjs.Graphics().p("AqvTiMAAAgnDIVfAAMAAAAnDg");
	var mask_3_graphics_176 = new cjs.Graphics().p("ArfTiMAAAgnDIW/AAMAAAAnDg");
	var mask_3_graphics_177 = new cjs.Graphics().p("AsOTiMAAAgnDIYeAAMAAAAnDg");
	var mask_3_graphics_178 = new cjs.Graphics().p("As+TiMAAAgnDIZ+AAMAAAAnDg");
	var mask_3_graphics_179 = new cjs.Graphics().p("AtuTiMAAAgnDIbdAAMAAAAnDg");
	var mask_3_graphics_180 = new cjs.Graphics().p("AueTiMAAAgnDIc9AAMAAAAnDg");
	var mask_3_graphics_181 = new cjs.Graphics().p("AvNTiMAAAgnDIecAAMAAAAnDg");
	var mask_3_graphics_182 = new cjs.Graphics().p("Av9TiMAAAgnDIf8AAMAAAAnDg");
	var mask_3_graphics_183 = new cjs.Graphics().p("AwtTiMAAAgnDMAhcAAAMAAAAnDg");
	var mask_3_graphics_184 = new cjs.Graphics().p("AxcTiMAAAgnDMAi6AAAMAAAAnDg");
	var mask_3_graphics_185 = new cjs.Graphics().p("AyMTiMAAAgnDMAkaAAAMAAAAnDg");
	var mask_3_graphics_186 = new cjs.Graphics().p("Ay8TiMAAAgnDMAl6AAAMAAAAnDg");
	var mask_3_graphics_187 = new cjs.Graphics().p("AzsTiMAAAgnDMAnaAAAMAAAAnDg");
	var mask_3_graphics_188 = new cjs.Graphics().p("A0bTiMAAAgnDMAo4AAAMAAAAnDg");
	var mask_3_graphics_189 = new cjs.Graphics().p("A1LTiMAAAgnDMAqYAAAMAAAAnDg");
	var mask_3_graphics_190 = new cjs.Graphics().p("A17TiMAAAgnDMAr4AAAMAAAAnDg");
	var mask_3_graphics_191 = new cjs.Graphics().p("A2rTiMAAAgnDMAtYAAAMAAAAnDg");
	var mask_3_graphics_192 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:null,x:0,y:0}).wait(161).to({graphics:mask_3_graphics_161,x:1.9003,y:125}).wait(1).to({graphics:mask_3_graphics_162,x:6.6818,y:125}).wait(1).to({graphics:mask_3_graphics_163,x:11.4632,y:125}).wait(1).to({graphics:mask_3_graphics_164,x:16.2447,y:125}).wait(1).to({graphics:mask_3_graphics_165,x:21.0261,y:125}).wait(1).to({graphics:mask_3_graphics_166,x:25.8075,y:125}).wait(1).to({graphics:mask_3_graphics_167,x:30.589,y:125}).wait(1).to({graphics:mask_3_graphics_168,x:35.3704,y:125}).wait(1).to({graphics:mask_3_graphics_169,x:40.1519,y:125}).wait(1).to({graphics:mask_3_graphics_170,x:44.9317,y:125}).wait(1).to({graphics:mask_3_graphics_171,x:49.7102,y:125}).wait(1).to({graphics:mask_3_graphics_172,x:54.4888,y:125}).wait(1).to({graphics:mask_3_graphics_173,x:59.2673,y:125}).wait(1).to({graphics:mask_3_graphics_174,x:64.0458,y:125}).wait(1).to({graphics:mask_3_graphics_175,x:68.8243,y:125}).wait(1).to({graphics:mask_3_graphics_176,x:73.6028,y:125}).wait(1).to({graphics:mask_3_graphics_177,x:78.3814,y:125}).wait(1).to({graphics:mask_3_graphics_178,x:83.1599,y:125}).wait(1).to({graphics:mask_3_graphics_179,x:87.9384,y:125}).wait(1).to({graphics:mask_3_graphics_180,x:92.7169,y:125}).wait(1).to({graphics:mask_3_graphics_181,x:97.4954,y:125}).wait(1).to({graphics:mask_3_graphics_182,x:102.274,y:125}).wait(1).to({graphics:mask_3_graphics_183,x:107.0525,y:125}).wait(1).to({graphics:mask_3_graphics_184,x:111.831,y:125}).wait(1).to({graphics:mask_3_graphics_185,x:116.6095,y:125}).wait(1).to({graphics:mask_3_graphics_186,x:121.388,y:125}).wait(1).to({graphics:mask_3_graphics_187,x:126.1666,y:125}).wait(1).to({graphics:mask_3_graphics_188,x:130.9451,y:125}).wait(1).to({graphics:mask_3_graphics_189,x:135.7236,y:125}).wait(1).to({graphics:mask_3_graphics_190,x:140.5021,y:125}).wait(1).to({graphics:mask_3_graphics_191,x:145.2806,y:125}).wait(1).to({graphics:mask_3_graphics_192,x:149.925,y:125}).wait(15).to({graphics:null,x:0,y:0}).wait(97));

	// GradHat-OUTLINE
	this.instance_13 = new lib.GradHatOUTLINE();
	this.instance_13.parent = this;
	this.instance_13.setTransform(150,179.75,1,1,0,0,0,0,0.7);
	this.instance_13._off = true;

	var maskedShapeInstanceList = [this.instance_13];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(161).to({_off:false},0).wait(31).to({alpha:0},15).to({_off:true},1).wait(96));

	// GradHat-ALL
	this.instance_14 = new lib.GradHatALL();
	this.instance_14.parent = this;
	this.instance_14.setTransform(150,179.75,1,1,0,0,0,0,0.7);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(192).to({_off:false},0).to({alpha:1},15).wait(25).to({x:450},14,cjs.Ease.quintIn).wait(58));

	// HEAD4
	this.instance_15 = new lib.HEAD4();
	this.instance_15.parent = this;
	this.instance_15.setTransform(206,186);
	this.instance_15.alpha = 0;
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(192).to({_off:false},0).to({alpha:1},8).wait(25).to({x:356},14,cjs.Ease.quintIn).to({_off:true},8).wait(57));

	// bkgd
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_1.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(304));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-149,124.5,785.3,126);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 250,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_MoreThan_300x250_atlas_.png?1570136209912", id:"CO_MoreThan_300x250_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;