(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"CO_Child_160x600_atlas_", frames: [[0,0,259,107]]}
];


// symbols:



(lib.Buttonshad = function() {
	this.initialize(ss["CO_Child_160x600_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.RULE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,2,1).p("A3LAAMAuXAAA");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.RULE, new cjs.Rectangle(-149.3,-1,298.70000000000005,2), null);


(lib.MotherChildoutlineai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-outline.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AXdJgIjTAAQhNgDgngfQghgZgUg5QgOg/gJgaQgLgcgYgmQgVghgjgVQgEgDhFgiIgWgJIgJgIQgbgQgYgEIglAAQgMAFgKAIQAZgWAGgjQAFgggNghQgYhBhEgsQgogbgtgJQAIgPAEgQQAEgPACgbQACgfACgLQAEgWASg+IAGgYQAUABALgJQAVgRgJgyQgPhKg7g+QgugwgEgEQgegdgbgNQgXgLgwgFQgkgEgkADQhAAFguAaQgHgZgfgOQgagLgdACQgfACgfAOQgfANgYAVQgXAUgJAXQgMAcAMAYQgaAFgPAQQgWAaAKAoQAKAnAeARQgVAYgHAbQgHAhATAWQATAWAdgEQAZgEAXgUQATgRAHAaQAFAWACAtQABAHADASQADAQAGAIIADAKQAHASADAGQAIAPAKAEQASAIAEgYQAEgSgEgQQgCgKgGgUQABgTgJgaQgEgLgPgfIgFgNIgBgDQANgQAWgMIgBABQgHAsAOArQAIAXANARQAFAGAKAKQAIAJgBAKQgCA6gOAsQgeBjhMAfQgOAHgfAOQgeANgPAIQgzAbgdAXQhQA/gUBcQgKAuAKBAQAIAyAQAqIAHAOI18AAAC1jgIgBAAIAAAAg");
	this.shape.setTransform(150.125,61.5596);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.2,302.3,123.60000000000001);


(lib.MotherChildMOTHERonlyai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-MOTHERonly.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AO1mkQgKgjgRgTQgXgagpgRQgVgJgKgDQgXgHgFALQgEAIAJAOQADADANAPQAYAbAjAQQAZALAtALgAQtknQgMgBgOgGQgigMgbgeQgSgUgMgtQgBgFgCgGQABAAAAAAQAuALAXALQAnASALAeQAGAQgDAXQgBAFgCALgAKlpLQAugaBAgFQAlgDAkAEQAvAFAXALQAcANAeAdQAEAEAtAwQA8A+AOBKQAKAygVARQgNAKgSgBQgDAJgEAOQgSA+gDAWQgCALgCAfQgCAbgEAPQgKAlgaAiQgVAcggAaQgIAHgXARQgVAPgLAJQgaAYgogOQgZgIgmgcQgIgGgHgGQgYgTgQgVQgigtANgYQAKgTAQAUQALAMAIAVQALAaAFAuQAAACAAABAKgk3QAKALAHADQAQAFAPgNQAHgHANgUQALgRATgLQALgHAagMQAYgKAHgFQASgMACgOQACgTgTgGQgQgGgRAGQgVAIgVAeQgTAkgLARQgUAdgjALQgFACgEABQgyAQgbAPQAFgWAKgQQAOgWAUAFQALADAMAPQADAEACACgAIwj7QgKgVgGgMQgNgdgFgVQgOg4AyhKQAdgqAQgUQAcgiAcgSQAHgFAHgEAIwj8QgRg/AGgsQAEgfATgcQAKgPAggjQAiglAJgNQAYgigDgbQAAgEgBgEQgGgXgbgOQgcgNgfACQggACgfAOQgeANgYAVQgXAUgKAXQgMAcAMAYQgaAFgOAQQgXAaALAoQAKAnAeARQgWAYgGAbQgIAhATAWQATAWAegEQAZgEAXgUQATgRAGAaQAGAWACAtQADAXABAHQADANAGAHQABAEACAFQAHASADAGQAIAPAJAEQASAIAFgYQAEgSgEgQQgDgNgFgQQgEgMgFgPQgPgtgDgKQgDgIgCgIQgBgDgBgCQgTAVgEAaQgEAfAQA0QACADADABQAMAJAOgLQAMgKACgOQAAgCAAgDQABgTgJgYQgDgKgQgjQgDgFgCgFQgBgDgBgDQAAAAAAABAEaJCQgDgGgDgIQgQgqgIgyQgKhAAKguQAUhcBQg/QAegXAygbQAQgIAdgNQAggOANgHQBMgfAfhiQAOgtACg6QAAgKgIgJQgKgKgEgGQgOgRgIgXQgOgrAIgsQAAAAAAgBQgCACgBAAQgTAMgNAOAEaJCIAKAAQAnAAAUAUQASARgMAPQgLAOgbgVQgXgSgOgbgAxhJCIV7AA");
	this.shape.setTransform(-37.827,0.0008);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-151,-64.6,225.6,129.2);


(lib.MotherChildCHILDonlyai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-CHILDonly.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AgfgqQAMAEALAGQBEAhAEADQAjAVAUAhQAZAmAKAcQAKAaAOA/QAUA5AhAZQAnAfBNADIDTAAAn3gYQgggygEgxQgDgkANgkQAMgiAZgdQAZgcAhgSQAigSAlgEQBKgJBHAvQBEAtAYBBQANAhgFAgQgFAegUAUQABgBACAAIAAgBQADgCAEgBAgfgqQAoAiAWAlQAeAzgKAxQgeA7hOAIQgWAChygJQg4gBgFgBQgkgHgHgeQAAAGgLgCQgLgDgDAAQgNgEgYgNQgZgNgNgEQgTgFgJgDQgRgGgIgKQgUgYAjgLQgSgRgRgUQgUgWgNgXQADABADAAQAKgCAIgNQABgDAJgTQARgpAOgUQAWggAdgIQAbgIAqANQA4ARANABQAQACAJgFQAGgEAAgGQAAgBgDgLQgCgGACgFQADgGAGgBQAJAAANAMQAMALAJAOQAJAQAAAPQAAAPgOAJQgIAFgCAFQgDAFAAAJQABAMAGAYQACARgFAZQgHAkgNAYQgFAJgFAHQgvBDhXgnQgugVgqgmQABgBAAAAQAQgFAngEQAZgCAMABQAWABAMALQAIAHAEAKQAEAHgBAHQAEgBAFgBQALgDAVgCQAWgCAIgCQAJgCAKgEQAMgFAOgIQATgLAMgGQAIgFAFgBQAZgLAUAHQALAEAHAGQAKAJgEAJQgGASgcgIQgXgGgPgMQgGgFgEgFQgHgJgDgLQgGgTAGgRQAPgoAzAAQAdAAAeALgAiUg5QAKgIAKgEIAmAAQAYAEAbAQQAEADAEAEAiUg6QABgBABgBQABgBABAAQACgCACgBAiUg6IAAAAQAAAAAAABQgBAAAAABQAAgBABgBQACgCADgDQgCADgDACgAiUg6IgBACAomhHQALARAOANQALAMABAAQAFAEAFABAklBaQABADgBACQgBAFgEAGQgFAIgEAAQgGAAABgGQABgFADgEQAGgGAJgDg");
	this.shape.setTransform(94.3,25.1451);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1.5,1,1).p("AgShKQABAzAFAaQAEAcAbAs");
	this.shape_1.setTransform(37.375,10.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(34.5,-8.7,116.6,67.7);


(lib.MotherChildallai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// MotherChild-all.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,0,0,4).p("AOQDQQALAEALAGQBFAiAEADQAjAVAVAhQAYAmALAcQAJAaAOA/QAUA5AhAZQAnAfBNADIDTAAAI6mkQgLgjgRgTQgXgagpgRQgUgJgKgDQgYgHgFALQgDAIAJAOQACADANAPQAYAbAjAQQAZALAuALgAKxknQgMgBgNgGQgjgMgbgeQgSgUgLgtQgCgFgBgGQAAAAAAAAQAvALAWALQAoASALAeQAGAQgEAXQgBAFgCALgAEqpLQAtgaBBgFQAkgDAkAEQAwAFAXALQAbANAeAdQAEAEAuAwQA7A+APBKQAJAygVARQgMAKgTgBQgCAJgEAOQgSA+gEAWQgCALgCAfQgCAbgEAPQgEAQgHAPQAqAIAqAcQBEAsAYBBQANAhgFAgQgEAYgNASQgEAEgDAEQAAABgBAAQgCACgCACQABgBABgBQACgBADgDIAAAAQAEgDAGgBQABAAACgBIAlAAQAYAEAbAQQAEAEAFADQApAjAVAlQAeAzgKAxQgeA7hOAIQgXAChygJQg4gBgFgBQgjgHgHgeQgBAGgKgCQgMgDgCAAQgOgEgYgNQgYgNgNgEQgTgFgKgDQgRgGgIgKQgUgXAkgMQAAAAABgBQAPgFAogEQAYgCANABQAVABANALQAHAHAFAKQADAHAAAHQAEgBAEgBQAMgDAUgCQAWgCAJgCQAIgBAKgEQgFAIgFAHQguBDhYgnQgugVgpgmQgSgRgSgUQgTgXgOgWQADABADgBQAKgCAIgNQACgDAJgTQAQgpAOgUQAWggAegIQAagIAqANQA4ARANABQARACAIgFQAHgEgBgGQAAgBgDgLQgCgGACgFQADgGAGgBQAJAAANAMQANALAIAOQAJAQAAAPQAAAPgOAJQgHAFgDAFQgDAFABAJQAAAMAGAYQADARgGAaQgHAkgNAZQAMgFAPgJQASgLAMgGQAIgEAFgCQAZgLAVAHQAKAEAHAGQAKAJgEAJQgGASgcgIQgXgGgPgMQgGgEgEgGQgHgJgDgLQgGgTAHgSQAOgoAzAAQAdAAAfALAElk3QAJALAIADQAPAFAPgNQAHgHAOgUQAKgRATgLQAMgHAagMQAXgKAIgFQARgMACgOQADgTgTgGQgQgGgSAGQgVAIgUAeQgUAkgLARQgTAdgkALQgEACgEABQgzAQgaAPQAEgWAKgQQAPgWAUAFQAKADANAPQACAEADACgAC0j7QgKgVgFgMQgNgdgGgVQgNg4AxhKQAdgqARgUQAcgiAbgSQAHgFAIgEAC1j8QgRg/AFgsQAEgfAUgcQAKgPAfgjQAjglAJgNQAXgigCgbQgBgEAAgEQgGgXgcgOQgbgNggACQgfACgfAOQgfANgYAVQgXAUgJAXQgMAcAMAYQgaAFgPAQQgWAaAKAoQAKAnAeARQgVAYgHAbQgHAhATAWQATAWAdgEQAZgEAXgUQATgRAHAaQAFAWACAtQADAXACAHQADANAFAHQACAEABAFQAHASADAGQAIAPAKAEQASAIAEgYQAEgSgEgQQgCgNgFgQQgEgMgFgPQgQgtgDgKQgCgIgCgIQgCgDgBgCQgSAVgEAaQgEAfAPA0QADADACABQANAJANgLQANgKABgOQABgCAAgDQABgTgJgYQgEgKgQgjQgCgFgCgFQgBgDgBgDQgBAAAAABAhhJCQgDgGgDgIQgQgqgIgyQgKhAAKguQAUhcBQg/QAdgXAzgbQAPgIAegNQAfgOAOgHQBMgfAehiQAOgtACg6QABgKgIgJQgKgKgFgGQgNgRgIgXQgOgrAHgsQAAAAABgBQgCACgCAAQgTAMgMAOAGZBEQgRgJgVgQQgIgGgHgGQgYgTgRgVQgigtAOgYQAKgTAQAUQAKAMAJAVQALAaAEAuQAAACABABQAFA2AEAVQAJArATAeQALARANANQAMAMABAAQAEAEAFACQgggzgDgxQgDgdAIgeQACgGADgHQAMgiAZgcQAYgcAigSQAhgSAlgEQAfgDAeAFQgKAVgOATQgWAcgfAaQgJAHgXARQgVAPgKAJQgaAYgogOQgLgDgOgIgAMiC6QADgDACgEAMgC7QgDACgDADQADgCACgCQACgBABgBQgBABgBAAgAMaDAQAAABAAAAQgBABAAAAQAAAAAAgBQABAAAAgBAMbDAQAAAAgBAAIgBACAMaDBQAIgGAKgFAKKFVQAAADgBACQgBAFgEAGQgEAIgFAAQgFAAABgGQAAgFAEgEQAFgFAKgEgAhhJCIALAAQAmAAAUAUQASARgLAPQgLAOgcgVQgXgSgOgbgA3cJCIV7AA");
	this.shape.setTransform(150.125,64.3508);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-0.2,302.3,129.2);


(lib.HEAD3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAKQgEgEAAgGQAAgFAEgEQAEgFAFAAQAGAAAEAFQAEAEAAAFQAAAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape.setTransform(64.975,-96.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag1A7QgVgWAAglQAAgjAWgYQAWgXAiAAQAgAAAUAVQATAWAAAiIAAAHIiEAAQAAAeARATQARATAbABQAvAAALgtIANADQgFAZgSAOQgTAPgdAAQgjAAgWgYgAA7gIQgBgdgOgQQgPgSgaABQgZAAgRARQgQAQgCAdIB0AAIAAAAg");
	this.shape_1.setTransform(54.275,-103.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgjBvIAAgMIAYAAQADAAAAgHIAAi0QAAgHgDAAIgYAAIAAgMIAJAAQAVAAANgDIAADKQAAAHAEAAIAXAAIAAAMg");
	this.shape_2.setTransform(42.2,-106.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgvBIQgBAPgFAWIgMAAQADgUAAgjIAAiPQgBgIgEAAIgWAAIAAgMIAHAAQAWAAAOgDIAABjQATgoArAAQAiAAAUAXQAVAXAAAkQAAAmgVAXQgUAWgiAAQgtAAgSgogAgdgVQgQASgBAfIAAADQABAfAQATQARATAZgBQAcAAAQgSQARgSAAggIAAgEQAAgegRgTQgQgSgcAAQgZAAgRATg");
	this.shape_3.setTransform(28.45,-106.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiBuIAAgMIAXAAQAEAAAAgHIAAhyQAAgNgIAAIgTAAIAAgNIAIAAQAVAAAOgCIAACOQAAAHADAAIAXAAIAAAMgAgNhfQAAgGAEgEQAEgEAFAAQAFAAAEAEQAEAEAAAGQAAAFgEAEQgEAFgFAAQgNAAAAgOg");
	this.shape_4.setTransform(15.625,-106.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhUBVQAAgbAogKQgegEAAgXQAAgUAZgIQgXgPAAgeQAAgaATgQQASgQAdAAQAfAAASAVQAGgeAVAAQAHAAAEAEQAEAFAAAFQAAAMgMAAQgKABgCgLQgIAHgEAQQAIANAAAPQAAAagSAQQgSAOgdgBQgRAAgOgEQgVADAAAQQAAARAbAAIA8AAQAyAAAAAlQAAAYgYAMQgWAMgnAAQhMAAAAgjgAg5A/QgMAIAAAMQAAAaA9AAQBHAAAAgjQAAgYgnAAIgxAAQgTAEgNAJgAgqhWQgOAMAAAWIAAAAQAAAVAOANQANAMAWgBQAVABANgMQANgNAAgUIAAgBQAAgVgNgNQgNgNgUAAQgXAAgNANg");
	this.shape_5.setTransform(3.7,-100.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgiBuIAAgMIAXAAQAEAAAAgHIAAhyQAAgNgIAAIgTAAIAAgNIAIAAQAVAAAOgCIAACOQAAAHADAAIAXAAIAAAMgAgNhfQAAgGAEgEQAEgEAFAAQAFAAAEAEQAEAEAAAGQAAAFgEAEQgEAFgFAAQgNAAAAgOg");
	this.shape_6.setTransform(-8.525,-106.35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgiBvIAAgMIAWAAQAFAAAAgHIAAi0QAAgHgFAAIgWAAIAAgMIAIAAQAVAAAOgDIAADKQgBAHAEAAIAYAAIAAAMg");
	this.shape_7.setTransform(-16.35,-106.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag1A7QgVgWAAglQAAgjAWgYQAWgXAiAAQAgAAAUAVQATAWAAAiIAAAHIiEAAQAAAeARATQARATAbABQAvAAALgtIANADQgFAZgSAOQgTAPgdAAQgjAAgWgYgAA7gIQgBgdgOgQQgPgSgaABQgZAAgRARQgQAQgCAdIB0AAIAAAAg");
	this.shape_8.setTransform(-28.475,-103.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgpBxIAAgNIAUAAQAEAAAAgGIAAiAIgYAAIAAgMIAYAAIAAgYQAAgpAlAAQANAAAJAEIAAAOQgJgGgLAAQgNABgFAGQgFAHABAQIAAAXIAiAAIAAAMIgiAAIAACAQAAAGADAAIAYAAIAAANg");
	this.shape_9.setTransform(-47.475,-106.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgiBuIAAgMIAXAAQAEAAAAgHIAAhyQAAgNgIAAIgTAAIAAgNIAIAAQAVAAAOgCIAACOQAAAHADAAIAXAAIAAAMgAgNhfQAAgGAEgEQAEgEAFAAQAFAAAEAEQAEAEAAAGQAAAFgEAEQgEAFgFAAQgNAAAAgOg");
	this.shape_10.setTransform(-55.975,-106.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag9AeIAAhcQAAgGgDAAIgYAAIAAgNIAsAAIAABuQAAAnAkAAQAXAAAPgVQAPgUAAgeIAAg7QAAgGgEAAIgXAAIAAgNIAsAAIAACMQAAAHAEAAIAXAAIAAAMIgJAAQgVAAgOACIAAgqQgRAsgngBQgyAAAAgzg");
	this.shape_11.setTransform(33.975,-148);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag4A8QgWgXABglQAAgkAWgXQAWgXAiAAQAjAAAVAXQAWAXgBAkQAAAlgVAXQgWAXgjAAQgiAAgWgXgAgsgzQgQATAAAgIAAAAQAAAhAQASQARAUAbgBQAcABARgUQARgSAAghIAAAAQAAgggRgTQgQgTgdAAQgbAAgRATg");
	this.shape_12.setTransform(16.55,-148.15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhKBmQgJgIAAgLQAAgIAEgEQAEgFAHAAQALAAAAAKQAAAKgKAEQAEAHAMAAQAOAAAKgLQALgMAMggIAAgBIg+iDQgDgGgDAAIgRAAIAAgMIA+AAIAAAMIgRAAQgIAAADAHIA1BwIAxhwQADgHgIAAIgSAAIAAgMIA8AAIAAAMIgRAAQgEAAgCAGIg9CLQgNAhgKAMQgNAPgVAAQgOAAgJgHg");
	this.shape_13.setTransform(-0.675,-145.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag4A8QgVgXAAglQgBgkAXgXQAWgXAiAAQAjAAAVAXQAVAXAAAkQABAlgWAXQgWAXgjAAQgiAAgWgXgAgsgzQgQATAAAgIAAAAQAAAhAQASQARAUAbgBQAcABASgUQAQgSAAghIAAAAQAAgggQgTQgRgTgcAAQgcAAgRATg");
	this.shape_14.setTransform(-25.1,-148.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgHBaQgJgJAAgVIAAhtIgaAAIAAgLIATgBQAJgBAAgIIACgdIAMAAIAAAlIAoAAIAAANIgoAAIAABtQAAAbAYAAQAGAAANgDIAAAMQgLAEgLAAQgUAAgIgKg");
	this.shape_15.setTransform(-38.175,-149.875);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgHBaQgJgJAAgVIAAhtIgaAAIAAgLIATgBQAJgBAAgIIACgdIAMAAIAAAlIAoAAIAAANIgoAAIAABtQAAAbAYAAQAGAAANgDIAAAMQgLAEgLAAQgUAAgIgKg");
	this.shape_16.setTransform(61.275,-194.725);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("Ag5BEIAAgoIAOAAIAAAhQARAKAaAAQAqAAAAggQAAgQgNgHQgJgGgWgEQgagGgMgGQgRgLAAgUQAAgVAQgMQAQgMAZAAQAeAAAXAOIAAAoIgOAAIAAggQgQgLgXAAQgTAAgLAJQgLAIAAAPQAAAQAOAGQAIAFAXAEQAaAFAMAIQAQALAAAUQAAAWgQANQgPAMgbAAQggAAgZgPg");
	this.shape_17.setTransform(49.975,-193);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag3A8QgXgXAAglQABgkAWgXQAWgXAiAAQAiAAAWAXQAVAXABAkQAAAkgXAYQgVAXgjAAQgiAAgVgXgAgsgzQgRATAAAgIAAAAQAAAgARAUQARASAbABQAdgBAQgSQARgUAAggIAAAAQAAgggRgTQgQgTgdAAQgbAAgRATg");
	this.shape_18.setTransform(34.6,-193);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag0A8QgWgXAAglQAAgkAXgXQAXgXAiAAQAeAAATAPQAUAQAAAZQAAAHgEAFQgFAGgGgBQgNAAAAgMQAAgNANgBQgIgkguAAQgcAAgRAUQgSATAAAgIAAAAQAAAgARATQARAUAcAAQAvgBALgsIAMADQgGAZgRAPQgTAOgcAAQgkAAgVgXg");
	this.shape_19.setTransform(18.325,-193);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag4A8QgWgXABglQAAgkAWgXQAWgXAiAAQAjAAAVAXQAWAXgBAkQAAAkgVAYQgWAXgjAAQgiAAgWgXgAgsgzQgQATAAAgIAAAAQAAAgAQAUQARASAbABQAcgBARgSQARgUAAggIAAAAQAAgggRgTQgQgTgdAAQgbAAgRATg");
	this.shape_20.setTransform(-5.5,-193);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAUBRIAAgMIAVAAQAFAAAAgGIAAhZQgBgpgjAAQgYAAgQAVQgPAXAAAkIAAAyQAAAGAEAAIAXAAIAAAMIhGAAIAAgMIAWAAQAFAAAAgGIAAh5QAAgHgFAAIgWAAIAAgMIAIAAQAVAAAOgDIAAAtQARgtAoAAQAzAAAAA1IAABaQAAAGADAAIAYAAIAAAMg");
	this.shape_21.setTransform(-23.2,-193.175);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgHBaQgJgJAAgVIAAhtIgaAAIAAgLIATgBQAJgBAAgIIACgdIAMAAIAAAlIAoAAIAAANIgoAAIAABtQAAAbAYAAQAGAAANgDIAAAMQgLAEgLAAQgUAAgIgKg");
	this.shape_22.setTransform(-44.225,-194.725);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag/BHQgNgMAAgSQAAgaAbgOQAZgMA6gGIAAgJQAAgXgLgLQgLgLgWAAQgiABgMATQALACgBALQAAAMgNAAQgOAAAAgQQAAgRATgMQATgLAaAAQA8AAAAA3IAABYQAAAHADAAIAYAAIAAAMIgoAAQgCgOgCgXQgGATgSAKQgPALgWAAQgWAAgOgMgAglAIQgXAKAAAVQAAAOALAJQAJAJARAAQAZAAAQgSQAQgSAAgcIAAgOQgyAGgVAJg");
	this.shape_23.setTransform(-56.55,-193);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag1A7QgVgWAAglQAAgjAWgYQAWgXAiAAQAgAAAUAVQATAWAAAiIAAAHIiEAAQAAAeARATQARATAbABQAvAAALgtIANADQgFAZgSAOQgTAPgdAAQgjAAgWgYgAA7gIQgBgdgOgQQgPgSgaABQgZAAgRARQgQAQgCAdIB0AAIAAAAg");
	this.shape_24.setTransform(59.425,-237.85);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag7BRIAAgMIAXAAQAEAAAAgGIAAh5QAAgHgEAAIgXAAIAAgMIAIAAQAUAAAPgDIAAAnQALgnAhAAQAPAAAJAIQAIAIAAAMQAAATgPAAQgFAAgEgDQgDgDAAgFQAAgLAMgBQgDgMgQAAQgVAAgKAVQgKATAAAhIAAA6QAAAGAEAAIAYAAIAAAMg");
	this.shape_25.setTransform(44.95,-238.025);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("Ag3A8QgXgXAAglQAAgkAXgXQAWgXAiAAQAiAAAWAXQAVAXABAkQAAAkgXAYQgVAXgjAAQgiAAgVgXgAgsgzQgQATAAAgIAAABQAAAfAQATQARAUAbAAQAcAAASgUQAQgTAAgfIAAgBQAAgggQgTQgRgTgcAAQgcAAgRATg");
	this.shape_26.setTransform(30,-237.85);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("ABABRIAAgMIAVAAQAEAAAAgGIAAhTQgBgZgHgLQgJgLgUAAQgVAAgMARQgLARABAfIAABBQAAAGADAAIAZAAIAAAMIhGAAIAAgMIAVAAQAFAAAAgGIAAhYQAAgqgkAAQgWAAgMARQgLARAAAfIAABBQAAAGAEAAIAXAAIAAAMIhHAAIAAgMIAYAAQADAAAAgGIAAh5QAAgHgDAAIgYAAIAAgMIAJAAQAUAAAPgDIAAAhQAOghAhAAQAoAAAGAnQAOgnAlAAQAyAAAAA7IAABUQAAAGADAAIAYAAIAAAMg");
	this.shape_27.setTransform(7.95,-238.025);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AhFBaQgVgWAAgnQAAgkAVgXQAVgXAhAAQAsAAASApIAAhNQAAgIgEAAIgYAAIAAgMIAKAAQAUAAAPgDIAADKQAAAHAEAAIAXAAIAAAMIgqAAQgCgPAAgWQgSAogrAAQgjAAgUgWgAg4gWQgQATAAAeIAAAEQAAAgAQASQARASAbAAQAaABAQgTQARgTAAgfIAAgDQAAgfgRgSQgQgTgaAAQgbAAgRASg");
	this.shape_28.setTransform(-22.125,-240.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAUBRIAAgMIAVAAQAFAAAAgGIAAhZQAAgpgkAAQgYAAgQAVQgPAXAAAkIAAAyQAAAGAEAAIAXAAIAAAMIhGAAIAAgMIAWAAQAFAAAAgGIAAh5QAAgHgFAAIgWAAIAAgMIAIAAQAVAAAOgDIAAAtQARgtAoAAQAzAAAAA1IAABaQAAAGADAAIAYAAIAAAMg");
	this.shape_29.setTransform(-41.1,-238.025);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag+BIQgOgNgBgSQAAgaAbgOQAagMA6gGIAAgJQAAgXgLgLQgKgKgXAAQgiAAgNATQAMACAAALQAAANgOAAQgOAAAAgRQAAgRATgMQATgLAbAAQA7AAAAA4IAABXQAAAGAEAAIAWAAIAAANIgnAAQgCgOgBgXQgHASgRAMQgQAKgVAAQgXAAgNgLgAgmAIQgWAKAAAVQAAAOAKAJQAKAJARAAQAZgBAQgRQAQgSAAgcIAAgNQgyAEgWAKg");
	this.shape_30.setTransform(-58.3,-237.85);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("Ag1A7QgVgWAAglQAAgkAWgXQAWgXAiAAQAgAAAUAVQATAWAAAiIAAAHIiEAAQAAAeARATQARATAbAAQAvABALguIANAFQgFAXgSAPQgTAPgdAAQgjAAgWgYgAA7gJQgBgcgOgRQgPgRgaAAQgZABgRARQgQAQgCAcIB0AAIAAAAg");
	this.shape_31.setTransform(22.875,-282.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("Ag7BRIAAgMIAXAAQAEAAAAgGIAAh5QAAgHgEAAIgXAAIAAgMIAIAAQAUAAAPgDIAAAnQAMgnAgAAQAPAAAJAIQAIAIAAAMQAAATgPAAQgFAAgDgDQgEgDAAgFQAAgLAMgBQgDgMgQAAQgVAAgKAVQgKATAAAhIAAA6QAAAGAEAAIAYAAIAAAMg");
	this.shape_32.setTransform(8.4,-282.875);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("Ag/BHQgOgMABgSQAAgaAbgOQAZgNA6gFIAAgJQAAgXgLgLQgKgLgXAAQgiAAgNAVQALACAAAKQAAAMgNAAQgOAAAAgQQAAgRATgMQATgLAaAAQA8AAAAA3IAABYQAAAGAEABIAWAAIAAALIgnAAQgDgOgBgWQgGATgRAKQgQALgWAAQgWAAgOgMgAgmAHQgWALAAAVQAAAOALAJQAKAIAQAAQAZAAAQgRQAQgSAAgcIAAgNQgyAEgWAJg");
	this.shape_33.setTransform(-5.85,-282.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("Ag0A8QgWgXAAglQAAgjAXgYQAXgXAiAAQAeAAATAPQAUAPAAAaQAAAHgEAGQgFAEgGAAQgNAAAAgMQAAgMANgCQgIgjgugBQgcABgRATQgSATAAAfIAAABQAAAgARATQARATAcAAQAvABALguIAMAEQgGAZgRAOQgTAPgcAAQgkAAgVgXg");
	this.shape_34.setTransform(-22.425,-282.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AAUBvIAAgMIAWAAQAEAAAAgHIAAhaQAAgogkAAQgYAAgPAWQgPAWAAAkIAAAyQAAAHAEAAIAWAAIAAAMIhGAAIAAgMIAXAAQAEAAAAgHIAAi0QAAgHgEAAIgYAAIAAgMIAKAAQAUAAAPgDIAABoQARgtAoAAQAyAAAAAzIAABcQAAAHADAAIAYAAIAAAMg");
	this.shape_35.setTransform(36.175,-330.675);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgHBaQgJgJAAgVIAAhtIgaAAIAAgLIATgBQAJgBAAgIIACgdIAMAAIAAAlIAoAAIAAANIgoAAIAABtQAAAbAYAAQAGAAANgDIAAAMQgLAEgLAAQgUAAgIgKg");
	this.shape_36.setTransform(22.525,-329.275);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgiBvIAAgMIAWAAQAFAAAAgHIAAi0QAAgHgFAAIgWAAIAAgMIAIAAQAVAAAOgDIAADKQgBAHAEAAIAYAAIAAAMg");
	this.shape_37.setTransform(14.15,-330.675);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("Ag+BHQgOgMgBgSQAAgaAbgOQAagMA6gGIAAgJQAAgXgLgLQgKgLgXAAQgiABgNATQALACAAALQAAAMgNAAQgOAAAAgQQAAgRATgMQATgLAbAAQA7AAAAA3IAABYQAAAHAEAAIAWAAIAAAMIgnAAQgCgOgCgXQgGATgRAKQgQALgVAAQgXAAgNgMgAgmAIQgWAKAAAVQAAAOAKAJQALAJAQAAQAZAAAQgSQAQgSAAgcIAAgOQgyAGgWAJg");
	this.shape_38.setTransform(2.35,-327.55);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("Ag1A8QgVgYAAgkQAAgjAWgYQAWgXAiAAQAgAAAUAVQATAVAAAjIAAAHIiEAAQAAAeARATQARAUAbAAQAvgBALgsIANADQgFAYgSAPQgTAPgdAAQgjAAgWgXgAA7gJQgBgcgOgRQgPgQgagBQgZAAgRASQgQARgCAbIB0AAIAAAAg");
	this.shape_39.setTransform(-14.625,-327.55);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAhBuIAAgMIAYAAQAEgBAAgGIAAhXIh6AAIAABXQABAGAEABIAXAAIAAAMIhIAAIAAgMIAYAAQADgBAAgGIAAi1QAAgGgDAAIgYAAIAAgMIBIAAIAAAMIgXAAQgEAAgBAGIAABTIB6AAIAAhTQAAgGgEAAIgYAAIAAgMIBJAAIAAAMIgYAAQgEAAAAAGIAAC1QAAAGAEABIAYAAIAAAMg");
	this.shape_40.setTransform(-33.8,-330.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-78.9,-354,157.9,270.1), null);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIAJQgEgEAAgFQAAgFAEgEQADgDAFAAQAFAAAEADQAEAEAAAFQAAAFgEAEQgEAEgFAAQgFAAgDgEg");
	this.shape.setTransform(61.5,30.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgGgDgBIgWAAIAAgLIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAAMQAAAQgOAAQgEAAgEgDQgDgCAAgFQAAgJALgCQgDgLgOABQgTAAgJASQgJASAAAdIAAA1QAAAGADAAIAWAAIAAALg");
	this.shape_1.setTransform(52.975,24.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_2.setTransform(39.325,24.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhnQAAgMgHgBIgSAAIAAgLIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhXQAAgFAEgEQADgDAFAAQAFAAAEADQADAFAAAEQAAAGgDADQgEAEgFAAQgMAAAAgNg");
	this.shape_3.setTransform(27.825,21.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AASBlIAAgLIAUAAQADAAABgGIAAhTQAAgjgiAAQgUAAgPAUQgNATAAAiIAAAtQgBAGAEAAIAVAAIAAALIhBAAIAAgLIAWAAQADAAAAgGIAAikQAAgGgDAAIgWAAIAAgLIAIAAQATAAAOgDIAABeQAQgoAkAAQAtAAAAAuIAABUQAAAGADAAIAVAAIAAALg");
	this.shape_4.setTransform(15.55,21.475);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgGBSQgJgIAAgUIAAhjIgXAAIAAgKIASAAQAHgBAAgIIADgaIAKAAIAAAiIAkAAIAAALIgkAAIAABjQAAAZAVAAQAHAAALgCIAAALQgKACgKAAQgSAAgHgIg");
	this.shape_5.setTransform(2.65,22.75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AggBlIAAgLIAWAAQADAAAAgGIAAikQAAgGgDAAIgWAAIAAgLIAJAAQASAAANgDIAAC4QAAAGADAAIAWAAIAAALg");
	this.shape_6.setTransform(-5.45,21.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_7.setTransform(-16.625,24.325);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_8.setTransform(-32.475,24.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AASBlIAAgLIAUAAQAEAAAAgGIAAhTQgBgjggAAQgWAAgNAUQgPATAAAiIAAAtQAAAGAEAAIAVAAIAAALIhAAAIAAgLIAUAAQAFAAAAgGIAAikQAAgGgFAAIgUAAIAAgLIAIAAQASAAANgDIAABeQARgoAjAAQAuAAgBAuIAABUQABAGADAAIAVAAIAAALg");
	this.shape_9.setTransform(-48.65,21.475);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgzA+IAAgkIAMAAIAAAdQAPAJAYAAQAmAAAAgdQAAgOgMgHQgIgEgUgFQgXgFgLgFQgPgKAAgTQAAgSAOgLQAOgMAXAAQAcAAAUANIAAAkIgMAAIAAgcQgPgKgVAAQgRAAgKAIQgKAHAAANQAAAPANAGQAHAEAVAEQAXAFALAHQAOAKAAASQAAAUgNALQgPAMgYAAQgdAAgWgOg");
	this.shape_10.setTransform(39.725,-5.725);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhnQAAgNgHAAIgSAAIAAgLIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhXQAAgFAEgEQADgDAFAAQAFAAAEADQADAFAAAEQAAAGgDADQgEAEgFAAQgMAAAAgNg");
	this.shape_11.setTransform(29.475,-8.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag/BRQgSgUgBgjQABggASgWQAUgUAeAAQAoAAAQAlIAAhHQgBgGgDAAIgVAAIAAgLIAIAAQATAAANgCIAAC3QAAAGADAAIAVAAIAAALIgmAAQgBgOAAgUQgRAmgnAAQgfAAgTgWgAgzgUQgPARABAcIAAADQgBAeAPAQQAQAQAZAAQAXABAOgSQAPgQABgdIAAgDQgBgbgPgRQgOgRgXAAQgZAAgQAQg");
	this.shape_12.setTransform(10.05,-8.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AggBlIAAgLIAWAAQADAAAAgGIAAikQAAgGgDAAIgWAAIAAgLIAJAAQASAAANgDIAAC4QAAAGADAAIAVAAIAAALg");
	this.shape_13.setTransform(-2.85,-8.575);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhnQAAgNgHAAIgSAAIAAgLIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhXQAAgFAEgEQADgDAFAAQAFAAAEADQADAFAAAEQAAAGgDADQgEAEgFAAQgMAAAAgNg");
	this.shape_14.setTransform(-10.475,-8.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AATBlIAAgLIATAAQAEAAgBgGIAAhTQAAgjggAAQgVAAgOAUQgOATgBAiIAAAtQABAGADAAIAVAAIAAALIhAAAIAAgLIAUAAQAEAAAAgGIAAikQAAgGgEAAIgUAAIAAgLIAIAAQASAAANgDIAABeQAQgoAkAAQAtAAAAAuIAABUQABAGADAAIAWAAIAAALg");
	this.shape_15.setTransform(-22.75,-8.575);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgwA3QgTgVAAgiQAAggAUgWQAVgVAfAAQAcAAARAOQASAOAAAXQAAAHgEAFQgEAEgGAAQgMAAAAgLQAAgMANAAQgIghgqAAQgZAAgQASQgQARAAAcIAAACQAAAcAPARQAQASAZAAQArAAAKgpIALADQgFAXgQANQgRAOgaAAQggAAgUgVg");
	this.shape_16.setTransform(-38.525,-5.725);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgHgDAAIgWAAIAAgLIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAAMQAAARgOAAQgEAAgEgEQgDgDAAgDQAAgLALgBQgDgKgOgBQgTABgJASQgJASAAAeIAAA0QAAAGADAAIAWAAIAAALg");
	this.shape_17.setTransform(24.525,-35.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag3AcIAAhUQAAgGgEAAIgVAAIAAgLIAoAAIAABkQAAAjAhAAQAVAAANgTQAOgSAAgcIAAg1QAAgGgEAAIgVAAIAAgLIAoAAIAAB+QAAAHAEAAIAVAAIAAALIgIAAQgTAAgNACIAAgmQgPAngkAAQgtAAAAgug");
	this.shape_18.setTransform(10.025,-35.625);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgyA3QgUgWAAghQAAghAUgVQAUgVAfAAQAfAAAUAVQATAVAAAhQAAAhgUAVQgUAWgfAAQgfAAgTgVgAgoguQgPARAAAdIAAABQAAAdAPARQAPARAZAAQAaAAAPgRQAPgSAAgcIAAgBQAAgdgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_19.setTransform(-6.275,-35.775);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhDBcQgJgGAAgLQAAgGAEgFQAEgEAGAAQAKAAAAAJQAAAJgJAEQAEAGALAAQANAAAJgKQAJgLAMgcIAAgCIg5h2QgDgGgDAAIgPAAIAAgLIA4AAIAAALIgPAAQgHAAACAGIAxBmIAshmQADgGgHAAIgRAAIAAgLIA3AAIAAALIgPAAQgFAAgCAGIg3B9QgMAfgIAKQgMAOgTAAQgNAAgIgHg");
	this.shape_20.setTransform(-22.375,-33.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-79,-60,158,102.2), null);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgHgDABIgWAAIAAgMIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAAMQAAAQgOABQgEAAgEgDQgDgEAAgDQAAgKALgBQgDgMgOAAQgTAAgJATQgJASAAAeIAAA0QAAAGADAAIAWAAIAAALg");
	this.shape.setTransform(52.025,33.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_1.setTransform(38.375,33.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgfBkIAAgLIAVAAQAEAAAAgGIAAhnQAAgMgHAAIgSAAIAAgMIAIAAQATAAAMgCIAACBQAAAGADAAIAVAAIAAALgAgMhWQAAgGAEgDQADgEAFAAQAFAAAEAEQADADAAAGQAAAFgDAEQgEADgFAAQgMAAAAgMg");
	this.shape_2.setTransform(26.875,30.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AATBlIAAgLIATAAQAEAAgBgGIAAhTQAAgjggAAQgVAAgOAUQgOATgBAiIAAAtQABAGADAAIAVAAIAAALIhAAAIAAgLIAVAAQADAAAAgGIAAikQAAgGgDAAIgVAAIAAgLIAIAAQASAAANgDIAABeQAQgoAlAAQAsAAABAuIAABUQAAAGADAAIAWAAIAAALg");
	this.shape_3.setTransform(14.6,30.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgGBTQgJgJABgTIAAhjIgYAAIAAgKIARgCQAIAAABgHIABgaIALAAIAAAhIAkAAIAAAMIgkAAIAABjQAAAZAWAAQAFgBAMgDIAAALQgKAEgJAAQgTgBgHgHg");
	this.shape_4.setTransform(1.7,31.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgfBlIAAgLIAVAAQAEAAAAgGIAAikQAAgGgEAAIgVAAIAAgLIAIAAQATAAAMgDIAAC4QAAAGADAAIAVAAIAAALg");
	this.shape_5.setTransform(-6.4,30.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_6.setTransform(-17.575,33.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_7.setTransform(-33.425,33.275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AASBlIAAgLIAUAAQADAAAAgGIAAhTQABgjgiAAQgUAAgPAUQgOATABAiIAAAtQgBAGAEAAIAVAAIAAALIhBAAIAAgLIAWAAQADAAAAgGIAAikQAAgGgDAAIgWAAIAAgLIAIAAQATAAAOgDIAABeQAPgoAlAAQAtAAAAAuIAABUQgBAGAEAAIAVAAIAAALg");
	this.shape_8.setTransform(-49.6,30.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_9.setTransform(41.775,3.225);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag1BKIAAgLIAVAAQADAAAAgGIAAhtQAAgGgDAAIgWAAIAAgMIAIAAQASAAAOgCIAAAjQAKgkAeAAQAOAAAIAIQAHAHAAALQAAARgOAAQgEAAgEgCQgDgEAAgDQAAgLALAAQgDgMgOAAQgTAAgJAUQgJARAAAeIAAA0QAAAGADAAIAWAAIAAALg");
	this.shape_10.setTransform(28.125,3.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag5BBQgMgLAAgRQAAgXAYgNQAYgMA0gFIAAgIQAAgVgKgJQgKgKgUAAQgfAAgLASQAKACAAAKQAAALgMAAQgNAAAAgPQAAgQARgKQARgLAYAAQA2AAAAAzIAABPQAAAGAEAAIAUAAIAAALIgkAAQgCgMgBgVQgGARgPAKQgOAKgUAAQgUAAgNgLgAgiAHQgUAJAAAUQAAAMAJAIQAJAIAPAAQAXAAAOgQQAPgQAAgaIAAgMQgtAFgUAIg");
	this.shape_11.setTransform(14.725,3.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag3AcIAAhUQAAgGgEAAIgVAAIAAgLIAoAAIAABkQAAAjAhAAQAVAAANgTQAOgSAAgcIAAg1QAAgGgEAAIgVAAIAAgLIAoAAIAAB+QAAAHAEAAIAVAAIAAALIgIAAQgTAAgNACIAAgmQgPAngkAAQgtAAAAgug");
	this.shape_12.setTransform(-8.875,3.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgyA3QgUgWAAghQAAghAUgVQAUgVAfAAQAfAAAUAVQATAVAAAhQAAAhgUAVQgUAWgfAAQgfAAgTgVgAgoguQgPARAAAdIAAABQAAAdAPARQAPARAZAAQAaAAAPgRQAPgSAAgcIAAgBQAAgdgPgRQgPgSgaAAQgZAAgPASg");
	this.shape_13.setTransform(-25.175,3.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhDBcQgJgGAAgLQAAgGAEgFQAEgEAGAAQAKAAAAAJQAAAJgJAEQAEAGALAAQANAAAJgKQAJgLAMgcIAAgCIg5h2QgDgGgDAAIgPAAIAAgLIA4AAIAAALIgPAAQgHAAACAGIAxBmIAshmQADgGgHAAIgRAAIAAgLIA3AAIAAALIgPAAQgFAAgCAGIg3B9QgMAfgIAKQgMAOgTAAQgNAAgIgHg");
	this.shape_14.setTransform(-41.275,5.875);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AASBKIAAgLIAUAAQAEAAAAgGIAAhQQAAgmghAAQgWAAgNAUQgPAUAAAhIAAAtQAAAGAEAAIAVAAIAAALIhBAAIAAgLIAVAAQAFAAAAgGIAAhtQAAgGgFAAIgVAAIAAgMIAJAAQASAAANgCIAAApQAQgqAkAAQAuAAAAAxIAABRQAAAGAEAAIAUAAIAAALg");
	this.shape_15.setTransform(31.1,-27);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgwA2QgTgVAAghQAAggATgVQAUgWAfAAQAeAAASAUQARATAAAgIAAAGIh4AAQAAAbAPARQAQASAZAAQArAAAJgpIAMAEQgFAWgQANQgRAOgbAAQgfAAgUgWgAA1gIQAAgagNgPQgOgPgXAAQgXAAgPAQQgPAPgCAZIBpAAIAAAAg");
	this.shape_16.setTransform(14.775,-26.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AASBlIAAgLIAUAAQAEAAAAgGIAAhTQgBgjggAAQgWAAgNAUQgPATAAAiIAAAtQAAAGAEAAIAVAAIAAALIhAAAIAAgLIAUAAQAFAAAAgGIAAikQAAgGgFAAIgUAAIAAgLIAIAAQASAAANgDIAABeQARgoAjAAQAuAAgBAuIAABUQABAGADAAIAWAAIAAALg");
	this.shape_17.setTransform(-1.4,-29.675);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AA2BkIg2iqIg3CqIgLAAIg0i2QgCgGgEAAIgTAAIAAgLIBBAAIAAALIgWAAQgEAAACAFIAsCeIA0igQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAAAgBAAIgYAAIAAgLIBHAAIAAALIgbAAQgBAAAAAAQgBAAAAABQgBAAAAABQAAABAAAAIA1CgIArieQACgFgFAAIgXAAIAAgLIBBAAIAAALIgTAAQgFAAgBAGIg0C2g");
	this.shape_18.setTransform(-24.85,-29.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-79.5,-51,159,102.1), null);


(lib.covwhiteRGBai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// co-v-white-RGB.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgyA1QgXgVAAggQAAgeAWgVQAVgWAeAAQAfAAAWAXQAVAVgBAdQAAAfgVAVQgVAVgfABQgdgBgVgUgAgvgvQgTAUAAAbQAAAcATAUQAUATAbAAQAcAAATgTQATgTABgdQAAgbgTgTQgUgUgcAAQgbAAgUATgAASAuQgCgDgCgKIgCgPQgCgIgFgEQgEgCgJAAIgGAAIAAAqIgRAAIAAhcIAfAAQAPAAAFACQAPAFAAARQAAAQgTAGQAGABADAEQADAEABAJQAEAVADAHgAgOgIIAOAAQATAAAAgNQAAgIgHgDQgDgBgMAAIgLAAg");
	this.shape.setTransform(526.5006,189.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACmLBQgKgEgNACQgPADgIAAQAAgDgKgCIgOgBQgRABgHgCQAAgDgSACQgjgBAAgBIgUgCIgTgBQgLgCgHAAQAAgBgQABQgRABAAgDIgOgEQgJgDAAAHQgDAAgFgDQgEgDgDAAQAAAFgJgBIgNgDQgNgCgLACQgRACgYgKIgJgEQgEgCgEABQgCAAgIgEQgIgFAAgBIgMABIgMABQgIACgFgBQgDAAgDgEQgEgFgDAAIAAAEQgEAAgEgCQgGgDAAgEQgCAGgBAAQAAgDgIgDQgIgCgFAAIgBABQgBAAAAAAQAAgBAAABQgBAAAAAAQAAAAAAAAQgDABgFgEQgEgDgEABQgEABAAgDIgIgGQgHgFAAAEQgCABgMgFQgNgGAAgCIgTgJQgBABAAAAQgBABAAAAQAAABAAAAQAAAAABAAIgEABIAAAAIgEAAIAEAAQABADgQgGQgCgDgFAAQAAgGgDgCIAAAGIgFgDQgGgDAAADIgIgIIgOgCQAAgCgNgGQgNgGAAgCQgKgEgDgKQgBgDgJgBIgOgCQgTgKgBABQgEgCgCABIABgDQgCAAgQgKQgLgIgDgIIgLgDQgCgCgBgDQgBgBgFAAIgDgHIgCgHQgEgBgCACQgCACgCAAQgBgLgTAAQgPAAAAgBIgNgBIgMgBQgSAFgHgCQAAgBgYgBQgaAAgDgBQAAACgJgCIgNgDQgLAFgDgEQgNgEgCABQAAABgGAAIgHgBIgJgCQgDgCgFAAIgOABQAAABgOgEQgGAAgFgHQgCgBgNABIgMAAQgEABgcgDQgcgDAAgBIgJgDQgGgCgDAAIgXgDQgDgEgbgGQgagHAAgBQgCAAgEgCQgDgDgDABQgOACAAgEQgJgEgPAAQAAgFgKgBQgNgBgBgBQgLgFgFgDQgHgGgQgDIgYgEQgDgDgDABIgHACIgGgDIgHgCQAAgEgJgBQgJgBgCgFIAJgCQgBgEgMgEQgMgFAAACIgSgJQgFAAgIgGIgLgHIgMgEIgNgBIAVAVQAAADAHAGQAHAGABAEQADACAGAHQAGAGAEABQAKADAEAHQADAAAHADIAKAFIAHAEQAHAEAAACQAFAAAHADQAGADAEAAIAEACQABAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAFABAGAGQACAFAWAEQAVAEAAADIAYAKQADAAAGADQAFAEAEAAQACgBATAGIATAFQADAAAIAEQAGAEAEgBQAEgBAJAEQAKAEADAAQAAgBARAEIAVAFQAEAAAJACIANAEQAAABAOACIAQABQAAAFBNAGQADADAjADQAiAEAAABQBPAIAAgBQADgBAkAEQAiAEAAgBQAIgBAAABQgGAAgMAGQgOAGgFABIgMgCQgLgCAAADIgGABQgDABgDgBQAAAGgUABQgTABAAgDQgQACAAgCIgGACQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgLgBQgDgBgDgGQgDAAgCADQgBABgGAAIgNgBQgXgCgDgCIgFgFIgJABIgMgEQgKgDAAADQgGAAgKgCQgCgGgEABIgJAFQgFADgFgCQAAgCgLgCQgKgCgEABQAAACgWgEIgbgFQAAgCgOgBQgPgBgBgEQgHAAgLgDQgMgDgGgBQgCgCgNgBQgNgBAAgCQgGAAgJgCIgOgEIgNgEQgNgEAAgBIgNgCQgKgCAAgBQgFAAgGgCIgLgFIgDgBIgCgBQgLAAAQALQACACAGACQAGACADADIAKADQAAABAFABIAHABQAAACASADQAAADAaAEQAZAFABAHIgKACQAAgDgXgDQgZgDgCgDIgagHQgVgHAAgDIgZgIQgUgIAAgBQgIgCgKgEQgNgGgFgGIgIgFQgJgEAAABQgCAAgHgFQgIgFAAgCQgKAAgPgHQgRgJgCgJQgPgKgGAAIgIgIQgFgFgDgCIgGgIIgJgFQgGgCAAgDQgGgEgHgIQgHgJgDgGQgDgBgEgHQgFgHAAgCQgDAAgDgJQgDgKgEAAQAAgEgDgGQgEgFAAgFQgBAAgFgTIgGgYIgHgkQgHgjAFAAIgFgVQgBAAgBgLIgBgNQgDAAAAgNQgBgOgCAAIgJhUIAAggQAAgcACAAIgCgjQgBggAEAAIgCgxQgCgsAFgDQAAgEAKgaQALgZgBgEQAIAAAHgOQAHgPAGgCQACgBADgFQACgGADgCQAAgFAGgGQAHgGAHgBIgDgEQAAAAAAgBQAAAAAAgBQAAAAABgBQABAAABAAIAEgCQAAAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAHgHIAKgHIAFAAIAEgCQALgIgHAAQgCgGAFgEQAFgFAFAAIAIgDIAIgCQAKgFAKgJIAQgRQAGgGADgBIAFgDIACgEQACAAAOgLQAAgCANgFQANgGAAgEQAEAAAJgGQAJgHABgDIAOgJQAHgEAIAAQAAgBAGgDIAFgCIAJABQAGACABgDIAXgEQAOgEAAgJQADgBACgEIADgEQABgCAEgDQAEgCABgDIgBAAQAAgFAHACIAJACIARgCIAIgFIAKgEIAJgFQAHgEACAAIAEgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAAAgBQAFAAAFgCQAHgCAAgDQgHAAAHgHQAHgGAEgBIANgHQAFAAAGgDQAAgDAHgCQAGgCAAgEQAGAAAAADQADAAAEgCIAHgCIAKACQAGABACgDIAOgGQAJgGAEAAQAAgBALgEQAKgDAEAAQAAgCAHAAQAHAAAAgBQAJAAACgCQACgBAAgHIAFgDIAEgEIAJACIgBAFIAEgCIADgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAfAAAHgDQAEgBAGACIAKACQALgGgFAAQgCgJASgGQATgGAAAFQAMgIAZAAQACgDAJAAQAJABACgEIAXgEQAUgEAAgBIABABIAVgFQAWgFADAAQAVAAAAgEIAIgCQAHgBAAgBIAggHIAvgHQAOAAAggFQAggGAQAAQAAgFBQAAQAAABAGACQAHACAAACQgIAFgXgCIgQABIgRABQgJAAgRADQgSADgJAAQAAgChXATQAAAFArgFIAxgGIAugGIAbgDQARgCAJACQAUgDABAKQASAAAAABIAHABQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAABIgIAAQAAADg1ACQAAABgRADIgUACIgTAAQgSAAAAADIgwAHIgSACIgUACQAAADgMACIgQACQgIgBgPAEQgQAFgHAAIgMACQgMACAAACQgEAAgGAEQgHAEgDAAIgJAAIgJgBQAAADgQACQgPADgBADQgCAKgMADQgOABgIACQAAADgTAHQgHAKgHAEQACAIAiABQAfABAHgEQADgCAagEQAXgDAAgCIAMgCIAMgDQAAgBAGABIAHABQARgEAJAAQAAgBAcgDIAcgFQAfgDAAgBIAVgCIAWgCQAAgCAmgCQAngDAFABIApgDQAkgDAAACQAMgCAYACIAcgBQASgBALACQAAADAJACQAJACAAgCIAQABQAAgBAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQADgBAKACQALADAAACQgEACgWABIgVAAIgmABQgCADgWAFQgVAFAAACIgQgBQgPgBAAACIgWAAQAAAFgZABIgegBQAAADglABQglACgBAIQARADAXgDIAngGQAAACAkgCQAjgBAAABQAFAAALgDQAEAAAEACQAFADAEAAIAQgBQAJABgEAGQgFAIghACIghACQhWAFAAADIgTACQgTACAAgCQgGgBgJADQgLADgDAAIgRACQgCACgGAAIgKgBQgGABgJAGQgIAGgGABQAAAFgdAEQAAABgHACQgIADAAABIgTADIgKACQgLACgBACQgRAAgMAMQgGABgKAFQgKAGgGABQAAgBgNAFIgPAFQAAgCgFABQgEAAgCACIAEABQgBADgMACIAAgEIgOAFQAKAIgUAEQgWAEAAACIgTAGQgNAFgGABQAAgCgvAQIgRAGQgRAGgCADQgTAAgDAEQgFAAgHAFQgGAEgFgBQgGAAgFAFQgGAGgFAAQgCgDgFACIgIAEIgKAFQgFACgFABQgBABgLADIgNACQAAAFgJACIgOADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABgBAAQgCADgEAAQgEAAgCADQgDAEgDACIgDADQgBABgEAAQgBgCgGgBQgFgCAAAEQgFAAgBAFQgDAHgCABQAAADgJAAQgOAJgCAAQAAACgMACQgLADAAAEIgMAGQgIAFAAADQgFABgFAEQgGAEgEABIgGADQgEACgCAAQgRAJgCAAQgEAEgFAAIgQAMQAAADgIAFQgIAEAAADQgGAEgOACQgBAEgEACQgFACgBABQgFAAgEAIQgEAHgDABQgEABgIAHQgIAFgDAAQAAAFgHAEQgIADgBAFQgSALgLANQgEAAgGAGIgIAKQgGAIgFADQgBADgFACQgFACAAAEQgCAAgHAJQgGAIgDAAIABADQgFAAgFAHIgHAKIgIAIIgHAJQgDAHgLANQgJALgBAJQADAAAGgHQAIgJACgBQAGgKAEAAQAAgDAHgFQAGgFABgCQgCAAAKgJIALgJQAGAAAEgJQAEgJADAAIAGgGQAGgFACAAQACgEAHgEIALgHQAAgCAEgFIAHgFIAVgPQADgHAUgGQABgDAJgEQAIgEAAgCQgBgEAGgCIAIgDIAWgOQAEAAAFgFQAGgEADAAIAhgUQAGgCARgIQATgJAAgDQAHgBACgDQAEAAABgDQACgDACAAQAHgCABgCIAIgEQAFgDAAgBIAGgDIAFgDQAAADAMgFQALgFACgDIAHgCQAFgCAAgBQAHgBAOgJQANgIAIAAQADgEAJgCQAIgCADgDQAEAAAGgEQAFgEAEAAQAFgFAIAAIAIgIIAHAAIAGgBIASgHQAAgBAGgCIAHgBQADgEAKgBIALgCQABgCAHgDQAIgEAAgCIAQgDQAAgCALgDQAJgCAEAAQAAgGANgBQANgBACgCIApgMQAhgJAAgFQAEAAASgFQARgGAAgBQAFAAAJgCQAKgCAAgEQAygGAAgEQALAAAQgFQATgHAHgBQAAgBAYgFIAbgFQAAgBAdgGIAhgHQAIgCANgBQAAgBAFgBIAHgBIATgEQAMgDAHABQAAAIgWAFIgeAFQgQAEAAACQgDAAgHAFQgHAFgFgBQAAAAgBgBQAAAAAAAAQAAAAgBAAQgBAAAAAAQAAACgZAIIgHAFQgEADgEAAQgDAEgGABIgMABIgbAJQgQAFgMACIgEADQgEADAAACQgEAAAFAEQAFADAAgEIAMgBQAKgBAAgCQAfAAgQAFIgHAEIgGAGQgCABgHgCQgEgBgCAGQgJgBgIAEQgKAEgIAAQgFAAgHAEQgGAEgEAAQAAAEAGAAIAGgCIAHgCQAAANgmACQgBADgGABQgDACgEgBQgEAAgDABQgBACgPAFQgFAGgSAAQgLABgBAGQgEgBgFACQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgEgCgBABQAAABgFAEIgIAEQgOAFAAACQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIABACIgGACQgEACgCgBQgBAGgKABIgOgBQAHAFgHADQgFACgGAAQAAgBgIAEIgIAEQgDAGgPAAQAAgDgGACIgEADQgBgDgEAFIgEAIIgGgCQgBAAgBAAQgBAAgBAAQAAAAgBABQAAAAAAABQgFACgIAAQgEAAgMACQgNADAAADQgDAAgEAEQgFAEgDAAIgbAKQAAAAAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgDADQgEAAgDACQgDACgCAAQAAADgEABQgEACgDAAQgFgBgDAEQgEAFgDAAIgHAEIgFADQAAAGgKACIgOABQAAABgFADIgHADQgDABgHAIQgFAHgGgBQgHgCgJAJQgRAEgBADIgFACQgCABAAAEIgJgBQABABAAAAQABAAgBABQAAAAAAAAQgBABgBAAIgEAAQgBAAgBAAQAAAAAAABQgBAAAAABQAAABABABQAAAGgKAAQgCgCgGADIgJAEQgRAHgIAKQgJABgIAEIgPAJQAAAEgMAGQgMAHgCAFIgJAEQgGACAAAEIgMAFIgGACQgDABgCADIgCADIgEACQgJAHAAACQgDAAgCADQgDAEgCAAQgHABgFAEIgNAPQgHAIgJADQAAAGgOAJQgOAKAAAHQgEACAOALQAPANgBADQgFAAgGAKQgFAKgBAGQgDAAAPANQAPAMAAgEQAGAAAIAHQAIAHABAGQAAAEAKACQAKACACACIAMAJQAGAAALAGQALAFAGAAQAAAHArAAQAMAMAIAAQAAABAIAAQAJABABABIALAAQAGABAFADIAOAJQANAGAFgCIAKgCIALgCQAEADACAAQgCAEADACQACABANgBQAMAAACAEIATABIAIABIAJABQAAgCAPADIASADQADgEAGAAIALAAQABACAHAAQAHAAADADIAEAKQAEAIADgBIACAAIABgCIABgNQABgFAFAAIAKAAIAPACIARAAQAAgCAKADIAMAEQAAgFAKgCQAKgBAAAGIAugFIgBgCQADgCgDgPQgEgPABAAIgEgNQgFgMABAAQABgCgBgFQgBgFgCAAIgBgUQgBgFACgMQABgOACAAIAAgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBABAAQAFAAAAgZQACAAACgIIADgJQAAgFADgGQADgHABgFIAIgfIAIgQQAFgKAAgGQAEgCACgGQADgIADgCQAHgGgBgHQAMgMgBAAIAEgGQADgCACgEQgCgFAEgBQAAgCAFgGQAGgFAAgDQACgBAFgGQAFgHACAAQAAgDAFgDIAIgGQACAAAEgEQADgEAAgCQANgGAPgPIAFgCQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIgRANQgFACgFAIQgFAHgBAFQAGgBADgDIAGgIQAPgGAAgBQAIgCANgKQALgJAKAAIAIgBQADAAADgDQABgBAAAAQAAgBABAAQAAgBABAAQABAAAAAAQAAgDAEgBQAAgDAJgHQAIgHAFgCQADgBAFgEIAIABQACgCAFAAQABAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBIAIgGQAHgGAAADQAGACAAgLQAGgBAFgEQACgCAJgCQAAgDACgDQADgDACAAQAAgCAMgGIANgHIACgFQABgCAEgBIAGgCIAGgFIAFgBIAFgCQAEgEAHgDQAIgDADgDQAFgEADACIAEADQADAHgOAHIgSAIQAAACgSAJIgMAJQgIAFgCAFQgEABgIAGQgIAGgGABQAAAIgLACIgMAJQgGAFgCAFQgIACgHAIQgCAAgDADQgDACgEAAQgGABgCAHQgIAEgCAJQgEACgEAFIgIAIIgPAMQgKAHAAAHQgNAGACANIgDAEIgCAGQgFACgBAJQgCAAgEAFIgFAFQgJAKAAgEQgDABgBAHQAAAGgIAAQAAABgEAEIgFAEIgBALIgGAJQgEAGgBAEIgMAKIgEAMIgGAEQgBACABAFQgBAAgEAHIgDAJQgDABgFAIIgHAHQAAATgIADQgGACABAJIAAANQgEAAgBAZQgBAZABAAQABgJAIgNQAKgOABgHQADAAAFgIQAEgGAAgDIALgUQACgBAFgIQAEgHAEAAQAEgPALgCQgCgKAMgGIANgPQABgEAJgIQAIgHAAgFQAFgCAGgIQAFgJAFgCQAAgDALgJQAJgIAFgDQAAgDALgHQAKgGAAgCQAGgEANgNIAPgNQAEAAADgFQADgFAEAAQACgEAHgGQAHgFAEgBQABgDAFgEQAHgEABgCQAIAAALgMQAMgMAGAAIAKgHQAIgFAAgCQADgBABgDQAAAAAAgBQABAAAAAAQABgBABAAQAAAAABAAQAIAAgCgGIAGAAQAAgCARgIQAQgJAEgBQAAgEATgKQARgJAGAAQADgGAJgFQAIgEAHgCQAAgBAJgEQAJgEACAAQACgCAUgJQATgIAAgBIAEgEQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAQABAAABAAIAGgBQAAgCAIgDIAIgCQADgDAIAEQACgJAFAAQAGgGAIAAQAAgCAHgCIAKgDQAFgHAZgGQABgCAGgBQAFgCACgCIAGgCIAHgCQAAgCAGgBQAGgBAAgBIAEADIAdgQQAAgBAMgDQALgCAAgCQAXgGAAgCIAJAAQAHAAADgEQADAAAPgJQABAAABAGQAAgIAVgEIAMgEQAJgDABAAQAQAKgEgHIgCgDQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAugJQACgEAXgEQAWgEAAgBIAIgDQAEgCADAAQAAgDARgBQATgCABgCQADAAADgDQADgDADAAQAAgCALAAQAngIADABQAAgCAvgIQAHABANgDIAVgGQAYgFAGAAQA9gJAGAAQAJgBAVgEQATgEAMAAQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAKAFQAIADAAgGIAUgCQA+gHAAACQADABAZgFIAigBQAfAAAAgCIBjgBQAAgCAoADQAsAEAEAAIAKAAQADAEAEgCIAIgCQACAHgDgBQgBAAgBAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgFAEgNAAQAAAAAAgBQAAAAgBAAQgBAAAAAAQgBAAgBAAIgFACQgEAAgDgCQgDgCgCAAQgNAHAAgEQgQACgIgCQAAgCgMABQgMACAAABQgLAAgKABQgCAFgGgCIgKgDQAAADgLAAQgKgHgCACIgDADIgFABQgDADgGABQgDAAAAAHQgMAAgCAIQgCAIAMAAQACADAKABQAKABADACQAAgFAHADIAKADQAAgEANACQAIABgDACIgFADQgCACgJAAQgIAAgEgCQAAABgHABQgGABgBAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCADQgKAAgIACQgKADgHAAIgqADQgCAEgLAAIgRAAIgtACQAAABgfAEQggADgFgBQAAAGgzgBQAAABgIADIgJACQgYAAAAADQgFgBgOADIgiACQAAABgVAEIgYADQAAgDgKAHQgLAGAAACIAhAAIAbgEIATACQADAAAFgCQAEgCAFAAIAOgDQANgCAAACQAFABAHgFIAOABQAAAFALgHQAKgBARgDQAAgCAJAAQAGgBAFABQAGACAGgBQAGgCAFACQAAgDARgDQARgEAAAFQArAFAAgDIAJABQAGABAAADQgNAHgDgBQgFgBgKABQgLABAAADQAkgDBBACQANAAAaAEQAYADANAAQAlAAA5AKQArAFAAAFQAFAAAXAFQAZAFAAADIAIAAQAEAAABgEQAJgDAFAAQAFAAAFACQAAABAIACQAIACAAACQATAAAZAOQAPASgBAAQAAAGASAAIgLgKQgIgHAJAAQAGAAAJAFQAJAFAFAAQAqAWAEAAQAAABAPAEQAOADAAADQADAAAHAEQAIADADAAQAAABAoAOIAZAOQASALAAAHQAEAEAFACQAAACAJAIQAKAIAAADQAHAMACAAQAAADAEAGQAEAGAAAEQABAAACAHIACAJQAEAAAFATQAFATADAAIAJAUQAFAMAAAKQACAAAFAbQACAAAGAXIANAyIAHAaQAHAXgDAAQACAGADApQABADgCAFIgCAIQgCAAAAAGIAAAJQgCAAgDAIIgDAJQgDABgFAPIgFAPQgBADgDAAIgDAAIgBAGQgBAAAAAAQgBABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgIAAIAAAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgEACgBAGQgCAAgDAGQgDADgCgFQgHABgFAFQgEAAgCAIQgCAIgCABQAAAHgGADQgGADgGgCQABANgJgDQgMgEgCAEIAAAMQgCABgDADIgCADIgEACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAGQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQgJgCAAABIgKAEQgEAAgCADQgCAAAAAFQgBAFACAAQgBAKgNABQAAgDgIgBIgLgCIgGADQgGACAAADQAAADgMACQgEABgKAFQgKAFAAADQgCAAgNAHQgNAHAAACQgFACgDAHQgCAFgHgCQAAACgDAEQABAAACAEQACADAAACQgGACgLgDQgLgDgFABIABAKQAAAGgFAAQgCgDgEACQgBABAAAAQAAABAAABQgBAAABABQAAAAABAAQADACABADQgEACgFAAIgJAAQgCAAgHgFQgHgEgFAFIgDAGQgBACgEABIgHAEIgFADQgBAFgJAAIgPgBQAAAHgJADQgLADgCADIgDADQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBgBQgCgDgDAAQgEgBAAAEQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAGIgMABQgDAAgGAFQgEADgDgHQgDgBgDAFQgDAEAAAEQgFAAgFADQgFADAAAEIgGgBIgHABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAADQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgEAAIgPADQgFAGgHACIgPACQAAAAgBAAQAAABAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAADABAGQAAAEgNgEIgHAFQgHAEAAADIgJgBQgEABgCAGIgJADQgHABgCgEQgGADgHAFIgMAIQAAAGgRgDQgSgDAAAIIgFgCQgBgBgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBAAgDAFQgDAEgCgBQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgGAHQgDAFgFgBIgEAAIgFACQAAAAgBABQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgJAEQgHADABABIAYAAQAOgBAIgDQADgBAcgFQAYgFAAgDQADgBAFAGQAEAGAEgCIARgFQACgFAZgDQAAgBALgDIALgEIALgCQAJgBgBgDQARgHABAHIAPgGQAKgDAHABQgSALgFABIgpAUQABgGgKACQgIABgEAEIAEADQgEAAgUAIQgUAIAAACIgJABQgIACAAADQgFABgFgBIgJgDQgBAKgHgBQgMgBgCABQAAABgIABQgJAAABAEQgRAJgKABQgWADAAACIgIABQgGgBAAgBQgDgBgEABIgHACQgWAMAAgIQgDAAgEACQgFABgBADQgDgBgIADIgGADQAAABgVAEQgGAAgFAEQgGAEAKABQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAIADABQAAgDARAAQAQgBAAgCQAIAAAWgHIAdgEIAkgGIAVgEQATgEAAABQAIAAAMgEIASgHQgBgBAOgFIAQgEIAVgIQAPgHAEAFIgUAKIgRAHQgGABgLAGQgMAFgEABQABADgKACIgNACQgKAGgLACQAAgCgMAIQgCAFgDgFIgDgDQgEABgFADQgFAEgDAAIgKADQgJABAAADQgFAAgGACQgGACgGAAQAAAJgLgMQgCAGgBAAQgDgFgJACIgLADQgFAGgBADQgFAAgEgDQgFgDgEgBQAAAFgGAEIgLAEQgXALgNgLQgMAEgDAAQAAAHgPAAQAAACgMADQgLADgEgBQAAgEgIAAIgMAAQgCAHgBAAIgHgBQAAACgVgBQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAADgJAAQAAgGgEAIIgDAEIgIAEQAAgEgHABIgIACQgCABgQAAQgOAAgBADIgYAAQgFAAgHgDIgMgDQgHAHgIAAIgRgDQAAABgKADQgKACAAABIgPACQgMACgEgEQAAgBgNAAIgRgBQAAAFgHgBIgKgCQAAADgPABIgFAAQgKAAAAgDgACUKCQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAIAEgCIAdgDQAZgCABAEQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBQACgDADAAIAEAAIADgBQAEgBAGABQAHAAADgBIAOgFQAJgCAHAEQABgGAEADIAFAFQADAAAFgFQADgGAEABIAHACQADAAAFgDQACgBAFAAIAHgCQAFgBABABIABAFQAEAAAEgGIAJgDIASgFIALgBQAHgBAEgDQALgFADAAQgFgBgPAEIgTAGIgfADQgPACgVgBIgWAEQgSACgBgEQgNACgBABQgKADgJgCQgKgDgNACIg1ADQgFABgCgFIgKADQgBgDgFgBQgIgBgCgCQgLAEgEgBQgMgDgagBIgagBQgFAAgJgCIgOgBIgMAAIgKgCIgBACQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgDgCgCABQgBgDgFgBIgHAAQgKgDgYgBIgOgCQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIgDABQgLABgIgDIgFgDQgCgCgDABIgNAAQAAgCgFAAIgHAAQgDgBgEAAIgIAAQgEAAgDgCIgGgEIgPgDQgJgBgEgEQgFgEgBAAQgCACgEAAIgKgCQgGgBgEABQgBgEgMgDQgIgCgGAAQgDABgDgDQgCgCgDABQgDAAgGgBIgKgEQACABgSgIQgQgHAEgBQgCgBgHAAQgGABgDgCQgIgEADgCIgQgFQgDgBgPADQgRADgOgBIApAdQARgBALAEIANAFQAIgBAMAGIAMAFQAKAEAAACIAHgCQADgBACADIAGAHQACgBAIgBQAJgBABADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIASAGQADACAFAAIAIABIASAFQAEACAFABIAJABQAQAEAjAEQA8ALA6AFIAbACQARABALACIAhABQADgBALACIAQABIAMgBQAIgBAEACQABAAAAAAQAAAAABAAQAAAAABgBQABAAAAAAIABgBQABAAAAAAQAAABABAAQAAAAAAAAQAAABABAAgAGCH/IgCgHQAAgDAHAAQABABAHgBQAHgBABgCIAPADQALACAAgEQAGgHAHAFIAMAHQAGAAAAgDQgBgEADgCIAHgCQACAAACAEQAIgIAQgBQAJAAAQABQAAgBAFgCIAGgDIARAAQAAgCAPAAQACAGAEAAQAAgGAIgBQAHgCAAACIAJgCIAJgCQAAAAABgBQAAAAABAAQAAgBABAAQABAAABAAQADAAACgDQALgFAIADQACAAATgEIAGACQAAAAABAAQAAgBABAAQAAAAAAgBQABgBAAgBQAAgBAAgBQABgBAAAAQAAAAABAAQABgBAAABQAFACABgBQAAgCAPgDIARgDQABgCAOgFQANgFAEAAQADABAEgEQAEgDADAAQAAgDAQAAQAGABALgHQAGAAALgFQALgGAGAAQACgDANgEQANgFAFAAQABgCAMgEQALgDAAgBIAVgIQADAAAEgCQAEgDAEAAIAKgEIAHgDQAEgCAEgBQABgDAGgBQAGgCACgCQAEAAAIgDQAJgEACgCQAEAAAHgEQAHgEADgEQAFAAAJgFQAIgFAGAAIAYgMQAAgBAVgIQAWgJACgDQAFAAAJgFQAIgGAGAAQAFAAAGgGQAHgHADAAQAEAAAGgGQAHgGADAAQAHAAAKgIQAEgCAHgHQAAgBAGgCQAGgCAAgCQgHAAAGgCQAFgCADAAQAAgEAJgBQAHgBADABQAAgDADgEQADgFAAgFIAQAAQAAgEAEgCIAIgFIANgIQAAgFAMgGQALgGAAgCQAMgCADgDQAGgEADgJQAFgBAQgbQAMgGAGgKIACgEQABgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAQADAAAFgJQAFgKAFAAQADgFAAgJQAFgDgBgEQABAAACgMQACgNACAAQAAgBgCgFIgEgGQAAAHgLAAIgFAGQgEAGACAAQAAADgHAGQgIAFAAACIgFAGIgGAIQgDAAgFAFIgIAFIgFADQgFADABAEIgJADIgHADIADAAIgBAEQADAAgMAKQgDADgIAAQgHABgCACQAFAAgFAHQgFAGgEAAQgJAMgOADQgEAIgOAFIgCACQgBAAgBAAQAAABgBAAQAAABAAAAQAAABAAAAIgKABQgCABAAAHQgbAFAAAGQgPALAAABIgJADQgGACgEAAQAAADgFACQgEACgEAAQgEgGgEAHQgEAHgCABQAAACgKAGIgMAGQgEABgIAGQgJAGAAAEQAAACgMAEIgQACQAAAEgJACQgJABABAEQAAABgaAFQAAAHgOAGQgLAFgKABQAAgFgOAHIgOAGQgDAAgJAEQgIAEAAABQgEAAgHADQgHADgEAAQAAACgJAEQgIADgCgBIgBADIgBADQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgDABgCgCQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAFIgDAAIgCgBQAAADgFABQgGABAAABQgEACgCgBQgDAAgDACQgDADgMAAIgIAGQAAABgKADIgNADQgNAGgDAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAAAAAABIgYAKQgYAGgGAEQAAADgXAAIgHAEQgEABgBAFQgFACgEgBIAAAFIgPAAQAAAGgGABQgHACAAgCQgDAAgLAFQgJAEgFgBQAAgBgGACIgHACQgDADgIAAIgMgBQgCAEgLAAIgbAJQAAABgFACIgJADQgFADgKAAQgDgDgDACIgFAEIgKgDQAAAHgNABIgTABIgIABQgFACgBADIgMgBQgcALgDgBIgUACQgSADAAACIgPADIgOACIgHACQgFACAAABQgIAAgQACQgVAEgDAEQACgCATAAQAAAEAZAAQADgEALABIAQACQAAgEANACIAOABQACAAADADQADACADAAIAAAAgAn2HeQgCAEgDAAIANAKQAJAGAEAAIADgDQABAAAAgBQAAgBAAAAQgBgBAAAAQgBgBgBAAQgBgDgGgFIgKgFIgDgCIgCACgAAUGwQACAEACAAIAIACQAFABACgEIADgBQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBAHgBQAHgCAAgBQAigBAAgFIAGABQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAFgBANADIAJgDQAGgDADAEQACADAFgBQAFAAACgDQACgCAFACIAIACIgEgEIADgGIAKgCQAGAHAAgFIASABQAFgCAHgHQACgBAKABQAJABADgDQAEgEAHAAIALABQACgFALABIAOABQAAgDAHABIAJADQAAABAKgHQAKgBAOACQAAgIAPgBQAAgBAVgEQAVgFADABQABADAMAAQAMAAACgEIACgFQAEgEADAFQACABAEAAIAGAAQAAgIABgCQACgBAIABQABAEAHgDIALgDQAEgBAKAEIAIgEQAAgFANgDIARgCQAHgDAEgGQADgCAHABIALABIgBgFQAEAAABgCQACgDADgBQADgBADABIAHACQAAgCAPgCIASgBIgCgEIADgBQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAJgBAHgEQAJgHAFgCQAXAAADgFQANAAABgCQAGAAgDgGIAKgBIAEgGQABgBAAgBQABgBAAAAQABAAAAAAQAAAAAAAAQADABADgCQADgCADABQAAACAHAAQAHAAAAgCQAHAAAEgDIAJgIQAHgBAEAAQACgEAEABQAGACACAAQAAgBASgGIAUgIQgDgDABgCQACgCAFAAQADADAFgCIAIgDQAAgBAHgBQAHgBAAgDIAGACQAIgFgEAAQgBgDAPgEQAQgEAAgCQAHAAAHgDIAOgIQABgCAIABQAHABAAgEIADgDQABgCAFAAQAEAAAHgDQAAgBAKgDQAKgCADABQgBgFAFgDQAGgEACgDQAPABAAgDIAHABQAEAAABgEIAKgIQAAgDAIgEQAHgFAEAAIALAAQAAABATgLQAAgDAHgFIAIgFQAGAAAIgHQAIgIAFAAQAAADASgNQAIgGAKAAQAUgNAAgCIAWgPQALAAAMgIQADgHAEAAQADgDAJgDQAJgEACgDQAFAAADgGQADgHADAAIAKgHQABgDAEgEIAHgGIAGgCQAFgBABgCQAAgFANgGQAMgHgBgDQAVgZADgBIAHgPQAFgKgHgDQAAgCgHgEQgIgDgBgDQAAgDgEgCIgHgFQgMgLgGgDIgQgHQgNgHAAgDQgGAAgJgFQgKgGgEgBQAAgBgJgFIgKgHQgEgBgIgFQgHgFgEAAQAAgBgSgEQgUgHgDgDIgQgIIgKABQgHABgEgBIgFgCIgHgBQgRgLgDAAQAAABgSgHIgJgDQgDgEgGgCIgKgBQgtgKgGgBQgGgHgWADQgSACgDgEQgDgEgHAAQAAgBgOACQgPACAAgDIgTgBQAAgEgGgBQgHgHgIAEIgNAFQgHAAgKgEIgRgGQAAAFgXgBQgWgBAAgJQABgEgFgBQgEgBgFABQgCADgIgCQgBgBgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAADgJgBQADAHAAAEQAHAAACAeQACAcgCAIQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABABQAAAAAAAAQgBABAAAAIgBAUQgBATgEAAQgBADADADIgIAQIgGANQgFAIAAAGIgGAPQgFAOgHAAIABAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIAAAEQgCAAgCAGQgBAGgDAAIAAAEQAAABgBAAQAAAAAAABQAAAAgBABQgBAAAAABIgFAEIgBAHQgDAAgBAFQgBAAgGAIQgHAJgFABQgBADgIADQgIACABAFIgCAFIgCADQAAACgEAEIgGAFQAEAKgSACQgBAGgHAEQgIAGgCADQgFAIgTAJQgCABgDAEIgFAFQgJAAgRAOQgUARgFACIgNAFQgJAEAAAEIgLAHQgGAFgGABQAAgBgFAFQgFAEABAAIgKAFIgKAGQAAABgLADQgMADAAAEQgJAAgRANQgSAMgMAAIgKADQgIAEgBABIgJAHQgFAFgFAAQgeAKgEAAQAAACgJAGQgJAFAAgEQgEAAgHADQgHAEgDADIgLACQgFABgEAFQgFAAgKAGQgJAGgEAAQgDAFgVAAQgCADgDACQgEABgBACIgGABQgEABgCgCIgGgDQgHgBgGADIgKAIQgBAFgNAEQgDAAgIAFQgHAEgEAAQgsANgHAAQAAADgZAHQgaAIgDADQgTACghANQgHADgOAAQAAAGgPAAQAAACgVAGQABgGgiAKQgEAAgGACIgKAEQAAgBgMAEIgPAFQgIAGgMACIgWAFIAFAAIABABIARACQAOACABgDQAcAAASAEQAsgBAAAFQAFABAvgHQAHgDAHAEIANAHQAAgCAQgCIAUgCIAQgBQAEABACADgAqtGZQgHgMAAgBIAHAFIAGAEQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIADgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgGAAIgCgBIgBAAIAAgBQgDgDgDgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgDgBQgjAFAAgEIgJgBIgIgCQAAgEgOACIgQADQgGAJATADQAWADAAABIAVABQARAAAAACIASAAIAAAAgAopGGQgDABAAAFIADAEIAEAFIAHgBQALAAgJgLQgFgEgEAAgAmTFsIAIAOIAFAFIAOACQABAAAAAAQABAAAAAAQABAAAAAAQAAgBAAAAIAOgCQAJgCAEABIBCgLQAAgCAVgDIAYgEQBOgSAHAAQAAgBAXgGQAXgFAEAAQAAgDAWgEQAWgDACgEQAHAAAKgEQALgDAGgBQAGAAALgEIAQgFQACgDAdgHQAagGgBgHQAYgBAAgDQAJgBARgHQAAgBAJgCQAJgCAAgBQADAAADgCQABgBAAAAQABgBAAAAQABAAAAgBQAAAAAAgBIAGgBIAFABQAAgDAQgFQAOgEAFAAQACgDAJgDQAKgCAAgDQAEAAAIgDQAJgDACgDQAGAAALgEQAJgEAFgEQAGgFAPgDQABgCANgEQANgEAAgCIANgGIAOgHIAPgFQAKgEADgEQACAAAJgFQAIgEAAgBQAEAAAIgEQAIgFADgDQAKAAAOgKQAOgKAIgBQACgEAUgJQATgKgBgCQAAgBANgHQAOgHAAgBIAHgGQADgDAFgBQAKACAEgGIAEgIQAEgIAFAAQAAgBAFgEQAGgDAAgCQAFgBAIgHQAIgHAFgBQADAAACgFQACgFADgBIAIgFIALgKQAEgCAFgHQAFgHAEgCQAAgFAOgMIAOgRQACgEAFgIQAGgIACAAQABgGAFgHIAGgMQACAAACgFIACgGIACgHQACgGgBgDQgFAAgJAOQgKAQgEACQAAAGgMAJIgLAKQgGAHgEACQAAAFgHAFIgKAKQgBACgIAFQgHAEAAAEQgDABgDAEQgDAEgFABIgEAFQgEADgCAAIgHADIgIADQAAACgEADQgFAEgBADIgKAGQgHAGgBACQgDAAgJAGQgJAGgCADQgKADgQANQgPAMgMACQgFAGgMAEQgLAEgIAAIgOAOQgFAAgHAGQgHAFgDAAQgCAEgIABQgHABgDADIgHADIgGADQgCAAgEAEIgFADQgCAEgJAAQgJABgDAEQgEACgDAAQgCAEgIABIgNABIgJABQgGAAgDABQgDABgDAHQgDAGgEABQgEAEgFgCQgHgCgDABQAAAEgFACQAAAEgVAJIgbALQgDAAgFADQgFADgDAAQAAACgNACQgEAEgIADQgHACgGAAQAAACgNADQgNADAAADIgNACQgKACgCADQgGAAgCABQgDABgFAFQgHAAgGACIgNADIgWAHQgBACgKACQgKACAAACIgbAHQgFAAgIADQgIADgFAAQgCACgOAEQgNADAAABQgDAAgFADQgFADgDAAQgBACgGABQgFABgCgCQgRAHgCAAQgDADgNADIgMACQgEABgKAEQgIADgEAAQAAACgOAAIgQgCQAAABgJADIgMACQgPAAgMAFQAAAFgLACQgMABAAABIgXAAQgQAAgFAFIgDACIgDADIgJADIgHACQgCADgcAEQgcAFAAACIgFAAIgFAAgAxuEwQAAgCgHgCQgFgCgEAAQAAAGAQAAgAzoD+IgCADIAOALIAKACIALACQAEAHAcAKQAbAKAAgGQgOAAAAgHQgQgCAAgCIgUgKQgCAAgEgIQgEgHgGAAQAAgDgKgBIgKgBIAAAAIgGACgAmhD9QgJAEgBADQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAIADAAQAAACAsgFIA0gGQAAgDAWgEIAcgFQABgDANAAIARAAQAFAAARgGQANgEAIACQAAgCATgDIAWgEQAAgFALACQAMACAAgEIAKAAQAGAAADgEIAJgDQAFgGAQACQAQABACgFQgIAAAHgEQAGgEAEAAIANgBIAEACIAFABIASgEQAAgCgFABIgHABQgDgGAcgHQAXgHAKAAQAAgBALgCQALgBABgCIAHgCIAHAAIADADIAFABQAAgBAAgBQgBgBABAAQAAgBAAAAQABAAABAAQgCgFAEgBIAJgCIAKAGQAKAGADgBIgHgDIgDgKIAGgFQADgBAFACQACABAMgFQALgFAAAEQADABAEgCQAEgCAAgCQAOAAADgFQAAgJAJAAQACgEAKAAIANAAQAFgBADgEQADgEADAAIAVAAIAEgJQADgDAEABIAGADQgBgJAGABIALADQADAAAEgDQAEgEADAAQACgCAJgFQALgFABACQAAgHAUgCQAUgCAAgCQAIAAAFgBIAFgDIAGgDQACgDALgDQAMgDAAAGQAEABAOgEQAGgEABgFQgEAAAEgHIAFgIQAEgCAAgJIANgHQAJgFAGAAQABACAKACIAMACQAAAEAMgGQALgFACgEQgHAAgCgMQAFAAAMgPQASgEAAgCQAMgCAOgGIAWgKQAFgFARgHQAOgGADgHQAGgCANgOQALgMAHAAQACgDAFgDQAFgEACgDQACgCAHgGQAHgFAAgEQACAAAFgIQAFgHAAgCQAEAAAJgXQAKgXgCgFQgCAAAAgMQABgMgEgCIADAAQgBAAgDgHIgHgRIgSgBQAAACgPgEQgPgDAAADQgmAHAAgBQgLABAAgCIgIABQgFABgDgDIgHABIgJABQAAgBAAAAQAAAAgBAAQgBAAAAAAQgBAAgBABIgGABQAAAEgMABQgLABgFgBIgPgBIgDAFQgBAAAAAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIgOABQgCAHgNgEIgUgGQgBACgIABQgFABAAAHQgYAAgEABQAAADgUABQgUABAAACIgZABQgLAAgDADIgBABQAAABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgQABQAAABgGACIgIABQAAgBgSADQgTACAAACIgMADQgIACgFAAIgJAIQAAAEgJgHQgDAAgBADIgCAFQgBADgEABIgGABQAAAEgMAAQgBACgEABQgEABgDADQgDADgGAAQAAgEgGABIgKACQAAAFgWgCQAAAGgJADQgLADgCACQgCAAgEADIgHAEQgEACgCgBQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgDAAgCgCQgEgCgCAAIgIADIgIACQgDgCgEACIgHADIgEAEQgEAEAAACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABIgBAEIgEAFIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgDABgCgCQgDgCgCABQgFAJgVACIgUAMQgKAEgEgDIAAgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAQAAgBgKAHQAAAHgEABIgIgCQgBgBgHADQgHADgBACQgFAAgDADQgDADABAEIgMACQgNADgEAFQgEAAgBAFIAAAGIgRAJQgEAGgIAAIgMgCQACAMgGACIgMAHQgMAIAAgFQgGgEgBADIAAAEQAAADgKAIQgLAGgEABQAAACgGAEIgKADQAAgGgFAEQgHAFACAAQAAAFgHAIQgGAHgFAEQgCAFgFADIgKAEQgJADgDgEIgIAHQgFAFAGAAIgCAHIgGAJQgFAGgCAAIgKAJQgHAHgCAEQgGAAgCADIgEAJQgEABgEAFIgGAHQACAEgZAYQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIAPgBIAqgFQAAAFARgHIAFAAIADgCQAAAAABAAQABgBAAAAQAAAAABAAQAAAAAAABIAEACQABgFAKgDIAJgEQAGAAAVgEQASgDAEAIQAAgBABAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAgBABAAQACgEACAAQAAgBAFABIAHAAQAAgBAGAAIAJgBQAAABAAAAQAAABABAAQAAAAABAAQABAAABAAQAAgKAqAAQAAgEAKgBIAOgBQAAgHAZgBQAZgCAAADQADgBAEgEQAEgDACAAQAAgCAHACIAIACQAAAHAVgMQAAgCAHgDIAJgCQAFAHAHgBIARgDIAOgBQAHgBAAgGQgEADgEAAQAAgEADgCQAEgCABgCIAOgCIAGgCQAAgFALAAIAPAAQAHAHAGgGQAJgKAEgBQAMAAAAgCQAFAAADAFQACAFgHAAQAAAEAHACQAGADAAgFQgEAAgBgDQAAgEAEAAQAAgCAKAAIAGgEQAFgCAAgDQAHAAAEgDQABgCAEABQAEABACgBQAEgHALAAQACABAHgDIAIgEQAVgLAAAFQALAAgDgBQgIgEgBgCQgHgCAGgCIAJgBIAFAGQACACAEABQAMAAAAgCIAYgLQAFAAAJgEQALgEAFAAQAAgEAMgEQAKgDAFAAQABgCAFgCQAFgCACgCQAQgEACAAQAEABADgDQAFgFADgBIAJgFQAHgDACAEQACADgLANQgEAAgHAGQgIAFgEAAQAAAFgNAGQgOAGgCAEQgCAEgKACQgIABgCAEQgEAAgHAFIgJAHQgcALAAgBIgTAPIgMAEIgLAEQgZAGgGAIQgGgBgGAEQgGADgEAAQAAABgMABQgLABAAAGIgQADQgLACgEAEQgMAGgHABQAAACgJADIgKAEIgEAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgKADQgEAGgJABIABADIgGACIgHACIgJAAQgFgBgEABIgKAGQgKAFAAgBQgIAAgPAFQgPAFgJAAQAAABgWAEQgWAEAAADQgdALAAgEQgEAAgIAFQgHAFgEAAIgQAFQgRAEgBABIgZAFIgkAJQgaAAgCAEIgIACIgIACQAAgDgUAHIgNAEQgIADgHAAQgKADgFAAIgTAAQgFAFgMAAQgNgCgFABQAAABgIACIgLADIgBgBIgIACgAz3D2QAEgHgIgCQAAgBgEgEIgFgFQgDAAgIgFQgHgEgEAAQgBgDgHgGQgHgGgDAAQAAgCgLgIQgLgIgEAAQACAFAGAIQAGAHAFADQANAKgCAAQADAFAGAAQAWATAAgCQACABAFgCQAAAHALAAgApzCuIAGAEQgEABgCADQgDAEADADQAFADgDADIgEAEQATgEAAgBQADgBAFABIAHACIAEgBIADgDIADgBIAKgCQgFgZACAAIgCgJQgCgGABgDIACgOQABgIABgEQADAAgBgIQgBgIgGgBIgMASQAAAFgGAJQgGAJABAEQgGADgCACIgEAJQgCAAgCAEIgDAFQAAAEgIgGQgBABAGAEgAnqBaQgEAAgDAIQgEAKgDABQgDAVgBAAIAAACQgDAAgDAUQgDAUACADQADgBAFgIIADgIQADgHACAAIAFgLQAEgIACAAIADgHQAEgFAAgDQACAAAEgJIAFgLIAIgGQAHgGAAgCQAEAAABgDIABgIQACAAACgDQABgEADAAQAIgJABgEQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIACgFQAIgFAHgLQAEAAAGgJQAFgJAGAAQAegLgOAAQAAgGAFgCIAJgDQAAgGAIgEQAIgEAAgFQAFgBADgEQAEgFADgBQACgDAMgGQALgFAAgEQAKgGAGAAQAAgEAIgFQAIgEAAgDIAGgEIAHgEIAHgFQADAAAIgHQAIgGABABIALgGQAIgFACgDQAHgFABgGQAFAAAGgBQAGgCAJgGQAAAHAMgIIAPgKQACAAAGgEIAHgGQABgBAIgDIAIgDQAhgKAAgDQAFAAAJgEQAIgDAGAAQABgEAFACQAHABACgIIAGgCQACAAAHgEQACgCAOgEQANgDAAgCIAJgDQAGgDAAgDQAQgCAAgBIAJgCQAHgCAAgBQAFAAAKgEQALgFAGgBQAAgBAIgDIALgCQA2gRAEAAQAAgBAOgDIAQgEQATABAAgGQAFAAALgDQAKgDAGAAIAfgIQAAgCAMgBIAOgBQAAgCAMgCQAMgBABgCQAEAAAGgCQAHgDAEAAIAMABQAHgBADgDQAXgCAKgDQAAgEAygEQADgFAeAAQASABARgEQAAgFA4gBIA+gBQAAgCAGABQABAAABAAQABAAAAgBQABAAAAgBQAAAAAAgBIADAAIgBgCQgEAAgEgIQgFgIgDAAQAAgDgHgHQgHgGAAgEQAHgCAJADQALADAAAIQAEABAFAEQAFAEACAEQADACAAAFIADABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAEADQAEgBAEABQAGABAMgBIAUAAIAmACQAhABAAABQAIABAHgBQAAgCAUACIAZADQArACAAACIAzAEQArAFAAAGQAKAAAUAFQAVAEAKAAQAAACAPADQAPACAAACQAHABAKAEQAJADAHABQADABAHADQAGADADAAQAAADAJAAQAKABABACIAcAJQAEAAAIAEQAJAEACADQAOAHAAgDIAEABIACACQAEAAALAGQALAGAAABQAFAAAIAGQAIAFAEAAQAAABAHAFQAHAEACAAQAAABAIADQAIAEABACQADADAKAFQAIAFADAEQAHAAgHgJQgGgKgFAAIgEgEQgEgDAAgCQgIAAgHgKQgEAAgKgJQgLgKAAgDIgLgBQgHgCAAgEIgDgCIgGgBQgIgIgCgBIgOgHQgGgEgHAAQgEgFgKgDQgEgBgBgCQgCgDgCgBQAAgCgSAAQAAgGgLgCIgPgCQgHAAgHgDQgIgEAAgEQgIAAgNgJQgNgKgHAAQAAgBgKgCIgKgBQgZgHAAgCIgPgDQgIgDgEAAQAAgEgdgGQgZgEgKAAQAAgCgOAAQgPgBAAgEIgXgDQAAgDgbgCIgbgDQgZgDgMAAQAAgBgMgBQgMgBgBgBIgbgBQAAADgogCQgBgCgOAAQgNgBAAACQgDABgGgBIgIgBQgRACgIgBIgKADQAAABgKAAIgMgBQAAADgVACQgVABgFgBIgwAEIg5AEQgFAAgYAEQgZAEAAACIgXACIgUADQAAAHgyACQAAADgkAGQgCADgJAAQgJAAgDAEQgFgBgGACIgJABQAAACgOABQgNABAAADIgeAJQgSAFgLAAIgdAKQgeAJgCgBQAAAEgNACQgOACgBAEIgOAEQgIACgFABQAAABgHADIgIACQAAABgKAEIgPADQgCAEgLADQgLADgCAEQgEAAgGADQgHAEgDAAQgVAFgFAHQgFAAgIAGQgJAGgFAAQgDADgHAEQgHAEgEAAQgCADgPAIQgEAAgJAHQgIAHgHgCQgBAEgJAAQgBAEgIADQgNAFgHAGIgPAJIgPAJIgJAIQgEAFgFAAQABgCgKAHQAAAGgYAPQgLAMgKAEQAAABgEADIgGAEQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAABgFAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEABQgDAEgMAHIgDAEIgEAEQAAADgEAEQgDAEgDAAIgFAHIgHAFQAAACgJAIQgDADgEACQgFABgDADQAAADgEACQAAADgDACIgGAEQgCACAAAEQAAAFgCACIgFADQgDAAgCADQgCAFgBAAQgBACgEAGQgEAFgCABQAAAGgJAGQgKAGAAAGQABAAgFARIABAIQgBAFgDABIgBABIAAAAIgBABgAxpmXQgDABgCACIgCAFQgHAAgCADQgCAAgGADQgFADgCACIgHADIgGADQgGAHgTAGQgCAEgKACQgKABgBADIgHAGQgGAFAAABQgOAAgBAHIgSAOQgEAAgPAKQgJAGgGAHQgCADgFADQgFADgCADQAAAHgIAEQgKAEgBAFQgCABgDAGQgCAEgDABQgBACgGAFQgFAEAAADIgJAJIgIALIgDACQACACAlgbQAmgdAHgBIAHgFQAEgDADAAQAAgBAEgCIADgEQgDgBAAgEIAMgBQAIgCACgCIADgCQAAgBABAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgCAGgDQAFgDACAAQACgDALgFQAJgEACgDQADAAAFgFIAHgHQAMgEABgBQADAAAHgEQAJgEADgBQACgCAHAAQAEABABgFQABgJANAAIAHgIQACgDAFABQAFABABgDQACAAAHgEQAHgFACgBQAAgCARgHQAQgHADABIgBgEQAGgBAHgEQAHgEAFgBIALgFQAHgEACgDQADAAAFgCIAHgDQACgCAFAAIAIABQACgFADgCQAGgHAPgDIAYgDQACgDAIgDQAIgDAEAAQAAgDAIACQACABAEgCIAGgEIAIgEQAEgCADAAQAEgGAOgEIAWgEQAGgBALgDQAOgEAAgDIAHgCIAFgDIAJABQAFgBAAgFQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgDIgGgDIgvAMIgCgBQAAACgLABQgKACAAABQgHAAgLAGQgLAGgGABIAAgDQgFAAgKADQgJADgFAAQgEgBgCADIgFAEQgEAEgCAAIgHgDIgIAEQgIADgBAEIADABQgBADgFAAQgEABACgEQgDAAgHADQgHADgEAAIgFACQgGADgBACIgDAFQgDABgDgBQgCAGgOAFQAAABgFABQgFAAAAABIgLACQgEABgCAHIgDABQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgKAAAAgCQgCAAgDACQgEADgCABIgOAHQgNAIACABIgNAGIgNgCIgDABgAlSlJQgFgDAKgGIALgHQAIgDAAgBQABgBABAAQAAAAABAAQABAAAAAAQAAABABABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQACACgOAJQgJAGgFAAIgEgBg");
	this.shape_1.setTransform(271.9321,70.8329);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABwDnIAAkXQAAgygageQgbgeguAAQgfAAgdAPQgdAPgkAjIAAFEIhjAAIAAnEIBjAAIAAA8IADAAQAdghAogSQAngSAqAAQBLAAAvAtQAxAxAABZIAAEWg");
	this.shape_2.setTransform(494.55,205.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjCCoQhLhEAAhnQAAhiBNhCQBNhDBxgBQB2AABNBCQBNBBAABlQAABqhMBCQhMBDh4AAQh1AAhLhEgAh4hvQgvAqAABCQAABGAuAsQAtArBIABQBPgBAugqQAugrAAhIQAAhBgwgrQgxgrhKAAQhGAAguArg");
	this.shape_3.setTransform(438.825,205.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiqEwQhCgnAAg8QABgyAegeQAfgfBBgOQgygbAAgeQAAgWAWgRQAWgRAjgIIAAgCQg3gVgdgkQgbgjAAgyQAAhIA8gqQA7gqBkAAIDRAAIAABFIhoAAQAeAbAMAWQALAVAAAdQAAAbgPAeQgNAcgTARQgiAghdAPQgoAGgOAGQgXAJAAARQAAASAnAOQAiAMBQAOQBNAOAlAjQAhAfgBAuQAABEg/AmQg/AmhvAAQhmAAhBgmgAhtCYQggATAAAeQAAAiAkASQAkASBEAAQBBAAAlgRQAlgSAAgfQgBgmg7gUQgsgOg9AAQgyAAggATgAhIjvQgdAYAAAhQABAlAbAXQAcAXAtAAQApAAAcgYQAbgYAAglQAAgggdgYQgdgYgnAAQgpAAgeAZg");
	this.shape_4.setTransform(386.35,217.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABoAAQBmAAA5A+QA8BAAAB7IliAAQAYCHCQAAQBVAABbg2IAABXQguAcgsAMQgxAOg9AAQhxgBhEhJgAhPiAQgjAdgKA2ID9AAQgDg0gfgeQgggeg0AAQg4AAgiAdg");
	this.shape_5.setTransform(336.35,205.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ai3DnIAAnEIBkAAIAABoIACAAQBHhxBKAAQA6AAA/A1Ig1BNQgXgTgbgNQgagMgSAAQgzAAgjAoQgjApAAA6IAADsg");
	this.shape_6.setTransform(296.35,205.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Aj1DJQhahSAAh3QAAh3BchTQBfhVCUAAQCWAABfBVQBbBSAAB4QAAB3haBSQhfBXiYAAQiVAAhfhXgAitiYQhGA8AABcQAABcBGA9QBFA9BoAAQBpAABFg9QBFg8AAhdQAAhchFg8QhFg9hpAAQhoAAhFA9g");
	this.shape_7.setTransform(236.525,200.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AijCiQhAhEAAhiQAAhoBCg/QBChABnAAQBnAAA5A+QA8BAAAB7IljAAQAMBCArAjQAqAiBIAAQBUAABdg2IAABXQgwAcgrAMQgwAOg/AAQhvgBhFhJgAhQiAQgjAdgKA2ID+AAQgDg0gfgeQgggeg0AAQg4AAgjAdg");
	this.shape_8.setTransform(171.8,205.55);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ai4DnIAAnEIBkAAIAABoIADAAQBHhxBKAAQA7AAA9A1Ig1BNQgWgTgbgNQgagMgSAAQgyAAgkAoQgkApAAA6IAADsg");
	this.shape_9.setTransform(132.5,205.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABFDgQgTgLgHgYQhAAuhHABQg2AAgkgiQgiggAAguQABg7A3gkQAfgUBVgbIBYgcIAAgYQAAgpgWgUQgWgTguAAQhZAAhHBLIAAhiQA7g+BtAAQBQABAxAjQA1AoAABKIAADoQAAAXATAAQARAAAkgYIAAA2QgjAVgTAHQgUAIgWAAQghAAgSgMgAhCAtQgxAbAAAkQABAcAUASQAVASAeAAQAsAAArgmIAAiDQhOAXggATg");
	this.shape_10.setTransform(85.3,205.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AjIDAQhRhQAAhnQAAiABhhUQBhhUCUAAQBcAAB7AuIAABXQg6gfg0gOQgzgOg3AAQhqAAhHA9QhHA+AABbQAABeBGA8QBGA7BwAAQBsAABug/IAABXQgzAYgwAMQg6AOhFAAQihAAhfhgg");
	this.shape_11.setTransform(28.225,200.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0.1,533.9,251.3);


(lib.BUTTONbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnmC7Qg1AAgmgmQglglAAg1IAAh1QAAg1AlglQAmgmA1AAIPNAAQA1AAAmAmQAlAlAAA1IAAB1QAAA1glAlQgmAmg1AAg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.5,-18.6,123,37.3);


(lib.covwhiteeps = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.covwhiteRGBai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.28,0.28,0,0,0,266.8,125.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.7,-35.1,149.5,70.4);


(lib.BUTTON = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8300").s().p("AgaA1IAAgQIAHAAIADgBIAAgFIAAgVIgagpQgDgFgEAAIgEAAIAAgQIA2AAIAAAQIgEAAQAAAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAACABADIAMAUIAMgWQADgFgGAAIgGAAIAAgQIAsAAIAAAQIgFAAQgEAAgEAFIgZAoIAAAWQAAAFAEABIAHAAIAAAQg");
	this.shape.setTransform(31.525,7.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_1.setTransform(21.625,7.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAAKAIQALAHAAARQAAASgKAGQgKAIgXAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgEgEQgDgEgIAAIgHAAg");
	this.shape_2.setTransform(12.35,7.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF8300").s().p("AgwA1IAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgDAAIgGAAIAAgQIA2AAQAWAAALAIQAKAHAAARQAAASgKAGQgLAIgWAAIgLAAIAAATQAAAFAEABIAGAAIAAAQgAgFgDIAHAAQAPAAAAgRQAAgIgDgEQgEgEgIAAIgHAAg");
	this.shape_3.setTransform(2.6,7.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_4.setTransform(-7.975,7.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaABQgZgBgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAJQAFAGAKABQALgBAFgGQAFgJAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_5.setTransform(-22.575,7.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF8300").s().p("AgbA1IAAgQIAHAAQAEgBAAgFIAAhDIgCAAIgKABQgCABgBAFIgCAIIgPAAIAAgfIBhAAIAAAfIgPAAIgBgIQgBgEgEgCIgKgBIgCAAIAABDQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAAAAAAAQABAAAAAAQABABAAAAIAHAAIAAAQg");
	this.shape_6.setTransform(-33.15,7.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF8300").s().p("AASA1IgSg2IgSA2IgaAAIgZhTQgCgGgEAAIgFAAIAAgQIAzAAIAAAQIgEAAIgEABIABAEIANArIANgrQACgFgFAAIgFAAIAAgQIAwAAIAAAQIgFAAQgEAAACAFIAOAsIANgsQABgFgEAAIgGAAIAAgQIAoAAIAAAQIgFAAIgEABIgCAFIgaBTg");
	this.shape_7.setTransform(38.15,-6.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF8300").s().p("AgoAoQgPgPAAgZQAAgYAPgQQAQgOAZAAQAaAAAOAOQAPAPAAAZQAAAZgPAPQgPAPgaAAQgZAAgPgPgAgPgbQgFAHAAARIAAAGQAAARAFAIQAFAIAKAAQALAAAFgIQAFgIAAgRIAAgGQAAgRgFgHQgFgIgLAAQgJAAgGAIg");
	this.shape_8.setTransform(24.525,-6.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF8300").s().p("AAHA1IAAgQIAFAAQAEgBAAgFIAAgYIgfAAIAAAYQAAAFAEABIAFAAIAAAQIg0AAIAAgQIAGAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgGAAIAAgQIA0AAIAAAQIgFAAQgEAAAAAFIAAAYIAfAAIAAgYQAAgFgEAAIgFAAIAAgQIA0AAIAAAQIgGAAQgEAAAAAFIAAA+QAAAFAEABIAGAAIAAAQg");
	this.shape_9.setTransform(13.075,-6.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF8300").s().p("AAXA1IgxhEIAAAuQAAAFAEABIAHAAIAAAQIgpAAIAAgQIAHAAQAEgBAAgFIAAg+QAAgFgEAAIgHAAIAAgQIArAAIAnA3IAAgiQAAgFgDAAIgHAAIAAgQIApAAIAAAQIgHAAQgEAAAAAFIAABUg");
	this.shape_10.setTransform(-1.625,-6.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF8300").s().p("AAcA1QgRAAgCgcQgCgJgCgDQgDgFgGABIgFAAIAAAWQAAAFADABIAGAAIAAAQIg0AAIAAgQIAFAAQAFgBAAgFIAAg+QAAgFgFAAIgFAAIAAgQIA8AAQAnAAAAAdQgBAVgWADQALAEAFAGQAEAHABALQAAAIAGAAIACAAIAAAQgAgJgEIAGAAQAIAAAFgEQADgDAAgKQAAgHgDgEQgEgEgHAAIgIAAg");
	this.shape_11.setTransform(-12.4,-6.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF8300").s().p("AAEA1IAAgQIAFAAQAFAAgCgGIgEgMIgdAAIgEAMQgCAGAFAAIAFAAIAAAQIgoAAIAAgQIAFAAIADgBIADgFIAfhTIAgAAIAfBTQACAGAEAAIAEAAIAAAQgAAEAEIgKgeIgKAeIAUAAg");
	this.shape_12.setTransform(-23.375,-6.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF8300").s().p("AguA1IAAgQIAGAAQAEgBAAgFIAAg+QAAgFgEAAIgGAAIAAgQIBcAAIAAAeIgQAAIgDgIQgCgEgCgBIgJgBIgRAAIAAAcIAIAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAIABgGIAAgDIAPAAIAAAlIgPAAIAAgEQAAgIgFABIgIAAIAAAdIASAAQAHAAACgBQACgBADgFIACgHIAQAAIAAAeg");
	this.shape_13.setTransform(-33.925,-6.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF8300").s().p("AgrA1IAAgQIAFAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAgBIAAg+QAAgFgEAAIgFAAIAAgQIA1AAIAAAQIgHAAQgDAAAAAFIAABEIAIAAIAKgBQADgBABgFIAFgQIARAAIAAAng");
	this.shape_14.setTransform(-43.125,-6.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.instance = new lib.BUTTONbkgd();
	this.instance.parent = this;
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_3
	this.instance_1 = new lib.Buttonshad();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-69,-27,0.5544,0.5544);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.BUTTON, new cjs.Rectangle(-69,-27,143.6,59.3), null);


(lib.ARToutline = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.MotherChildoutlineai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0.05,1,1,0,0,0,150.1,61.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ARToutline, new cjs.Rectangle(-151.1,-61.8,302.29999999999995,123.6), null);


(lib.ARTall = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.MotherChildallai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,-0.05,1,1,0,0,0,150.1,64.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ARTall, new cjs.Rectangle(-151.1,-64.6,302.29999999999995,129.2), null);


// stage content:
(lib.CO_Child_160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_165 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(165).call(this.frame_165).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(166));

	// RULE
	this.instance = new lib.RULE();
	this.instance.parent = this;
	this.instance.setTransform(80.1,453.1,1.0111,1,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(166));

	// LOGO
	this.instance_1 = new lib.covwhiteeps("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(346.9,672.5,1,1,0,0,0,266.9,125.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(166));

	// BUTTON
	this.instance_2 = new lib.BUTTON();
	this.instance_2.parent = this;
	this.instance_2.setTransform(81.2,454);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(166));

	// Child
	this.instance_3 = new lib.MotherChildCHILDonlyai();
	this.instance_3.parent = this;
	this.instance_3.setTransform(29.2,233.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.instance_4 = new lib.ARTall();
	this.instance_4.parent = this;
	this.instance_4.setTransform(29.2,233.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(71).to({_off:false},0).to({alpha:1},8).to({_off:true},45).wait(42));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(124).to({_off:false},0).to({x:-154.9},12,cjs.Ease.quintIn).to({_off:true},1).wait(29));

	// Mother
	this.instance_5 = new lib.MotherChildMOTHERonlyai();
	this.instance_5.parent = this;
	this.instance_5.setTransform(29.2,233.6);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.instance_6 = new lib.ARTall();
	this.instance_6.parent = this;
	this.instance_6.setTransform(29.2,233.6);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(31).to({_off:false},0).to({alpha:1},8).to({_off:true},85).wait(42));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(124).to({_off:false},0).to({x:-154.9},12,cjs.Ease.quintIn).to({_off:true},1).wait(29));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgASAu4MAAAhdvIAlAAMAAABdvg");
	var mask_graphics_1 = new cjs.Graphics().p("EgAsAu4MAAAhdvIBZAAMAAABdvg");
	var mask_graphics_2 = new cjs.Graphics().p("EgBFAu4MAAAhdvICLAAMAAABdvg");
	var mask_graphics_3 = new cjs.Graphics().p("EgBeAu4MAAAhdvIC9AAMAAABdvg");
	var mask_graphics_4 = new cjs.Graphics().p("EgB3Au4MAAAhdvIDvAAMAAABdvg");
	var mask_graphics_5 = new cjs.Graphics().p("EgCQAu4MAAAhdvIEhAAMAAABdvg");
	var mask_graphics_6 = new cjs.Graphics().p("EgCqAu4MAAAhdvIFVAAMAAABdvg");
	var mask_graphics_7 = new cjs.Graphics().p("EgDDAu4MAAAhdvIGHAAMAAABdvg");
	var mask_graphics_8 = new cjs.Graphics().p("EgDcAu4MAAAhdvIG5AAMAAABdvg");
	var mask_graphics_9 = new cjs.Graphics().p("EgD1Au4MAAAhdvIHrAAMAAABdvg");
	var mask_graphics_10 = new cjs.Graphics().p("EgEOAu4MAAAhdvIIdAAMAAABdvg");
	var mask_graphics_11 = new cjs.Graphics().p("EgEnAu4MAAAhdvIJPAAMAAABdvg");
	var mask_graphics_12 = new cjs.Graphics().p("EgFBAu4MAAAhdvIKDAAMAAABdvg");
	var mask_graphics_13 = new cjs.Graphics().p("EgFaAu4MAAAhdvIK1AAMAAABdvg");
	var mask_graphics_14 = new cjs.Graphics().p("EgFzAu4MAAAhdvILnAAMAAABdvg");
	var mask_graphics_15 = new cjs.Graphics().p("EgGMAu4MAAAhdvIMZAAMAAABdvg");
	var mask_graphics_16 = new cjs.Graphics().p("EgGlAu4MAAAhdvINLAAMAAABdvg");
	var mask_graphics_17 = new cjs.Graphics().p("EgG/Au4MAAAhdvIN/AAMAAABdvg");
	var mask_graphics_18 = new cjs.Graphics().p("EgHYAu4MAAAhdvIOxAAMAAABdvg");
	var mask_graphics_19 = new cjs.Graphics().p("EgHxAu4MAAAhdvIPjAAMAAABdvg");
	var mask_graphics_20 = new cjs.Graphics().p("EgIKAu4MAAAhdvIQVAAMAAABdvg");
	var mask_graphics_21 = new cjs.Graphics().p("EgIjAu4MAAAhdvIRHAAMAAABdvg");
	var mask_graphics_22 = new cjs.Graphics().p("EgI8Au4MAAAhdvIR5AAMAAABdvg");
	var mask_graphics_23 = new cjs.Graphics().p("EgJWAu4MAAAhdvIStAAMAAABdvg");
	var mask_graphics_24 = new cjs.Graphics().p("EgJvAu4MAAAhdvITfAAMAAABdvg");
	var mask_graphics_25 = new cjs.Graphics().p("EgKIAu4MAAAhdvIURAAMAAABdvg");
	var mask_graphics_26 = new cjs.Graphics().p("EgKhAu4MAAAhdvIVDAAMAAABdvg");
	var mask_graphics_27 = new cjs.Graphics().p("EgK6Au4MAAAhdvIV1AAMAAABdvg");
	var mask_graphics_28 = new cjs.Graphics().p("EgLTAu4MAAAhdvIWnAAMAAABdvg");
	var mask_graphics_29 = new cjs.Graphics().p("EgLtAu4MAAAhdvIXbAAMAAABdvg");
	var mask_graphics_30 = new cjs.Graphics().p("EgMGAu4MAAAhdvIYNAAMAAABdvg");
	var mask_graphics_31 = new cjs.Graphics().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:1.9003,y:300.0246}).wait(1).to({graphics:mask_graphics_1,x:4.4185,y:300.0246}).wait(1).to({graphics:mask_graphics_2,x:6.9366,y:300.0246}).wait(1).to({graphics:mask_graphics_3,x:9.4548,y:300.0246}).wait(1).to({graphics:mask_graphics_4,x:11.973,y:300.0246}).wait(1).to({graphics:mask_graphics_5,x:14.4911,y:300.0246}).wait(1).to({graphics:mask_graphics_6,x:17.0093,y:300.0246}).wait(1).to({graphics:mask_graphics_7,x:19.5275,y:300.0246}).wait(1).to({graphics:mask_graphics_8,x:22.0456,y:300.0246}).wait(1).to({graphics:mask_graphics_9,x:24.5638,y:300.0246}).wait(1).to({graphics:mask_graphics_10,x:27.0819,y:300.0246}).wait(1).to({graphics:mask_graphics_11,x:29.6001,y:300.0246}).wait(1).to({graphics:mask_graphics_12,x:32.1183,y:300.0246}).wait(1).to({graphics:mask_graphics_13,x:34.6364,y:300.0246}).wait(1).to({graphics:mask_graphics_14,x:37.1546,y:300.0246}).wait(1).to({graphics:mask_graphics_15,x:39.6727,y:300.0246}).wait(1).to({graphics:mask_graphics_16,x:42.1909,y:300.0246}).wait(1).to({graphics:mask_graphics_17,x:44.7091,y:300.0246}).wait(1).to({graphics:mask_graphics_18,x:47.2272,y:300.0246}).wait(1).to({graphics:mask_graphics_19,x:49.7454,y:300.0246}).wait(1).to({graphics:mask_graphics_20,x:52.2636,y:300.0246}).wait(1).to({graphics:mask_graphics_21,x:54.7817,y:300.0246}).wait(1).to({graphics:mask_graphics_22,x:57.2999,y:300.0246}).wait(1).to({graphics:mask_graphics_23,x:59.818,y:300.0246}).wait(1).to({graphics:mask_graphics_24,x:62.3362,y:300.0246}).wait(1).to({graphics:mask_graphics_25,x:64.8544,y:300.0246}).wait(1).to({graphics:mask_graphics_26,x:67.3725,y:300.0246}).wait(1).to({graphics:mask_graphics_27,x:69.8907,y:300.0246}).wait(1).to({graphics:mask_graphics_28,x:72.4089,y:300.0246}).wait(1).to({graphics:mask_graphics_29,x:74.927,y:300.0246}).wait(1).to({graphics:mask_graphics_30,x:77.4452,y:300.0246}).wait(1).to({graphics:mask_graphics_31,x:79.9633,y:300.0246}).wait(49).to({graphics:null,x:0,y:0}).wait(86));

	// ART-outline
	this.instance_7 = new lib.ARToutline();
	this.instance_7.parent = this;
	this.instance_7.setTransform(29.2,230.8);

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},80).wait(86));

	// HEAD1
	this.instance_8 = new lib.HEAD1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(80.05,106.05);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(31).to({_off:false},0).to({alpha:1},8).wait(75).to({x:-60},12,cjs.Ease.quintIn).to({_off:true},1).wait(39));

	// HEAD2
	this.instance_9 = new lib.HEAD2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(80.05,360.05);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(71).to({_off:false},0).to({alpha:1},8).wait(39).to({x:-81},14,cjs.Ease.quintIn).to({_off:true},1).wait(33));

	// HEAD3
	this.instance_10 = new lib.HEAD3();
	this.instance_10.parent = this;
	this.instance_10.setTransform(80,416.3,1,1,0,0,0,0,-15);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(141).to({_off:false},0).to({alpha:1},10).wait(15));

	// bkgd
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8300").s().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");
	this.shape_1.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(166));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-225.7,299.5,456.7,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 160,
	height: 600,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/CO_Child_160x600_atlas_.png?1570228478845", id:"CO_Child_160x600_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;